import ast,json,subprocess,types,pathlib,copy,hashlib
p=pathlib.Path('/tmp/salon-autoquote-review/app/services/contract.py');t=ast.parse(p.read_text());t.body=[n for n in t.body if not(isinstance(n,ast.ImportFrom) and n.level)];g={'config':types.SimpleNamespace(),'db':types.SimpleNamespace(),'payments':types.SimpleNamespace()};exec(compile(t,str(p),'exec'),g)
normal=lambda x:g['_normal_line'](x,1,{'id':101,'topic':'SYNTHETIC'},'2026-09-10T00:00:00')
raw={'line_id':'LN-1','contract_contour':'A','academic_submode':'A1','service_id':'custom','title':'SYNTHETIC','permitted_purpose':'Synthetic non-attestation purpose','deliverable':'Exact annotated source','formats':['docx','pdf'],'inclusions':['fact check','source check'],'exclusions':['new research'],'acceptance_criteria':['all 3 references checked'],'deadline':{'date':'2026-10-01','text':'Contractual Oct 1'},'correction_window':{'days':14,'scope':'Exact agreed defects'},'iterations':3,'price_amount':6011,'discount_amount':20,'customer_inputs':{'description':'Sample input','version':'v3','source_material_required':True,'source_material_provided':True,'original_prompt':'Synthetic prompt','sources_disclosure':'Synthetic sources'}}
executor='Семёнов Семён Юрьевич';cases={}
cases['A1']=copy.deepcopy(raw)
cases['A2']=copy.deepcopy(raw);cases['A2'].update(academic_submode='A2',author_participation={'required':True,'confirmed':True,'checkpoints':['Plan review'],'customer_decisions_and_data':['Synthetic data provided'],'confirmation_version':'specification-2.2'})
for contour in ['B1','B2']:
 r=copy.deepcopy(raw);b1=contour=='B1';mode='simple_license' if b1 else 'exclusive_right_alienation';name=executor if b1 else 'Synthetic Author';r.update(contract_contour=contour,academic_submode='',service_id='author',rights_schema_version=1,rights_mode_code=mode,actual_author_profile={'name':name,'party_role':'contractor' if b1 else 'third_party','confirmed':True},rights_basis={'code':'contractor_is_author' if b1 else 'third_party_written_assignment','evidence_ref':'SYNTHETIC-basis','effective_on_code':'full_payment_and_delivery' if b1 else 'incoming_right_effective_and_full_payment_and_delivery'},performer_profiles=[] if b1 else [{'name':name,'role_code':'author','creative':True,'consent_confirmed':True,'consent_ref':'SYNTHETIC-consent'}],rights_confirmation={'confirmed':True},rights_chain=([] if b1 else [{'from_role':'author','from_name':name,'to_role':'contractor','mode_code':mode,'basis_ref':'SYNTHETIC-consent','status_code':'documented'}])+[{'from_role':'author' if b1 else 'contractor','from_name':executor,'to_role':'customer','mode_code':mode,'basis_ref':'SYNTHETIC-basis','status_code':'documented'}]);cases[contour]=r
core=pathlib.Path('/Users/saymurrbk.ru/.codex/worktrees/salon-admin-rebuild/assets/js/salon-admin-core.js')
script="let s='';process.stdin.on('data',x=>s+=x);process.stdin.on('end',()=>process.stdout.write(JSON.stringify(require("+json.dumps(str(core))+").pricedLines({id:101,specification_lines:[JSON.parse(s)]},6011)[0])));"
checks=[]
for name,r in cases.items():
 base=normal(r);g['_validate_offered']({'lines':[base]});payload=json.loads(subprocess.check_output(['node','-e',script],input=json.dumps(base).encode()));after=normal(payload);g['_validate_offered']({'lines':[after]});changes={k:{'before':v,'after':after.get(k)} for k,v in base.items() if after.get(k)!=v};checks.append({'name':name,'ok':not changes,'changes':changes})
report={'core_sha256':hashlib.sha256(core.read_bytes()).hexdigest(),'backend_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'checks':checks,'synthetic_only':True};pathlib.Path('/tmp/admin-rebuild-spec-models.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps(report,ensure_ascii=False,indent=2));assert all(x['ok'] for x in checks)
