// Actual production static resources; all API and external traffic intercepted.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');const manifest=JSON.parse(fs.readFileSync(process.argv[2])),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
const expected=['assets/js/app.js','assets/js/salon-shell.js','assets/js/salon-experience.js','assets/js/salon-library.js','assets/js/salon-portfolio.js','assets/js/salon-ease.js','assets/js/salon-ease-preferences.js','assets/css/salon-ease.css'];
async function physical(page,s){const r=await page.locator(s).boundingBox();assert(r&&r.y>=0&&r.y+r.height<=900);await page.mouse.click(r.x+r.width/2,r.y+r.height/2)}
async function choose(page,selector,value,label){const field=page.locator(selector),trigger=field.locator('..').locator('.salon-select-trigger');if(await trigger.count()){await trigger.scrollIntoViewIfNeeded();await trigger.focus();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await trigger.press('ArrowDown');const input=page.locator('.salon-select-panel:popover-open input');await input.fill(label);await input.press('Enter')}else await field.selectOption(value)}
try{for(const width of [390,1440])for(const theme of ['light','dark']){
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width,height:900},colorScheme:theme,reducedMotion:'reduce'}),errors=[],checked=new Set(),pending=[],calls=[];
 await context.addInitScript(()=>{const now=Date.now();localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(now-60000).toISOString(),expiresAt:new Date(now+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.salon_analytics_qa_session_v1='1'});
 await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='akademsalon.ru')return r.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.request().method()});return r.fulfill({json:{ok:true,pay_online:true,authenticated:false}})}return r.continue()});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{const p=new URL(r.url()).pathname.slice(1);if(expected.includes(p))pending.push(r.body().then(b=>{assert.equal(crypto.createHash('sha256').update(b).digest('hex'),manifest.files[p],p);checked.add(p)}))});
 const go=async route=>{await page.goto('https://akademsalon.ru'+route,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready)};
 try{
  await go('/');assert.equal(await page.locator('html').getAttribute('data-theme'),theme);await physical(page,'.sh-quick-search');await page.locator('#experience-search-input').fill('курсовая');assert(await page.locator('.experience-search nav a').count()>0);await page.keyboard.press('Escape');assert(await page.locator('.sh-quick-search').evaluate(e=>e===document.activeElement));
  await physical(page,'.sh-menu>summary');await page.locator('.se-settings>summary').click();await choose(page,'[data-ease-assistant]','compact','Только значок');await choose(page,'[data-ease-theme]','light','Светлая');assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await choose(page,'[data-ease-theme]','system','Как на устройстве');assert.equal(await page.locator('html').getAttribute('data-theme'),theme);await page.keyboard.press('Escape');await page.waitForSelector('.sa-launch',{state:'attached'});assert.equal(await page.locator('.sa-launch').count(),1);assert.equal(await page.locator('.sa-launch').evaluate(e=>e.getBoundingClientRect().width),60);
  const faq=page.locator('[data-home-faq] details').first(),id=await faq.getAttribute('id');await go('/#'+id);await page.waitForFunction(id=>document.getElementById(id)?.open,id);assert(await page.locator('#'+id+' .se-faq-copy').isVisible());
  await go('/guide-kursovaya-za-nedelyu.html');await page.locator('[data-reader-size]').click();await page.locator('[data-reader-space]').click();await go('/guide-vvedenie-kursovoy.html');assert.equal(await page.locator('[data-reader-size]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-reader-space]').getAttribute('aria-pressed'),'true');await page.screenshot({path:path.join(out,'reader-'+width+'-'+theme+'.png')});
  await go('/services.html');await page.locator('[data-cat-filter=part]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('[data-cat-filter=part]').getAttribute('aria-pressed'),'true');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await go('/samples.html');await page.locator('.document-open').click();await page.waitForFunction(()=>document.querySelector('#pdf-loading').hidden&&document.querySelector('#pdf-page canvas'));await page.locator('#pdf-page-number').fill('4');await page.locator('#pdf-page-number').press('Enter');await page.waitForFunction(()=>document.querySelector('#pdf-page-number').value==='4'&&document.querySelector('#pdf-loading').hidden);await page.locator('#pdf-close').click();await page.locator('.document-open').press('Enter');await page.waitForFunction(()=>document.querySelector('#pdf-page-number').value==='4'&&document.querySelector('#pdf-loading').hidden);await page.screenshot({path:path.join(out,'pdf-'+width+'-'+theme+'.png')});await page.locator('#pdf-close').click();
  await go('/configurator.html?type=course');await page.waitForSelector('.sa-launch',{state:'attached'});assert.equal(await page.locator('.sa-launch').count(),1);assert(await page.locator('.sa-launch').evaluate(e=>e.parentElement!==document.body));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await Promise.all(pending);assert.deepEqual(errors,[]);assert(!calls.some(x=>x.method!=='GET'));assert.equal(checked.size,expected.length);results.push({width,theme,status:'PASS',staticHashesVerified:[...checked],errors,apiCalls:calls.length,apiWrites:0});
 }catch(e){await page.screenshot({path:path.join(out,'failure-'+width+'-'+theme+'.png')});results.push({width,theme,status:'FAIL',error:String(e),errors});throw e}finally{await context.close()}
}}finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({sourceCommit:manifest.source_commit,production:'https://akademsalon.ru',browser:'Chrome',network:'real static resources; API synthetic and external aborted',results},null,2));console.log(JSON.stringify(results))}
