// Real browser, exact candidate, synthetic API only. No production mutations.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const guide='/guide-kursovaya-za-nedelyu.html';
async function setup(opts={}){const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(()=>{const t=Date.now();try{localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')}catch(_){}});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready)};
async function physical(page,selector){const b=await page.locator(selector).boundingBox();assert(b&&b.y>=0&&b.y+b.height<=page.viewportSize().height,'visible control '+selector);await page.mouse.click(b.x+b.width/2,b.y+b.height/2)}
async function settings(page){await physical(page,'.sh-menu>summary');await page.locator('.se-settings>summary').click();}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n)}
const manifest=JSON.parse(fs.readFileSync(path.join(root,'../build.json'))),registry=JSON.parse(fs.readFileSync('scripts/salon-ease-20260924/faq-ids.json'));const env=await setup({width:360,theme:'dark'});try{for(const name of manifest.public_routes){await goto(env.page,'/'+name);const row=await env.page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,settings:document.querySelectorAll('.se-settings').length,search:document.querySelectorAll('.sh-quick-search:not([hidden])').length,faqs:document.querySelectorAll('.se-faq').length}));assert.equal(row.settings,1,name);assert.equal(row.search,1,name);assert.equal(row.faqs,registry[name]?.length||0,name);assert(row.overflow<=1,name+' body overflow '+row.overflow);results.push({name,...row,status:'PASS'});}assert.deepEqual(env.errors,[]);assert(!env.calls.some(x=>x.method!=='GET'));}finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source,root,viewport:'360x900',theme:'system-dark',results},null,2));console.log(JSON.stringify(results));}
