const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const raw=fs.readFileSync('assets/js/material-store.js','utf8');
const tick=()=>new Promise(r=>setImmediate(r));
function runtime({authenticated=false,url='https://akademsalon.ru/shop.html',handler}={}){
 const nodes=new Map(),calls=[],session=new Map(),redirects=[];
 function el(id){if(!nodes.has(id))nodes.set(id,{id,textContent:'',innerHTML:'',hidden:false,disabled:false,value:'',checked:false,open:false,listeners:{},append(){},reset(){this.wasReset=true},reportValidity(){return true},click(){return this.listeners.click?.()},focus(){},scrollIntoView(){},addEventListener(k,f){this.listeners[k]=f},showModal(){this.open=true},close(){this.open=false;this.listeners.close?.()}});return nodes.get(id)}
 let loc=new URL(url);const products=['social-pedagogy','housing-first'].map((sku,i)=>({sku,title:sku,price:i?790:1490,page_label:'PDF',requirements_label:'РПД',available:5,contents:[],previews:[]}));
 const ctx={URL,URLSearchParams,crypto:crypto.webcrypto,console,location:{get href(){return loc.href},get search(){return loc.search},get hash(){return loc.hash},get pathname(){return loc.pathname},assign(u){redirects.push(u)}},history:{replaceState(a,b,u){loc=new URL(u,loc)}},sessionStorage:{getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)},document:{hidden:false,cookie:'',getElementById:el,querySelectorAll:()=>[],addEventListener(){}},setInterval:()=>1,clearInterval(){},requestAnimationFrame:f=>f()};ctx.window={setTimeout(){}};
 ctx.fetch=async(path,options)=>{const body=options?.body?JSON.parse(options.body):undefined;calls.push({path,body});let value;if(handler)value=await handler(path,body);
 if(value===undefined)value=path.endsWith('catalogue')?{products,checkout_enabled:true,terms:'v'}:path.endsWith('session')?{authenticated}:path.endsWith('account')?{balance:0,achievements:[],purchases:[]}:path.endsWith('quote')?{price:790,cash:790,discount:0,bonus:0}:{};
 return {ok:true,json:async()=>value};};vm.runInNewContext(raw.replace('  void init();','  window.qa={init,choose,afterLogin,refreshQuote,state:()=>({selected,quote,busy})};'),ctx);
 return {ctx,el,calls,session,redirects,products,qa:ctx.window.qa};
}
test('anonymous explicit SKU shows price and no quote/reservation',async()=>{const r=runtime({url:'https://akademsalon.ru/shop.html?buy=housing-first'});await r.qa.init();assert.equal(r.el('checkout-title').textContent,'housing-first');assert.match(r.el('selection-price').textContent,/790/);assert(r.el('checkout-form').hidden);assert(!r.calls.some(x=>x.path.endsWith('quote')||x.path.endsWith('checkout')));});
test('auth resumes selection with unchecked terms and server quote',async()=>{const r=runtime();await r.qa.init();await r.qa.choose('housing-first');await r.qa.afterLogin(true);assert.equal(r.qa.state().selected.sku,'housing-first');assert.equal(r.qa.state().quote.cash,790);assert(!r.el('accept-terms').checked);assert(!r.el('pay-button').disabled);});
test('cancel clears saved choice and invalidates late quote',async()=>{let release;const r=runtime({authenticated:true,handler:p=>p.endsWith('quote')?new Promise(x=>release=x):undefined});await r.qa.init();const wait=r.qa.choose('housing-first');await tick();r.el('checkout-dialog').close();release({cash:790});await wait;assert.equal(r.qa.state().quote,null);assert(!r.session.has('salon_material_intent_v1'));assert(r.el('pay-button').disabled);});
test('initial auth response cannot overwrite a newer user choice',async()=>{let release;const r=runtime({url:'https://akademsalon.ru/shop.html?buy=social-pedagogy',handler:p=>p.endsWith('session')?new Promise(x=>release=x):undefined});const wait=r.qa.init();await tick();await r.qa.choose('housing-first');release({authenticated:false});await wait;assert.equal(r.qa.state().selected.sku,'housing-first');});
test('late checkout A cannot redirect after selecting B',async()=>{let release;const r=runtime({authenticated:true,handler:p=>p.endsWith('checkout')?new Promise(x=>release=x):undefined});await r.qa.init();await r.qa.choose('social-pedagogy');r.el('accept-terms').checked=true;const wait=r.el('checkout-form').listeners.submit({preventDefault(){}});await tick();r.el('checkout-dialog').close();await r.qa.choose('housing-first');release({purchase:{payment_url:'https://example.invalid/invoice-A'}});await wait;assert.equal(r.qa.state().selected.sku,'housing-first');assert.deepEqual(r.redirects,[]);assert(r.el('checkout-dialog').open);});
test('unknown SKU and expired saved intent do not open checkout',async()=>{const r=runtime({url:'https://akademsalon.ru/shop.html?buy=unknown'});await r.qa.init();assert(!r.el('checkout-dialog').open);assert.equal(r.qa.state().selected,null);});
test('payment return never revives old choice',async()=>{const r=runtime({url:'https://akademsalon.ru/shop.html?Shp_store=1&buy=social-pedagogy'});r.session.set('salon_material_intent_v1',JSON.stringify({sku:'housing-first',until:Date.now()+9999}));await r.qa.init();assert(!r.el('checkout-dialog').open);assert.equal(r.qa.state().selected,null);});
test('coupon typing invalidates quote before Enter',async()=>{const r=runtime({authenticated:true});await r.qa.init();await r.qa.choose('housing-first');r.el('coupon').listeners.input();r.el('accept-terms').checked=true;await r.el('checkout-form').listeners.submit({preventDefault(){}});assert(!r.calls.some(x=>x.path.endsWith('checkout')));});

test('Enter in code verifies and explicit email button can resend after expiry',async()=>{const r=runtime();await r.qa.init();r.el('code-row').hidden=true;await r.el('email-form').listeners.submit({preventDefault(){}});r.el('code').value='123456';r.el('code').listeners.keydown({key:'Enter',preventDefault(){}});await tick();assert.equal(r.calls.filter(x=>x.path.endsWith('email/verify')).length,1);await r.el('email-form').listeners.submit({preventDefault(){}});assert.equal(r.calls.filter(x=>x.path.endsWith('email/start')).length,2);});
test('request confirmation requires server id and preserves retry key on failure',async()=>{let good=false;const r=runtime({authenticated:true,handler:p=>p.endsWith('/requests')?good?{id:12}:{ok:true}:undefined});await r.qa.init();r.el('demand-subject').value='Synthetic';r.el('demand-task').value='Synthetic exercise';r.el('demand-deadline').value='2026-09-12';r.el('demand-budget').value='0';await r.el('demand-form').listeners.submit({preventDefault(){}});assert(!r.el('demand-form').wasReset);assert(!r.el('demand-task').disabled);good=true;await r.el('demand-form').listeners.submit({preventDefault(){}});const calls=r.calls.filter(x=>x.path.endsWith('/requests'));assert.equal(calls[0].body.request_key,calls[1].body.request_key);assert(r.el('demand-form').wasReset);assert.match(r.el('demand-status').textContent,/12/);});
