const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const raw=fs.readFileSync('assets/js/material-store.js','utf8');
const tick=()=>new Promise(r=>setImmediate(r));
function runtime({authenticated=false,url='https://akademsalon.ru/shop.html',handler}={}){
 const nodes=new Map(),calls=[],session=new Map(),redirects=[],savedStorage=new Map();
 function el(id){if(!nodes.has(id))nodes.set(id,{id,dataset:{},setAttribute(k,v){this[k]=v},textContent:'',innerHTML:'',hidden:false,disabled:false,value:'',checked:false,open:false,listeners:{},append(){},reset(){this.wasReset=true},reportValidity(){return true},click(){return this.listeners.click?.()},focus(){},scrollIntoView(){},addEventListener(k,f){this.listeners[k]=f},showModal(){this.open=true},close(){this.open=false;this.listeners.close?.()}});return nodes.get(id)}
 let loc=new URL(url);const products=['social-pedagogy','housing-first'].map((sku,i)=>({sku,title:sku,price:i?790:1490,programme:'39.03.02',semester:3,licences:5,reserved:0,description:'Fixture',page_label:'PDF',requirements_label:'РПД',available:5,contents:[],previews:[]}));
 const ctx={URL,URLSearchParams,crypto:crypto.webcrypto,console,location:{get href(){return loc.href},get search(){return loc.search},get hash(){return loc.hash},get pathname(){return loc.pathname},assign(u){redirects.push(u)}},history:{replaceState(a,b,u){loc=new URL(u,loc)}},sessionStorage:{getItem:k=>session.get(k)||null,setItem:(k,v)=>session.set(k,v),removeItem:k=>session.delete(k)},localStorage:{getItem:k=>savedStorage.get(k)||null,setItem:(k,v)=>savedStorage.set(k,v)},document:{hidden:false,cookie:'',getElementById:el,querySelectorAll:()=>[],addEventListener(){}},setInterval:()=>1,clearInterval(){},requestAnimationFrame:f=>f()};ctx.window={setTimeout(){}};
 ctx.fetch=async(path,options)=>{const body=options?.body?JSON.parse(options.body):undefined;calls.push({path,body});let value;if(handler)value=await handler(path,body);
 if(value===undefined)value=path.endsWith('catalogue')?{products,checkout_enabled:true,terms:'v'}:path.endsWith('session')?{authenticated}:path.endsWith('account')?{balance:0,achievements:[],purchases:[]}:path.endsWith('quote')?{price:790,cash:790,discount:0,bonus:0}:{};
 return {ok:true,json:async()=>value};};vm.runInNewContext(raw.replace('  void init();','  window.qa={init,choose,afterLogin,refreshQuote,preview,moveReader,toggleSaved,matchesProduct,loadCatalog,state:()=>({selected,quote,busy,readerState,displaySku,cardFilter,searchQuery,saved})};'),ctx);
 return {ctx,el,calls,session,savedStorage,redirects,products,qa:ctx.window.qa};
}
test('anonymous explicit SKU shows price and no quote/reservation',async()=>{const r=runtime({url:'https://akademsalon.ru/shop.html?buy=housing-first'});await r.qa.init();assert.equal(r.el('checkout-title').textContent,'housing-first');assert.match(r.el('selection-price').textContent,/790/);assert(r.el('checkout-form').hidden);assert(!r.calls.some(x=>x.path.endsWith('quote')||x.path.endsWith('checkout')));});
test('auth resumes selection with unchecked terms and server quote',async()=>{const r=runtime();await r.qa.init();await r.qa.choose('housing-first');await r.qa.afterLogin(true);assert.equal(r.qa.state().selected.sku,'housing-first');assert.equal(r.qa.state().quote.cash,790);assert(!r.el('accept-terms').checked);assert(!r.el('pay-button').disabled);});
test('cancel clears saved choice and invalidates late quote',async()=>{let release;const r=runtime({authenticated:true,handler:p=>p.endsWith('quote')?new Promise(x=>release=x):undefined});await r.qa.init();const wait=r.qa.choose('housing-first');await tick();r.el('checkout-dialog').close();release({cash:790});await wait;assert.equal(r.qa.state().quote,null);assert(!r.session.has('salon_material_intent_v1'));assert(r.el('pay-button').disabled);});
test('initial auth response cannot overwrite a newer user choice',async()=>{let release;const r=runtime({url:'https://akademsalon.ru/shop.html?buy=social-pedagogy',handler:p=>p.endsWith('session')?new Promise(x=>release=x):undefined});const wait=r.qa.init();await tick();await r.qa.choose('housing-first');release({authenticated:false});await wait;assert.equal(r.qa.state().selected.sku,'housing-first');});
test('late checkout A cannot redirect after selecting B',async()=>{let release;const r=runtime({authenticated:true,handler:p=>p.endsWith('checkout')?new Promise(x=>release=x):undefined});await r.qa.init();await r.qa.choose('social-pedagogy');r.el('accept-terms').checked=true;const wait=r.el('checkout-form').listeners.submit({preventDefault(){}});await tick();r.el('checkout-dialog').close();await r.qa.choose('housing-first');release({purchase:{payment_url:'https://example.invalid/invoice-A'}});await wait;assert.equal(r.qa.state().selected.sku,'housing-first');assert.deepEqual(r.redirects,[]);assert(r.el('checkout-dialog').open);});
test('unknown SKU and expired saved intent do not open checkout',async()=>{const r=runtime({url:'https://akademsalon.ru/shop.html?buy=unknown'});await r.qa.init();assert(!r.el('checkout-dialog').open);assert.equal(r.qa.state().selected,null);});
test('payment return never revives old choice',async()=>{const r=runtime({url:'https://akademsalon.ru/shop.html?Shp_store=1&buy=social-pedagogy'});r.session.set('salon_material_intent_v1',JSON.stringify({sku:'housing-first',until:Date.now()+9999}));await r.qa.init();assert(!r.el('checkout-dialog').open);assert.equal(r.qa.state().selected,null);});
test('coupon typing invalidates quote before Enter',async()=>{const r=runtime({authenticated:true});await r.qa.init();await r.qa.choose('housing-first');r.el('coupon').listeners.input();r.el('accept-terms').checked=true;await r.el('checkout-form').listeners.submit({preventDefault(){}});assert(!r.calls.some(x=>x.path.endsWith('checkout')));});

test('Enter in code verifies and explicit email button can resend after expiry',async()=>{const r=runtime();await r.qa.init();r.el('code-row').hidden=true;await r.el('email-form').listeners.submit({preventDefault(){}});r.el('code').value='123456';r.el('code').listeners.keydown({key:'Enter',preventDefault(){}});await tick();assert.equal(r.calls.filter(x=>x.path.endsWith('email/verify')).length,1);await r.el('email-form').listeners.submit({preventDefault(){}});assert.equal(r.calls.filter(x=>x.path.endsWith('email/start')).length,2);});
test('request confirmation requires server id and preserves retry key on failure',async()=>{let good=false;const r=runtime({authenticated:true,handler:p=>p.endsWith('/requests')?good?{id:12}:{ok:true}:undefined});await r.qa.init();r.el('demand-subject').value='Synthetic';r.el('demand-task').value='Synthetic exercise';r.el('demand-deadline').value='2026-09-12';r.el('demand-budget').value='0';await r.el('demand-form').listeners.submit({preventDefault(){}});assert(!r.el('demand-form').wasReset);assert(!r.el('demand-task').disabled);good=true;await r.el('demand-form').listeners.submit({preventDefault(){}});const calls=r.calls.filter(x=>x.path.endsWith('/requests'));assert.equal(calls[0].body.request_key,calls[1].body.request_key);assert(r.el('demand-form').wasReset);assert.match(r.el('demand-status').textContent,/12/);});

test('reader clamps fragments and ignores private or external preview paths',async()=>{const r=runtime();r.products[0].previews=[{path:'/assets/store/social/preview-01.png',label:'Страница 2'},{path:'/private/paid.pdf',label:'private'},{path:'https://example.invalid/page.png',label:'external'},{path:'/assets/store/social/preview-02.png',label:'Страница 4'}];await r.qa.init();r.qa.preview('social-pedagogy');assert.equal(r.el('reader-count').textContent,'1 / 2');assert.match(r.el('reader-page').innerHTML,/Страница 2/);r.qa.moveReader(9);assert.equal(r.el('reader-count').textContent,'2 / 2');assert.match(r.el('reader-page').innerHTML,/Страница 4/);assert(r.el('reader-next').disabled);r.qa.moveReader(-9);assert(r.el('reader-prev').disabled);assert(!r.el('reader-page').innerHTML.includes('/private/'));});
test('reader purchase preserves the displayed SKU without creating an invoice',async()=>{const r=runtime();await r.qa.init();r.qa.preview('housing-first');await r.el('preview-content').listeners.click({target:{closest:()=>({dataset:{reader:'buy'}})}});assert.equal(r.qa.state().selected.sku,'housing-first');assert(r.el('checkout-dialog').open);assert(!r.el('preview-dialog').open);assert(!r.el('accept-terms').checked);assert(!r.calls.some(x=>x.path.endsWith('checkout')));});
test('seasonal code requests server quote and invalidates old amount while waiting',async()=>{let release;const r=runtime({authenticated:true,handler:(p,b)=>p.endsWith('quote')&&b.coupon==='СЕМЕСТР'?new Promise(x=>release=x):undefined});await r.qa.init();await r.qa.choose('housing-first');r.el('seasonal-coupon').listeners.click();await tick();assert(r.el('pay-button').disabled);assert.equal(r.qa.state().quote,null);assert.equal(r.el('coupon').value,'СЕМЕСТР');release({price:790,cash:750.5,discount:39.5,bonus:0});await tick();assert.equal(r.qa.state().quote.cash,750.5);assert(!r.el('accept-terms').checked);assert(!r.calls.some(x=>x.path.endsWith('checkout')));});
test('invoice in flight freezes all price modifiers and unlocks them after failure',async()=>{let release;const r=runtime({authenticated:true,handler:p=>p.endsWith('checkout')?new Promise(x=>release=x):undefined});await r.qa.init();await r.qa.choose('housing-first');r.el('accept-terms').checked=true;const wait=r.el('checkout-form').listeners.submit({preventDefault(){}});await tick();for(const id of ['coupon','use-bonus','apply-coupon','seasonal-coupon'])assert(r.el(id).disabled);const quotes=r.calls.filter(x=>x.path.endsWith('quote')).length;r.el('seasonal-coupon').listeners.click();await tick();assert.equal(r.calls.filter(x=>x.path.endsWith('quote')).length,quotes);release({error:'provider_unavailable'});await wait;for(const id of ['coupon','use-bonus','apply-coupon','seasonal-coupon'])assert(!r.el(id).disabled);assert.deepEqual(r.redirects,[]);});

test('reader availability updates and zoom keyboard keeps native pane scrolling',async()=>{const r=runtime();r.products[0].previews=[{path:'/assets/store/example/page.png',label:'Page'}];await r.qa.init();r.qa.preview('social-pedagogy');r.products[0].available=0;r.qa.moveReader(0);assert(r.el('reader-buy').disabled);assert.equal(r.el('reader-buy').textContent,'Нет лицензий');await r.el('preview-content').listeners.click({target:{closest:()=>({dataset:{reader:'buy'}})}});assert(!r.el('checkout-dialog').open);r.qa.state().readerState.zoom=true;let prevented=false;r.el('preview-dialog').listeners.keydown({target:r.el('reader-page'),key:'ArrowRight',preventDefault(){prevented=true}});assert(!prevented);});


test('featured book is independent from checkout choice and opens its own pages',async()=>{const r=runtime();await r.qa.init();await r.qa.choose('social-pedagogy');await r.el('feature-tabs').listeners.click({target:{closest:()=>({dataset:{feature:'housing-first'}})}});assert.equal(r.qa.state().displaySku,'housing-first');assert.equal(r.qa.state().selected.sku,'social-pedagogy');r.el('checkout-dialog').close();r.el('hero-preview').listeners.click();assert.equal(r.qa.state().readerState.product.sku,'housing-first');assert.equal(r.qa.state().selected,null);assert(!r.calls.some(x=>x.path.endsWith('quote')||x.path.endsWith('checkout')));});
test('saved shelf persists only SKU choices and never starts a purchase',async()=>{const r=runtime();await r.qa.init();r.qa.toggleSaved('housing-first');assert.deepEqual(JSON.parse(r.savedStorage.get('salon_material_saved_v1')),['housing-first']);assert.equal(r.el('saved-count').textContent,'1');await r.el('shop-filters').listeners.click({target:{closest:()=>({dataset:{filter:'saved'}})}});assert.match(r.el('products').innerHTML,/id="housing-first"/);assert(!r.el('products').innerHTML.includes('id="social-pedagogy"'));r.qa.toggleSaved('housing-first');assert.equal(r.el('saved-count').textContent,'0');assert.equal(r.el('empty-title').textContent,'Твоя полка пока пуста');assert(!r.el('catalogue-empty').hidden);assert.equal(r.qa.state().selected,null);assert(!r.calls.some(x=>x.path.endsWith('quote')||x.path.endsWith('checkout')));});
test('topic search and reset do not change an in-progress checkout SKU',async()=>{const r=runtime({authenticated:true});await r.qa.init();await r.qa.choose('social-pedagogy');r.el('store-search').value='housing-first';r.el('store-search').listeners.input();assert.match(r.el('products').innerHTML,/id="housing-first"/);assert(!r.el('products').innerHTML.includes('id="social-pedagogy"'));assert.equal(r.qa.state().selected.sku,'social-pedagogy');r.el('store-search').value='<img src=x onerror=alert(1)>';r.el('store-search').listeners.input();assert.equal(r.el('products').innerHTML,'');assert(!r.el('catalogue-empty').hidden);r.el('reset-filters').listeners.click();assert.equal(r.el('store-search').value,'');assert(r.el('catalogue-empty').hidden);assert.equal(r.qa.state().selected.sku,'social-pedagogy');});
test('published proof whitelist rejects arbitrary images and opens only known archive records',async()=>{const r=runtime();await r.qa.init();r.el('store-reviews').listeners.click({target:{closest:()=>({dataset:{proof:'../../private'}})}});assert(!r.el('proof-dialog').open);r.el('store-reviews').listeners.click({target:{closest:()=>({dataset:{proof:'43'},focus(){}})}});assert.equal(r.el('proof-image').src,'/assets/img/reviews/review-43.webp');assert(r.el('proof-dialog').open);r.el('proof-close').listeners.click();assert(!r.el('proof-dialog').open);assert(!r.calls.some(x=>x.path.endsWith('checkout')));});
test('zero verified sales render no sales claim, later real catalogue sales do',async()=>{const r=runtime();r.products[0].sold=0;await r.qa.init();assert(!r.el('products').innerHTML.includes('Продано лицензий:'));r.products[0].sold=2;r.products[0].available=0;await r.qa.loadCatalog();assert.match(r.el('products').innerHTML,/Продано лицензий: 2/);r.qa.preview('social-pedagogy');assert(r.el('reader-buy').disabled);assert.equal(r.el('hero-preview').disabled,false);});

test('empty fresh catalogue removes stale featured title price and selectors',async()=>{const r=runtime();await r.qa.init();assert(r.el('feature-price').textContent);r.products.length=0;await r.qa.loadCatalog();assert(r.el('hero-preview').disabled);assert.equal(r.el('feature-price').textContent,'');assert.equal(r.el('feature-tabs').innerHTML,'');assert.match(r.el('feature-cover').innerHTML,/Готовим/);});

const assistantEntry=fs.readFileSync('assets/store/assistant-entry.js','utf8');
function assistantRuntime({handler,api,secretStore}={}) {
 const calls=[],assets=[],events=[],session=new Map();
 const consent={version:'store-consent'},privacy={version:'store-privacy'};
 const document={dispatchEvent:e=>events.push(e),readyState:'complete',cookie:'__Host-salon_csrf=csrf-fixture',head:{append:n=>assets.push(n)},querySelector:s=>assets.find(n=>s.startsWith(n.tag)),createElement:tag=>({tag,dataset:{}})};
 const ctx={CustomEvent:class {constructor(type,options){this.type=type;this.detail=options.detail}},window:{Salon:{consent,analyticsPrivacy:privacy,...(api?{api}:{}),...(secretStore?{secretStore}:{})}},document,sessionStorage:{getItem:k=>session.get(k)||null,removeItem:k=>session.delete(k)},fetch:async(path,options)=>{calls.push({path,options});return handler?handler(path,options):{ok:true,status:200,json:async()=>({ok:true,answer:'fixture'})}}};
 vm.createContext(ctx);vm.runInContext(assistantEntry,ctx);
 return {ctx,consent,privacy,assets,events,session,calls,api:ctx.window.Salon.api};
}
test('Listik entry preserves privacy and existing API and mounts assets once without network POST',()=>{const api={post(){},guestTokens(){return []}},r=assistantRuntime({api});vm.runInContext(assistantEntry,r.ctx);assert.equal(r.ctx.window.Salon.consent,r.consent);assert.equal(r.ctx.window.Salon.analyticsPrivacy,r.privacy);assert.equal(r.api,api);assert.equal(r.assets.length,2);assert(r.assets.every(n=>/salon-assistant\.(css|js)/.test(n.href||n.src)));assert.equal(r.calls.length,0);for(const file of ['shop.html','shop-terms.html']){const s=fs.readFileSync(file,'utf8');assert(!/src="\/assets\/js\/app\.js/.test(s));assert(s.includes('/assets/store/assistant-entry.js'));}});
test('Listik cookie POST uses CSRF and validated guest tokens, rejects external paths and header overrides',async()=>{const r=assistantRuntime();r.session.set('salon_tokens',JSON.stringify(['valid_guest_token123','bad\nheader']));assert.deepEqual(Array.from(r.api.guestTokens()),['valid_guest_token123']);await r.api.post('/assistant/answer',{question:'fixture'},{'X-Order-Tokens':'valid_guest_token123',Authorization:'bad'});const c=r.calls[0];assert.equal(c.path,'/api/assistant/answer');assert.equal(c.options.credentials,'include');assert.equal(c.options.headers['X-CSRF-Token'],'csrf-fixture');assert.equal(c.options.headers.Authorization,undefined);assert.equal(c.options.headers['X-Order-Tokens'],'valid_guest_token123');const rejected=await r.api.post('//external.invalid',{});assert.equal(rejected.error,'unsupported_path');assert.equal(r.calls.length,1);});
test('Listik failures never repeat POST or claim success',async()=>{for(const mode of ['network','json','401']){const r=assistantRuntime({handler:async()=>{if(mode==='network')throw Error('offline');return {ok:mode!=='401',status:mode==='401'?401:200,json:async()=>{if(mode==='json')throw Error('bad');return {ok:true}}}}});const result=await r.api.post('/lead',{message:'fixture'});assert.equal(result.ok,false);assert.equal(r.calls.length,1);}});
test('Listik stale 401 cannot clear a newer legacy session, current 401 clears old hints',async()=>{let release;const r=assistantRuntime({handler:()=>new Promise(resolve=>release=resolve)});r.session.set('salon_session',JSON.stringify('old_session_token123'));const waiting=r.api.post('/orders/17/message',{text:'fixture'});r.session.set('salon_session',JSON.stringify('new_session_token456'));release({status:401,ok:false,json:async()=>({error:'unauthorized'})});await waiting;assert.equal(JSON.parse(r.session.get('salon_session')),'new_session_token456');assert.equal(r.events.length,0);const current=r.api.post('/orders/17/message',{text:'fixture'});release({status:401,ok:false,json:async()=>({error:'unauthorized'})});await current;assert(!r.session.has('salon_session'));assert.equal(r.events.length,1);assert.equal(r.events[0].type,'salon:auth-lost');assert.equal(r.calls.length,2);});
