const fs=require('fs'),vm=require('vm'),crypto=require('crypto');const repo=process.argv[2]||require('path').resolve(__dirname,'..'),src=fs.readFileSync(repo+'/assets/js/admin.js','utf8');const results=[];const check=(name,p)=>results.push({name,pass:!!p});const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve()};
function extract(name){const line=src.split('\n').find(x=>x.startsWith('  function '+name+'('));if(line&&line.trim().endsWith('}'))return line;const m=src.match(new RegExp('^  function '+name+'\\([^]*?^  }','m'));if(!m)throw Error(name);return m[0];}
function setup(){const requests=[],toasts=[],rendered=[];let confirmResolve;const confirmCalls=[],stored={};const b={disabled:false,isConnected:true};const els={agBDelta:{value:'500'},agBNote:{value:'test reason',focus(){}}};const st={identityEpoch:0,tabRequestEpoch:0,cardRequestSeq:0,clientRequestSeq:0,deskLoading:false,deskFailed:false,desk:null,tab:'summary',ovBusy:false,ov:null,ovAt:0,busy:false,csel:101,ccard:{name:'Synthetic A'},controlFilter:'all',controlLimit:8};const S={api:{token:()=>true,get:path=>new Promise(resolve=>requests.push({path,resolve})),post:(path,body)=>new Promise(resolve=>requests.push({path,body,resolve}))}};const ctx={st,S,Date,Promise,console,uncertainBonuses:{},bonusReadEvidence:null,sessionStorage:{getItem:k=>stored[k],setItem:(k,v)=>stored[k]=v},document:{getElementById:id=>els[id],body:{classList:{remove(){}}}},toast:x=>toasts.push(x),drawBody:()=>rendered.push('body'),drawNav(){},drawLive(){},drawClientCard(){rendered.push('clientcard')},loadSubs(){},loadGifts(){},loadQA(){},loadCard(){},listQuery:()=>'',refreshT:null,confirmDlg:opts=>{confirmCalls.push(opts);return new Promise(r=>confirmResolve=r)},loadClient:id=>rendered.push('client'+id),errSay:e=>e,ico:()=>'',dmLabel:x=>x};for(const n of ['adminRead','saveUncertainBonus','uncertainBonusNotice','loadDesk','doRefresh','api','dlLeft','silentDays','deskRows','controlQueueRows','controlQueue','esc','money'])vm.runInNewContext(extract(n),ctx);const start=src.indexOf("    var reviewed=t.closest('[data-bonus-reviewed]');"),end=src.indexOf("    if (t.closest('#agBan')) {",start);vm.runInNewContext('function bonus(t){'+src.slice(start,end)+'}',ctx);const identityBody=src.match(/document.addEventListener\('salon:identity-changing',function\(\)\{([^]*?)\}\);/)[1];vm.runInNewContext('function changeIdentity(){'+identityBody+'}',ctx);return{ctx,st,S,requests,toasts,rendered,b,els,stored,confirmCalls,reviewed:()=>ctx.bonus({closest:s=>s==='[data-bonus-reviewed]'?{dataset:{bonusReviewed:'101'},isConnected:true}:null}),reconcile:()=>ctx.bonus({closest:s=>s==='[data-bonus-reconcile]'?{dataset:{bonusReconcile:'101'},isConnected:true}:null}),confirm:r=>confirmResolve(r),bonus:()=>ctx.bonus({closest:s=>s==='#agBApply'?b:null})};}
(async()=>{
let t=setup();t.ctx.loadDesk();t.ctx.loadDesk();check('Desk request is coalesced',t.requests.length===1);t.requests[0].resolve({ok:false,error:'network'});await flush();check('Failed initial desk is not empty queue',t.st.desk===null&&t.st.deskFailed&&t.ctx.controlQueue().includes('Очередь не загрузилась'));
t=setup();t.ctx.loadDesk();t.ctx.changeIdentity();t.requests[0].resolve({ok:true,orders:[{id:101}]});await flush();check('Late desk result from old identity discarded',t.st.desk===null);
t=setup();t.ctx.loadDesk();t.ctx.changeIdentity();t.ctx.loadDesk();check('New identity can start its own desk read before old request settles',t.requests.length===2);t.requests[0].resolve({ok:true,orders:[{id:101}]});await flush();check('Old desk completion does not leave new UI waiting without a draw/reload',t.requests.length>1||t.rendered.length>0);
t=setup();const operation=t.ctx.api('/admin/test',{});t.ctx.changeIdentity();t.requests[0].resolve({ok:true,private:'old'});const r=await operation;check('Old mutation result is not delivered as success',r.ok===false);check('Identity change does not retain old busy lock',!t.st.busy);
t=setup();const failed=t.ctx.api('/admin/clients/101/bonus',{delta:500,note:'test'});t.requests[0].resolve({ok:false,error:'network'});const fr=await failed;check('Resolved network failure is classified as uncertain',fr.error==='network_uncertain');
t=setup();t.ctx.doRefresh();t.ctx.changeIdentity();t.st.ov=null;t.requests[0].resolve({ok:true,month:{revenue:12345}});await flush();check('Background overview cannot repopulate old identity private state',t.st.ov===null);
t=setup();t.bonus();t.st.csel=202;t.confirm({ok:true});await flush();check('Bonus confirm after client switch does not mutate',t.requests.length===0);
t=setup();t.bonus();t.ctx.changeIdentity();t.confirm({ok:true});await flush();check('Bonus confirm after identity switch does not mutate',t.requests.length===0);
t=setup();t.bonus();t.els.agBDelta.value='900';t.confirm({ok:true});await flush();check('Bonus uses amount and client actually confirmed',t.requests[0]?.body.delta===500&&t.requests[0]?.path==='/admin/clients/101/bonus');t.requests[0].resolve({ok:false,error:'network'});await flush();t.bonus();await flush();check('Uncertain manual bonus cannot be immediately repeated',t.requests.length===1);
t=setup();t.bonus();t.confirm({ok:true});await flush();check('Pending bonus is protected across reload before network acknowledgement',!!JSON.parse(t.stored.salon_admin_uncertain_bonus||'{}')['101']);
t=setup();t.ctx.saveUncertainBonus(101,500);check('Uncertain marker survives session serialization',JSON.parse(t.stored.salon_admin_uncertain_bonus)['101'].delta===500);t.reconcile();t.requests[0].resolve({ok:false,error:'network'});await flush();check('Failed journal read keeps uncertain lock',!!t.ctx.uncertainBonuses[101]);
t=setup();t.ctx.saveUncertainBonus(101,500);t.reconcile();t.requests[0].resolve({ok:true,client:{id:101}});await flush();check('Journal refresh is GET only and does not execute bonus',t.requests.every(r=>!r.body));check('Journal can be inspected before acknowledgement dialog',t.confirmCalls.length===0);if(t.confirmCalls.length){t.confirm({ok:false});await flush();check('Cancel reconciliation retains uncertain lock',!!t.ctx.uncertainBonuses[101]);}
t=setup();t.ctx.saveUncertainBonus(101,500);t.reconcile();t.ctx.changeIdentity();t.requests[0].resolve({ok:true,client:{id:101}});await flush();check('Old identity journal result cannot clear lock',!!t.ctx.uncertainBonuses[101]&&t.confirmCalls.length===0);
for(const err of ['network','bad_json']){t=setup();t.bonus();t.confirm({ok:true});await flush();t.requests[0].resolve({ok:false,error:err});await flush();check('Uncertain '+err+' retains persisted bonus lock',!!JSON.parse(t.stored.salon_admin_uncertain_bonus||'{}')['101']);}
for(const err of ['bonus_empty','bad_amount','bad_request','forbidden']){t=setup();t.bonus();t.confirm({ok:true});await flush();t.requests[0].resolve({ok:false,error:err});await flush();check('Definite validation '+err+' clears pending marker',!t.ctx.uncertainBonuses[101]);}
t=setup();t.bonus();t.confirm({ok:true});await flush();t.requests[0].resolve({ok:true,balance:500});await flush();check('Confirmed success clears pending marker',!t.ctx.uncertainBonuses[101]);
t=setup();t.bonus();t.confirm({ok:true});await flush();t.ctx.changeIdentity();t.requests[0].resolve({ok:true,balance:500});await flush();check('Identity change during bonus retains recovery marker and suppresses success',!!t.ctx.uncertainBonuses[101]&&!t.toasts.some(x=>x.startsWith('Проведено')));
t=setup();t.ctx.saveUncertainBonus(101,500);t.reviewed();check('Acknowledgement without fresh journal cannot open confirm',t.confirmCalls.length===0);
t=setup();t.ctx.saveUncertainBonus(101,500);t.reconcile();t.requests[0].resolve({ok:true,client:{id:101}});await flush();t.reviewed();check('Fresh journal requires explicit second click before confirmation',t.confirmCalls.length===1);t.confirm({ok:false});await flush();check('Cancel explicit review preserves lock',!!t.ctx.uncertainBonuses[101]);t.reviewed();t.confirm({ok:true});await flush();check('Confirmed review clears lock with no automatic POST',!t.ctx.uncertainBonuses[101]&&t.requests.length===1&&!t.requests[0].body);
t=setup();t.ctx.saveUncertainBonus(101,500);t.reconcile();t.requests[0].resolve({ok:true,client:{id:101}});await flush();t.reviewed();t.ctx.changeIdentity();t.confirm({ok:true});await flush();check('Late review confirmation after identity change cannot clear marker',!!t.ctx.uncertainBonuses[101]);
t=setup();t.st.desk=[{id:1,status:'new'},{id:2,status:'fix'},{id:3,status:'work',claimed:true},{id:4,status:'new',paused:true}];t.st.controlFilter='payment';check('Payment filter shows claimed only and no paused',t.ctx.controlQueueRows().map(x=>x.o.id).join(',')==='3');t.st.controlFilter='fix';check('Fix filter keeps existing quick action and target',t.ctx.controlQueueRows()[0].quick==='fixack'&&t.ctx.controlQueueRows()[0].focus==='feed');t.st.controlFilter='new';check('New filter preserves quote target',t.ctx.controlQueueRows()[0].focus==='plan');
const clip=src.split('\n').find(x=>x.includes("Promise.resolve().then(function(){return navigator.clipboard.writeText(r.url);})"));const notices=[];const cc={r:{url:'https://example.test/synthetic'},navigator:{clipboard:{writeText:()=>Promise.reject(Error('denied'))}},toast:x=>notices.push(x)};vm.runInNewContext(clip,cc);await flush();check('Rejected create-link clipboard does not claim copied',notices.length===1&&notices[0].includes('вручную')&&!notices[0].includes('скопирована'));
const report={mode:'Actual extracted functions/bonus branch in Node VM; only synthetic data, API/confirmation mocked',hashes:{'assets/js/admin.js':crypto.createHash('sha256').update(src).digest('hex')},passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results,reproducer:__filename};console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
