const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const repo=require('path').resolve(__dirname,'..');
const source=fs.readFileSync(repo+'/assets/js/salon-workspace.js','utf8'),domain=fs.readFileSync(repo+'/assets/js/salon-order-domain.js','utf8');
const results=[];const check=(name,ok,details)=>results.push({name,pass:!!ok,...(details?{details}:{})});const flush=async()=>{for(let i=0;i<24;i++)await Promise.resolve()};
function form(kind,data={},type){return{dataset:{form:kind,...(type?{type}:{})},data,isConnected:true,closest(){return this},querySelector(){return {isConnected:true,dataset:{}}}}}
function container(){return{forms:[],_html:'',set innerHTML(s){this.forms.forEach(f=>f.isConnected=false);this._html=s;this.forms=[...s.matchAll(/<form\b([^>]*)>/g)].map(m=>{const a=Object.fromEntries([...m[1].matchAll(/data-([\w-]+)="([^"]*)"/g)].map(x=>[x[1],x[2]]));return form(a.form,{},a.type)});},get innerHTML(){return this._html},querySelectorAll(s){return s==='[data-form]'?this.forms:[]},querySelector(){return null},replaceChildren(){this.innerHTML=''}}}
function setup(){const events={},we={},calls=[],nav=[],root=container(),dialog=Object.assign(container(),{open:false,showModal(){this.open=true},close(){this.open=false}}),elements={'workspace-root':root,'ws-dialog':dialog,'ws-notice':{},'ws-tg-state':container(),'ws-email':{focus(){}},'ws-email-state':container()};
 const doc={getElementById:id=>elements[id],querySelector:s=>s==='dialog[open]'&&dialog.open?dialog:s==='[name=code]'?{focus(){}}:null,querySelectorAll:()=>[],activeElement:{tagName:'BODY'},body:{classList:{contains:()=>false,toggle(){}}},documentElement:{dataset:{}},addEventListener:(n,f)=>(events[n]??=[]).push(f),dispatchEvent:e=>(events[e.type]||[]).forEach(f=>f(e))};
 const A={guestTokens:()=>[],token:()=>null,identified:()=>false,get:async()=>({ok:true,orders:[]}),post:async(path,body)=>{calls.push({path,body});return{ok:true}},headers:()=>({})};
 const win={Salon:{api:A,secretStore:{del(){}}},scrollTo(){},addEventListener:(n,f)=>(we[n]??=[]).push(f)};const ctx={window:win,document:doc,location:{hash:'#order-101-work',href:'https://example.test/dashboard.html',origin:'https://example.test',pathname:'/dashboard.html',assign:u=>nav.push(u)},URL,URLSearchParams,Intl,Map,Date,Event:class{constructor(type){this.type=type}},FormData:class{constructor(f){this.data=f?.data||{}}get(k){return this.data[k]??null}append(k,v){this.data[k]=v}},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},innerHeight:800,TextEncoder};
 vm.runInNewContext(domain,ctx);vm.runInNewContext(fs.readFileSync(repo+'/assets/js/salon-payment-domain.js','utf8'),ctx);
 const code=source.slice(0,source.indexOf('(async()=>{try{await A.ready;'))+`window.review={state,payment,editing,run,dialog,login,bindForm,request,checkout,setRender(f){render=f},setRefresh(f){refresh=f}};})();`;
 vm.runInNewContext(code,ctx);const R=win.review;R.setRender(async()=>{});R.setRefresh(async()=>{});
 const click=(action,extra={})=>{const c={dataset:{action,...extra},isConnected:true,closest(sel){return sel==='[data-action]'?this:null}};(events.click||[]).forEach(f=>f({target:c}));};
 const submit=f=>events.submit[0]({target:f,preventDefault(){}});
 return{R,A,events,we,calls,nav,ctx,root,dialog,elements,click,submit};}
(async()=>{
 let t=setup();t.R.state.detail={id:101,handoff_artifact_id:11};t.click('accept-work');await flush();const old=t.dialog.forms[0];check('Dialog binds order and artifact',old?.dataset.orderId===101&&old?._orderSnapshot?.handoff_artifact_id===11);
 t.ctx.location.hash='#order-202-work';t.we.hashchange[0]();await flush();t.R.state.detail={id:202,handoff_artifact_id:22};t.submit(old);await flush();check('Back/hash navigation closes dialog and stale submit cannot mutate B',!t.dialog.open&&t.calls.length===0);
 t=setup();t.R.state.detail={id:101,handoff_artifact_id:11};t.click('accept-work');await flush();const same=t.dialog.forms[0];t.R.state.detail={id:101,handoff_artifact_id:22};t.submit(same);await flush();check('Same-order newer version cannot silently replace reviewed artifact',t.calls[0]?.path==='/orders/101/action'&&t.calls[0]?.body.artifact_id===11);
 t=setup();t.R.dialog('Private review','private draft');t.events['salon:auth-lost'][0]();check('Auth loss closes dialog and clears bound context',!t.dialog.open&&t.R.state.dialogContext===null);
 t=setup();t.R.dialog('Private review','private draft');t.events['salon:identity-changing'][0]();check('Identity change closes dialog',!t.dialog.open);
 t=setup();const newEpoch=form('message',{text:'old'});t.R.state.detail={id:101};t.R.bindForm(newEpoch);t.R.state.epoch++;t.submit(newEpoch);await flush();check('Old identity form sends no request',t.calls.length===0);
 t=setup();let o={id:101,price:45000,status:'work',actions:[]};let h=t.R.payment(o);check('Unknown due does not imply no payment required',h.includes('Проверяем график оплаты')&&!h.includes('Сейчас платить не нужно')&&!h.includes('data-form="pay"'));
 o={...o,pay_online:true,due_now:{amount:5000},payments:[{status:'claimed'}],specification_meta:{id:1}};h=t.R.payment(o);check('Claimed payment-array state suppresses online form',h.includes('Проверяем платёж')&&!h.includes('data-form="pay"'));
 o={...o,pay_online:false,requisites:'synthetic',actions:['paid']};h=t.R.payment(o);check('Claimed payment also suppresses manual-transfer instructions and gift controls',!h.includes('Переведи ' )&&!h.includes('data-form="gift"'));
 o={id:101,price:45000,status:'work',pay_online:true,due_now:{amount:5000},specification_meta:{id:1},actions:[]};h=t.R.payment(o);check('Unknown claimed status suppresses payment until reconciled',!h.includes('data-form="pay"'));
 t=setup();let resolve;t.A.post=(path,body)=>{t.calls.push({path,body});return new Promise(r=>resolve=r)};t.ctx.location.hash='#order-101-chat';t.R.state.detail={id:101};t.R.state.drafts.set(101,'sent version');let f=form('message',{text:'sent version'});t.R.bindForm(f);t.submit(f);await flush();t.R.state.drafts.set(101,'next unsent version');resolve({ok:true});await flush();check('Late message success preserves newer unsent draft',t.R.state.drafts.get(101)==='next unsent version');
 t=setup();t.R.state.detail={id:101};t.R.state.drafts.set(101,'sent');f=form('message',{text:'sent'});t.R.bindForm(f);t.submit(f);await flush();check('Unchanged acknowledged draft clears',!t.R.state.drafts.has(101));
 t=setup();t.R.state.drafts.set(101,'abandoned');t.ctx.location.hash='#orders';check('Off-route draft does not suppress polling',!t.R.editing());
 t=setup();let refreshed=0;t.R.setRefresh(async()=>refreshed++);t.R.run({isConnected:true},()=>new Promise(()=>{}));await flush();t.click('refresh');await flush();check('Manual refresh remains available during pending mutation',refreshed===1);
 t=setup();t.R.state.features={email_login:true};t.R.login();const email=t.root.forms.find(f=>f.dataset.form==='email');email.data={email:'synthetic@example.test'};t.submit(email);await flush();check('Actual login email form is bound and request starts',t.calls.some(c=>c.path==='/auth/email/start'));
 t=setup();t.R.state.features={email_login:true};t.R.login();const claim=t.root.forms.find(f=>f.dataset.form==='claim');check('Actual login claim form is epoch-bound',Number(claim.dataset.epoch)===t.R.state.epoch);
 t=setup();t.A.post=(path,body)=>{t.calls.push({path,body});return new Promise(r=>resolve=r)};const done=t.R.checkout('/orders/101/pay',{},101);await flush();t.ctx.location.hash='#order-202-money';resolve({ok:true,online:true,url:'https://auth.robokassa.ru/example'});await done;check('Late order payment URL does not redirect after leaving that order',t.nav.length===0);
 const out={source:'candidate',mode:'VM actual handlers; API, post-render and refresh mocked; synthetic data only',hashes:Object.fromEntries([['assets/js/salon-workspace.js',source],['assets/js/salon-order-domain.js',domain]].map(([k,v])=>[k,crypto.createHash('sha256').update(v).digest('hex')])),passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results,reproducer:__filename};if(process.env.SALON_WORKSPACE_EVIDENCE)fs.writeFileSync(process.env.SALON_WORKSPACE_EVIDENCE,JSON.stringify(out,null,2)+'\n');console.log('Workspace contract: '+out.passed+' passed, '+out.failed+' failed');require('assert/strict').equal(out.failed,0,JSON.stringify(results.filter(x=>!x.pass)));
})().catch(e=>{console.error(e);process.exitCode=1});
