const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {policy,preview}=require('../assets/js/salon-referral-policy.js');
test('six qualified orders cover 6000, never a larger custom package',()=>{assert.equal(preview(6).due,0);assert.equal(preview(6,9000).due,3000);assert.equal(preview(60,9000).applied,6000);assert.equal(policy.minOrder,5000)});
test('used credit and residual do not become another cash discount',()=>{assert.equal(preview(8).left,2000);assert.equal(preview(6,6000,2000).due,2000);assert.equal(preview(-2).applied,0);assert.equal(preview(1).acquisitionCeiling,.2)});
const sandbox={window:{},document:{},console,URL};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('assets/js/salon-cabinet.js','utf8'),sandbox);const render=sandbox.window.SalonCabinetUI.referrals;
test('guest, disabled and error never show a fabricated balance or personal link',()=>{for(const s of [null,{enabled:false},{loadError:true}]){const html=render(s,true);assert.doesNotMatch(html,/desk-circle-link/);assert.doesNotMatch(html,/data-circle-reserve/)}assert.match(render(null,false),/Войди/)});
test('server balance controls reservation and hostile labels are escaped',()=>{const html=render({enabled:true,available:10000,eligible_orders:[{id:9,label:'<img onerror=x>'}],claims:[],ref_link_tg:'https://evil.example/?start=ref_2'},true);assert.match(html,/data-circle-amount="6000"/);assert.match(html,/&lt;img/);assert.doesNotMatch(html,/<img|desk-circle-link/)});
test('already reserved orders are excluded and only own pending claim has release action',()=>{const html=render({enabled:true,available:2000,eligible_orders:[{id:9,label:'№9'}],claims:[{id:'claim-1',order_id:9,state:'reserved',amount:1000}]},true);assert.doesNotMatch(html,/data-circle-reserve=/);assert.match(html,/data-circle-release="claim-1"/);assert.match(html,/сам по себе не меняет счёт/)});
test('new page and rules disclose draft status and preserve old obligations',()=>{for(const file of ['referral.html','referral-rules.html']){const h=fs.readFileSync(file,'utf8');assert.match(h,/ещё не запущен/);assert.match(h,/200/);assert.match(h,/5 000/);assert.doesNotMatch(h,/остаток сгорает/)} });

test('disabled programme preserves a validated legacy personal link',()=>{const html=render({enabled:false},true,{ref_link_tg:'https://t.me/academic_saloon_bot?start=ref_42'});assert.match(html,/200 бонусов/);assert.match(html,/data-circle-copy/);assert.doesNotMatch(html,/data-circle-reserve/)});
