// Fresh private contexts, production GET/HEAD only; never submits an order.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire((process.env.SALON_NODE_DEPS||'/Users/saymurrbk.ru/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules')+'/package.json');
const{chromium}=require('playwright');const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
try{for(const width of [319,1440])for(const theme of ['light','dark']){
const ctx=await browser.newContext({viewport:{width,height:900},colorScheme:theme,serviceWorkers:'block',reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[],mutations=[];p.on('pageerror',e=>errors.push(String(e)));
await ctx.addInitScript(theme=>{localStorage.setItem('salon_theme',theme);localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1','{"v":1}');sessionStorage.setItem('salon_analytics_qa_session_v1','1')},theme);
await ctx.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.hostname!=='akademsalon.ru')return route.abort();if(!['GET','HEAD'].includes(req.method())){mutations.push({path:url.pathname,method:req.method()});return route.abort()}return route.continue()});
await p.goto('https://akademsalon.ru/services.html',{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready);await p.locator('[data-product="course"]').click();await p.locator('#cat-deadline-calendar').click();
assert(await p.locator('#salon-calendar').evaluate(e=>e.open));const initial=await p.locator('#salon-calendar').boundingBox();await p.locator('.sc-period').click();const monthly=await p.locator('#salon-calendar').boundingBox();assert(Math.abs(initial.y-monthly.y)<=1,'calendar stays in place');await p.locator('.sc-period').click();
const target=await p.evaluate(()=>{const d=new Date();d.setDate(d.getDate()+1);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')});await p.locator('[data-date="'+target+'"]').click();assert.equal(await p.locator('#cat-deadline').inputValue(),target);const total=await p.locator('#cat-total').textContent();await p.locator('#cat-deadline-calendar').click();assert.equal(await p.locator('[data-date][aria-selected="true"]').getAttribute('data-date'),target);await p.screenshot({path:path.join(out,'live-calendar-'+width+'-'+theme+'.png')});await p.keyboard.press('Escape');
assert(await p.locator('#cat-deadline-calendar').evaluate(e=>e===document.activeElement));if(width<1050)assert(await p.locator('#catalog-sheet').evaluate(e=>e.open));await p.locator('#cat-checkout').click();await p.waitForURL('**/configurator.html?composition=1');assert.equal(await p.locator('#deadline').inputValue(),target);assert.equal(await p.locator('#summary-price').textContent(),total);await p.locator('#deadline-calendar').click();assert.equal(await p.locator('[data-date][aria-selected="true"]').getAttribute('data-date'),target);await p.screenshot({path:path.join(out,'live-request-calendar-'+width+'-'+theme+'.png')});await p.keyboard.press('Escape');assert(await p.locator('#deadline-calendar').evaluate(e=>e===document.activeElement));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
const assets=await p.locator('script[src*="salon-calendar"],link[href*="salon-calendar"]').evaluateAll(a=>a.map(e=>e.src||e.href));assert.equal(assets.length,2);assert.deepEqual(errors,[]);assert.deepEqual(mutations,[]);results.push({width,theme,status:'PASS',target,total,assets,errors,mutations});await ctx.close();
}}catch(e){console.error(e);results.push({status:'FAIL',error:String(e)});process.exitCode=1}finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({at:new Date().toISOString(),route:'https://akademsalon.ru/services.html',browser:'Chrome',network:'live read-only; all non-GET/HEAD blocked',results},null,2))}
