(function(){
'use strict';
const E=window.SalonEstimate;if(!E)return;
const key='salon_estimate_benefits_v1';
let state={plan:'none',newPlan:true,period:'sem',points:0,gift:0,deposit:0};
try{const x=JSON.parse(sessionStorage.getItem(key)||'null');if(x){state={plan:Object.hasOwn(E.plans,x.plan)?x.plan:'none',newPlan:x.newPlan!==false,period:x.period==='month'?'month':'sem',points:Math.max(0,Math.min(500000,Math.floor(Number(x.points)||0))),gift:Math.max(0,Math.min(50000,Math.floor(Number(x.gift)||0))),deposit:[20000,30000,45000,60000].includes(x.deposit)?x.deposit:0}}}catch(_){}
const money=E.money,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function html(prefix){return '<div class="est-benefit-fields"><label for="'+prefix+'-plan">Подписка<select id="'+prefix+'-plan" data-est-option="plan"><option value="none">Без подписки</option><option value="plus">Салон+ · 5%, до 1 000 ₽</option><option value="pro">Про · 10%, до 3 000 ₽</option><option value="session">Сессия · 7%, до 2 000 ₽</option></select></label><label for="'+prefix+'-status" data-est-plan-field>Статус<select id="'+prefix+'-status" data-est-option="newPlan"><option value="true">Планирую подключить</option><option value="false">Уже есть подписка</option></select></label><label for="'+prefix+'-period" data-est-plan-field>Срок подписки<select id="'+prefix+'-period" data-est-option="period"><option value="sem">150 дней</option><option value="month">30 дней</option></select></label><label for="'+prefix+'-points">Доступные баллы<input id="'+prefix+'-points" data-est-option="points" type="number" min="0" max="500000" step="1" inputmode="numeric" value="0"></label></div><details class="est-extra-benefits"><summary>Сертификат и депозит <span aria-hidden="true">＋</span></summary><div class="est-benefit-fields"><label for="'+prefix+'-gift">Остаток сертификата, ₽<input id="'+prefix+'-gift" data-est-option="gift" type="number" min="0" max="50000" step="1" inputmode="numeric" value="0"></label><label for="'+prefix+'-deposit">Планирую внести на депозит<select id="'+prefix+'-deposit" data-est-option="deposit"><option value="0">Без пополнения</option><option value="20000">20 000 ₽ · до 8%</option><option value="30000">30 000 ₽ · до 10%</option><option value="45000">45 000 ₽ · до 12%</option><option value="60000">60 000 ₽ · до 15%</option></select></label></div><p>Сертификат — способ оплаты. Депозит — твои деньги на будущие услуги; ставка зависит от фактически использованной суммы.</p></details><p class="est-fine">Это пример расчёта: укажи свои баллы и привилегии. <a href="dashboard.html#loyalty">Личный баланс ↗</a>. Скидка подписки и промокод не суммируются; действует большая скидка. Промокод проверяется отдельно перед оплатой.</p><button type="button" class="est-reset" data-est-reset>Сбросить пример выгод</button>';}
function sync(){document.querySelectorAll('[data-est-option]').forEach(input=>{if(document.activeElement!==input)input.value=String(state[input.dataset.estOption]);input.setAttribute('aria-invalid',String(!input.validity.valid));const error=document.getElementById(input.id+'-error');if(error){error.hidden=input.validity.valid;error.textContent='Введите целое число от '+input.min+' до '+input.max+'. В расчёте пока '+Number(state[input.dataset.estOption]).toLocaleString('ru-RU')+'.'}});document.querySelectorAll('[data-est-plan-field]').forEach(el=>el.hidden=state.plan==='none');document.querySelectorAll('[data-est-option="period"]').forEach(el=>{el.disabled=state.plan==='session';if(state.plan==='session'){if(!el.querySelector('option[value=session60]'))el.add(new Option('60 дней','session60'));el.value='session60'}else{el.querySelector('option[value=session60]')?.remove();el.value=state.period}el.closest('label').querySelectorAll('.est-session-period').forEach(n=>n.remove());if(state.plan==='session'){const n=document.createElement('small');n.className='est-session-period';n.textContent='Сессия всегда на 60 дней';el.closest('label').append(n)}})}
function notify(){sync();try{sessionStorage.setItem(key,JSON.stringify(state))}catch(_){}document.dispatchEvent(new Event('salon:benefits-estimate'))}
function mount(host,prefix){host.innerHTML=html(prefix);host.querySelectorAll('input[type=number]').forEach(input=>{const hint=document.createElement('small');hint.id=input.id+'-error';hint.className='est-input-error';hint.hidden=true;hint.setAttribute('role','status');input.setAttribute('aria-describedby',hint.id);input.after(hint)});host.addEventListener('input',e=>{const input=e.target.closest('[data-est-option]');if(!input)return;const k=input.dataset.estOption;if(!input.validity.valid){sync();return}state[k]=k==='newPlan'?input.value==='true':['points','gift','deposit'].includes(k)?Number(input.value):input.value;notify()});host.querySelector('[data-est-reset]').onclick=()=>{state={plan:'none',newPlan:true,period:'sem',points:0,gift:0,deposit:0};notify()};sync()}
function summary(price,high){const b=E.benefit(price,state),hi=E.benefit(high,state);if(state.plan==='none'&&!state.points&&!state.gift&&!state.deposit)return '<p class="est-next-bonus">После полной оплаты вернётся от <b>'+b.cashback.toLocaleString('ru-RU')+' б.</b> на следующие заказы.</p><p class="est-fine">Есть баллы или подписка? Укажи их в настройках примера, чтобы увидеть свою выгоду.</p>';const rows=[['Подписка'+(state.plan!=='none'?' «'+E.plans[state.plan].name+'»':''),b.discount?'−'+money(b.discount):'Без скидки'],['Списание баллов',b.spent?'−'+money(b.spent):'0 ₽']];if(b.giftUsed)rows.push(['Из сертификата',money(b.giftUsed)]);if(b.fee)rows.push(['Подключение · '+(state.plan==='session'?'60':state.period==='month'?'30':'150')+' дней','+'+money(b.fee)]);
let out='<div class="est-benefit-receipt">'+rows.map(r=>'<div><span>'+r[0]+'</span><b>'+r[1]+'</b></div>').join('')+'<div class="est-payable"><span>С выбранными условиями<small>Предварительно, включая подключение</small></span><strong>'+E.range(b.totalNow,hi.totalNow)+'</strong></div><p class="est-next-bonus">Вернётся от <b>'+b.cashback.toLocaleString('ru-RU')+' б.</b> после полной оплаты · на следующие заказы</p>';
if(b.netSaving>0)out+='<p class="est-net">Выгода от '+money(b.netSaving)+' уже учтена. Будущий кешбэк показан отдельно.</p>';else if(b.fee)out+='<p class="est-fine">Для одного заказа подключение дороже скидки на '+money(-b.netSaving)+'. Посмотри расчёт нескольких работ ниже.</p>';
if(state.deposit){out+='<div class="est-deposit-note"><b>Если пополнить депозит сейчас</b><p>Внести '+money(state.deposit)+'. '+(b.fromDeposit?'На эту работу из него уйдёт от '+money(b.fromDeposit)+'; останется до '+money(b.depositLeft)+' твоих денег.':'Для этого ориентира пополнения недостаточно: этап оплачивается целиком. Можно выбрать другой способ.')+'</p><p>Первоначальные расходы: '+E.range(b.upfront,hi.upfront)+(b.fee?' с подпиской.':'.')+' Деньги на депозите не являются скидкой.</p><p>В примере по нижней границе из резерва: '+b.reserve.toLocaleString('ru-RU')+' б. после приёмки и 14 дней; кешбэк уже вычтен. Резерв не доступен сейчас.</p></div>'}
return out+'<p class="est-fine">Баллами — до 20% заказа. Скидка и списание вместе — до 25%. Доступность выгод и итоговую сумму подтвердим до оплаты.</p></div>'}
function comparison(price,count=1){const c=E.compare(price,count,state.period);return '<div class="est-compare-cards">'+c.items.map(p=>'<article class="'+(c.best.id===p.id?'est-recommended':'')+'"><span>'+esc(p.name)+(c.best.id===p.id?' · меньше расходов':'')+'</span><strong>'+money(p.total)+'</strong><small>'+count+' '+(count===1?'заказ':count<5?'заказа':'заказов')+' + '+money(p.fee)+' за подключение</small><b>'+((p.net>0?'Выгода '+money(p.net):p.net<0?'Дороже на '+money(-p.net):'Без доплат'))+'</b><p>'+ (p.id==='none'?'Кешбэк 5% на следующую работу.':p.days+' дней. '+(p.breakEven?'Подключение окупается скидками с '+p.breakEven+' заказа такой цены.':''))+'</p></article>').join('')+'</div><p class="est-fine">Сравнение по нижней границе ориентира для работ одной цены. Стоимость подключения включена, будущие баллы и промокоды не вычтены. Сессия — '+count+' заказа за 60 дней; её не сравниваем с семестром как один срок.</p>'}
window.SalonEstimateUI={mount,summary,comparison,state:()=>({...state}),save:notify};document.querySelectorAll('[data-est-benefit-controls]').forEach((el,i)=>mount(el,'est-page-'+i));
})();
