(function(){
'use strict';
const root=document.querySelector('[data-catalogue]'),P=window.SalonProducts,M=window.SalonCommerce,C=window.SalonCalc,E=window.SalonEstimate,U=window.SalonEstimateUI;
if(!root||!P||!M||!C)return;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),money=P.money,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='salon_direct_selection_v1',scopeNames={whole:'Целиком',part:'Только часть',editing:'Доработка'},speedNames={standard:'Планово',express24:'24 часа · ×2',expressfast:'Быстрее суток'};
let filter='all',speed='standard',state=null,trigger=null;const drafts=new Map();
function readContext(){try{const raw=JSON.parse(sessionStorage.getItem(key)||'{}');return {discipline:C.disciplines.some(d=>d.id===raw.discipline)?raw.discipline:'hum',deadline:/^\d{4}-\d{2}-\d{2}$/.test(raw.deadline||'')?raw.deadline:''}}catch(e){return {discipline:'hum',deadline:''}}}
let context=readContext();
function contextLabel(){return [context.discipline!=='hum'?C.disciplines.find(d=>d.id===context.discipline).label:'',context.deadline?new Date(context.deadline+'T00:00:00').toLocaleDateString('ru-RU'):''].filter(Boolean).join(' · ')}
function term(s){if(s.speed!=='standard')return 'free';const days=Math.ceil((new Date(context.deadline+'T00:00:00')-new Date(new Date().setHours(0,0,0,0)))/86400000);return Number.isFinite(days)?days<14?'urgent':days<30?'mid':'free':'free'}
function estimate(s){return E.estimate(s,context,E.read(s))}
function fresh(p,selectedSpeed=speed){return M.normalize({product:p.id,scope:p.id==='chapter'?'part':p.id==='editing'?'editing':'whole',speed:selectedSpeed,package:'standard',addons:[]})}
function persist(){context=readContext();state=M.save({...state,addons:estimate(state).addons});try{sessionStorage.setItem(key,JSON.stringify({product:state.product,scope:state.scope,...context}))}catch(e){}}
function saveContext(){try{const previous=JSON.parse(sessionStorage.getItem(key)||'{}');const product=P.products.some(p=>p.id===previous.product)?previous.product:'course';sessionStorage.setItem(key,JSON.stringify({product,scope:['whole','part','editing'].includes(previous.scope)?previous.scope:'whole',...context}))}catch(e){}}
function time(s){const p=P.get(s.product);if(p.id==='custom'&&s.speed==='standard')return 'по объёму задачи';return s.speed==='express24'?'до 24 часов':s.speed==='expressfast'?'срок по задаче':s.scope==='editing'||s.scope==='part'&&p.id!=='chapter'?'срок по объёму':p.days}
const aliases={essay:'эссе сочинение',referat:'реферат доклад',self:'контрольная самостоятельная домашнее задание задачи решения',course:'курсовая курсовой проект',practice:'практика отчет дневник',chapter:'глава теория практическая часть кандидатской',diplom:'диплом вкр выпускная бакалавр',master:'магистерская магистр диссертация',rinc:'научная статья ринц публикация',kandidat:'кандидатская диссертация',editing:'правки доработка исправления замечания редактирование',custom:'другое введение заключение расчет презентация речь часть задачи'};
const fold=s=>s.toLocaleLowerCase('ru').replace(/ё/g,'е').trim();
// Static anchors remain usable without JS; enhanced controls open a dialog.
// A button also keeps the shared navigation guard from treating this as checkout.
const cards=$$('.cat-card').map(link=>{const card=document.createElement('button');card.type='button';card.className=link.className;card.dataset.product=link.dataset.product;card.dataset.category=link.dataset.category;card.innerHTML=link.innerHTML;card.setAttribute('aria-haspopup','dialog');link.replaceWith(card);return card});
function renderCards(){const query=fold($('#cat-search').value).split(/\s+/).filter(Boolean);let count=0;
 cards.forEach(card=>{const p=P.get(card.dataset.product),s=fresh(p),q=estimate(s),text=fold(p.name+' '+p.detail+' '+aliases[p.id]);card.hidden=!(filter==='all'||filter===p.group)||!query.every(word=>text.includes(word));if(!card.hidden)count++;
 card.querySelector('[data-card-price]').textContent=E.range(q.total,q.high);
 let perk=card.querySelector('.est-card-perk');if(!perk){perk=document.createElement('div');perk.className='est-card-perk';card.querySelector('.cat-card-bottom').after(perk)}const b=E.benefit(q.total,U.state());perk.textContent=b.netSaving>0?'С выбранными выгодами от '+money(b.totalNow):'Вернётся от '+b.cashback.toLocaleString('ru-RU')+' б. на следующий заказ';
 card.querySelector('[data-card-time]').textContent=p.id==='kandidat'&&speed!=='standard'?'от 3 месяцев · без экспресса':time(s);
 });
 $('#cat-count').textContent='Найдено: '+count;$('#cat-empty').hidden=count>0;
 $$('[data-cat-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.catFilter===filter)));
 $$('[data-catalog-speed]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.catalogSpeed===speed)));
 $('#cat-speed-description').textContent=speed==='express24'?'×2 к цене работы. Дополнения не дорожают. Отсчёт после согласования, материалов и оплаты.':speed==='expressfast'?'Меньше суток: бюджет ×2–3 от плановой цены. Сначала подтвердим возможность выполнить задачу.':'Цены и сроки для планового заказа. Оформление по методичке включено.';
 renderHero();const label=contextLabel();$('#cat-context').hidden=!label;$('#cat-context').textContent='В ценах учтено: '+label+'. Изменить можно в «Уточнить ориентир».';
}
const details={
 essay:['Аргументация и выводы по теме','Источники и ссылки в тексте'],referat:['План и обзор литературы','Основной текст и список источников'],self:['Ответы или решения по заданию','Пояснения к выполнению'],course:['План, введение и главы','Выводы и список источников'],practice:['Отчёт по материалам твоей практики','Дневник и приложения: состав по заданию'],chapter:['Теоретическая или практическая глава','Выводы, ссылки и источники'],diplom:['План, введение и главы ВКР','Заключение и список источников'],master:['Методология и главы исследования','Анализ результатов и выводы'],rinc:['Текст статьи, аннотация и источники','По требованиям издания; публикация отдельно'],kandidat:['Замысел, методология и главы','Согласованный план работы по этапам'],editing:['Исправления по твоим замечаниям','Логика, источники или оформление по заданию'],custom:['Только согласованные задачи','Результат и объём закрепим в смете']};
const dialog=document.createElement('dialog');dialog.className='catalog-sheet';dialog.id='catalog-sheet';dialog.setAttribute('aria-labelledby','cat-sheet-title');
dialog.innerHTML='<div class="cat-sheet-head"><span>СОБЕРИ СВОЙ ЗАКАЗ</span><button type="button" class="cat-close" aria-label="Закрыть состав заказа">×</button></div><div class="cat-sheet-layout"><div class="cat-sheet-content"><h2 id="cat-sheet-title"></h2><span class="cat-label">Какой объём нужен?</span><div class="cat-scope" role="group" aria-label="Объём выбранной работы">'+Object.entries(scopeNames).map(([id,name])=>'<button type="button" data-sheet-scope="'+id+'">'+name+'</button>').join('')+'</div><ul class="cat-included" id="cat-included"></ul><div class="cat-part-tip" id="cat-part-tip" hidden></div><span class="cat-label">Когда нужно?</span><div class="cat-sheet-speeds" role="group" aria-label="Срок выбранной работы">'+Object.entries(speedNames).map(([id,name])=>'<button type="button" data-sheet-speed="'+id+'">'+name+'</button>').join('')+'</div><p class="cat-sheet-time" id="cat-sheet-time"></p><details class="cat-additions"><summary><span>Дополнения и VIP<small id="cat-addon-caption">Презентация, речь, нормоконтроль</small></span><span aria-hidden="true">＋</span></summary>'+M.addons.map(a=>'<label class="cat-addon"><input type="checkbox" data-cat-addon="'+a.id+'"><span><strong>'+a.label+'</strong><small>'+a.detail+'</small><b data-cat-addon-price="'+a.id+'">от '+money(a.price)+'</b></span></label>').join('')+'<p class="cat-saving" id="cat-saving" hidden></p><label class="cat-addon cat-vip"><input type="checkbox" id="cat-vip"><span><strong>VIP · от начала до защиты</strong><small>План, этапы, обратная связь, нормоконтроль, презентация, речь и индивидуальный разбор. Состав, число итераций и срок сопровождения фиксируем до оплаты.</small><b>Всё сопровождение в одной смете</b></span></label></details><p class="cat-sheet-context" id="cat-sheet-context" hidden></p></div><aside class="cat-receipt" aria-label="Состав и стоимость заказа"><div class="cat-receipt-inner"><span class="cat-receipt-label">ТВОЯ СПЕЦИФИКАЦИЯ</span><h3 id="cat-receipt-name"></h3><p class="cat-receipt-subtitle" id="cat-receipt-subtitle"></p><div class="cat-receipt-lines" id="cat-receipt-lines"></div><div aria-live="polite" aria-atomic="true"><span class="cat-total-label" id="cat-total-label">Ориентир за заказ</span><strong id="cat-total"></strong></div><a class="cat-checkout" id="cat-checkout" href="configurator.html?composition=1">К заявке <span aria-hidden="true">→</span></a><p class="cat-checkout-note">Без регистрации и оплаты.<br>Точную смету согласуем по заданию.</p></div></aside></div>';
document.body.append(dialog);
const mobileTotal=document.createElement('button');mobileTotal.type='button';mobileTotal.className='est-mobile-total';mobileTotal.setAttribute('aria-label','Перейти к расчёту');$('.cat-sheet-head').prepend(mobileTotal);mobileTotal.onclick=()=>$('.cat-receipt').scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});

const estimateFields=document.createElement('div');estimateFields.className='est-scope-fields';estimateFields.innerHTML='<label for="est-unit">Уточни задачу<select id="est-unit"></select></label><label for="est-quantity" id="est-quantity-label">Количество одинаковых задач<input id="est-quantity" type="number" min="1" max="10" step="1" value="1" inputmode="numeric"></label><p id="est-unit-note" class="est-fine"></p>';
$('.cat-scope').after(estimateFields);
const assumptions=document.createElement('p');assumptions.id='est-assumption';assumptions.className='est-assumption';$('#cat-sheet-context').after(assumptions);
const benefits=document.createElement('section');benefits.className='est-sheet-benefits';benefits.innerHTML='<details><summary>Бонусы к этому заказу <span aria-hidden="true">＋</span></summary><div id="est-sheet-benefit-controls"></div></details><div id="est-benefit-result" aria-live="polite" aria-atomic="true"></div>';$('#cat-total').parentElement.after(benefits);U.mount($('#est-sheet-benefit-controls'),'est-sheet');
const compare=document.createElement('details');compare.className='est-compare';compare.innerHTML='<summary>Окупится ли подписка? <span aria-hidden="true">＋</span></summary><label for="est-order-count">Сколько таких работ планируешь?<select id="est-order-count"><option value="1">1 работа</option><option value="2">2 работы</option><option value="3">3 работы</option><option value="5">5 работ</option><option value="10">10 работ</option></select></label><div id="est-plan-comparison"></div><a href="plus.html">Возможности подписок ↗</a>';$('#est-assumption').after(compare);$('#est-order-count').onchange=renderSheet;
const copy=document.createElement('button');copy.type='button';copy.id='est-copy';copy.className='est-copy';copy.textContent='Скопировать расчёт';const status=document.createElement('p');status.id='est-saved-status';status.setAttribute('role','status');status.className='est-fine';const fallback=document.createElement('textarea');fallback.hidden=true;fallback.id='est-copy-fallback';fallback.readOnly=true;fallback.setAttribute('aria-label','Текст расчёта для копирования');$('.cat-checkout-note').after(copy,status,fallback);
copy.onclick=async()=>{const q=estimate(state),b=E.benefit(q.total,U.state());const text=[P.get(state.product).name+' · '+scopeNames[state.scope]+' · '+speedNames[state.speed],q.unit+(q.quantity>1?' × '+q.quantity:''),...q.lines.map(l=>l.label+': '+money(l.price)),'Ориентир: '+E.range(q.total,q.high),'Пример с выбранными выгодами: от '+money(b.totalNow)+(b.fee?' (подключение включено)':''),'Баллы к списанию в примере: '+b.spent+'. Кешбэк на следующие заказы: от '+b.cashback+' б.',q.note,'https://akademsalon.ru/services.html'].join('\n');try{await navigator.clipboard.writeText(text);fallback.hidden=true;status.textContent='Расчёт скопирован'}catch(_){fallback.hidden=false;fallback.value=text;fallback.focus();fallback.select();status.textContent='Выдели и скопируй текст расчёта'}};
function renderEstimateInputs(){const mode=E.kind(state),o=E.read(state);estimateFields.hidden=mode==='whole';if(mode==='whole')return;const opts=mode==='piece'?E.pieces.map(p=>({id:p.id,label:p.name})):E.editTypes.map(id=>({id,label:C.types.find(t=>t.id===id).label}));const signature=mode+opts.map(o=>o.id).join('|');if($('#est-unit').dataset.mode!==signature){$('#est-unit').innerHTML=opts.map(o=>'<option value="'+o.id+'">'+esc(o.label)+'</option>').join('');$('#est-unit').dataset.mode=signature}$('#est-unit').value=mode==='piece'?o.piece:o.edit;if(document.activeElement!==$('#est-quantity'))$('#est-quantity').value=o.quantity;$('#est-quantity-label').hidden=mode!=='piece';$('#est-unit-note').textContent=mode==='piece'?E.pieces.find(p=>p.id===o.piece).detail:'Ориентир редакторского этапа из действующего прайса. Небольшая правка может стоить меньше полного этапа после оценки материалов.'}
$('#est-unit').onchange=()=>{const o=E.read(state);o[E.kind(state)==='piece'?'piece':'edit']=$('#est-unit').value;E.save(state,o);renderSheet()};$('#est-quantity').oninput=()=>{if(!$('#est-quantity').validity.valid)return;E.save(state,{...E.read(state),quantity:$('#est-quantity').value});renderSheet()};
document.addEventListener('salon:benefits-estimate',()=>{renderCards();if(dialog.open)renderSheet();renderHero()});
function renderHero(){const s=fresh(P.get('course')),q=estimate(s),b=E.benefit(q.total,U.state());$('#est-hero-price').textContent=E.range(q.total,q.high);$('#est-hero-perk').textContent=b.netSaving>0?'С выбранными выгодами от '+money(b.totalNow):'Вернётся от '+b.cashback.toLocaleString('ru-RU')+' бонусов';$('#est-hero-context').textContent='Курсовая · '+speedNames[s.speed]+(contextLabel()?' · '+contextLabel():'');}
$('#est-open-course').onclick=()=>openCard(cards.find(c=>c.dataset.product==='course'));

function renderSheet(){if(!state)return;state=M.normalize(state);const p=P.get(state.product),q=estimate(state),vip=state.package==='vip',candidate=p.id==='kandidat';
 renderEstimateInputs();
 $('#cat-sheet-title').textContent=p.name;$('#cat-receipt-name').textContent=p.name;
 $$('[data-sheet-scope]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.sheetScope===state.scope));b.disabled=p.id==='chapter'&&b.dataset.sheetScope==='whole'||p.id==='editing'&&b.dataset.sheetScope!=='editing'});
 $$('[data-sheet-speed]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.sheetSpeed===state.speed));b.disabled=candidate&&b.dataset.sheetSpeed!=='standard'});
 const included=state.scope==='part'&&p.id!=='chapter'?['Только нужный фрагмент работы','Состав и объём уточним по заданию']:state.scope==='editing'?['Правки твоего текста по согласованным замечаниям','Состав доработки фиксируем до начала']:details[p.id];
 $('#cat-included').innerHTML=[...included,'Оформление по переданной методичке'].map(t=>'<li>'+esc(t)+'</li>').join('');
 const tip=$('#cat-part-tip');tip.replaceChildren();tip.hidden=!(candidate||state.scope==='part'&&p.id!=='chapter');
 if(candidate){tip.append('Кандидатская готовится по этапам. Для срочной главы есть отдельный формат. ');const b=document.createElement('button');b.type='button';b.textContent='Выбрать отдельную главу →';b.onclick=()=>{state={...state,product:'chapter',scope:'part',speed};renderSheet()};tip.append(b)}
 else if(state.scope==='part'&&p.id!=='chapter')tip.textContent='Оплачивается только нужная часть. В заявке укажи, что подготовить: введение, главу, расчёты или другой фрагмент.';
 $('#cat-sheet-time').textContent=state.speed==='express24'?'До 24 часов · ×2 за работу. Отсчёт после согласования задания, полного комплекта материалов и условий оплаты.':state.speed==='expressfast'?'Бюджет ×2–3 от плановой цены. Нужный час укажи в заявке; возможность подтвердим после материалов.':time(state)+' · точную дату согласуем по заданию.';
 $('#cat-receipt-subtitle').textContent=scopeNames[state.scope]+' · '+speedNames[state.speed];
 $('#cat-receipt-lines').innerHTML='<div><span>'+esc(q.unit)+(q.quantity>1?' × '+q.quantity:'')+'</span><b>от '+money(q.work)+'</b></div>'+q.lines.map(l=>'<div><span>'+esc(l.label)+'</span><b>от '+money(l.price)+'</b></div>').join('');
 $('#cat-total').textContent=E.range(q.total,q.high);mobileTotal.textContent=E.range(q.total,q.high)+' ↓';
 $('#est-assumption').textContent=q.note;$('#est-benefit-result').innerHTML=U.summary(q.total,q.high);$('#est-plan-comparison').innerHTML=U.comparison(q.total,Number($('#est-order-count').value));$('#est-saved-status').textContent='';
 $('#cat-total-label').textContent=vip?'Работа + VIP':q.lines.length?'Работа + дополнения':'Ориентир за работу';
 $('#cat-addon-caption').textContent=vip?'VIP выбран · услуги включены':q.lines.length?'Дополнения · от '+money(q.extras):'Презентация, речь, нормоконтроль';
 $$('[data-cat-addon]').forEach(c=>{c.checked=vip||q.primaryAddon===c.dataset.catAddon||state.addons.includes(c.dataset.catAddon);c.disabled=vip||q.primaryAddon===c.dataset.catAddon;const a=M.addons.find(a=>a.id===c.dataset.catAddon);$('[data-cat-addon-price="'+a.id+'"]').textContent=q.primaryAddon===a.id?'Уже в основной задаче':vip?'Входит в VIP':'от '+money(a.price)+(a.id==='tutor'?' / час':'')});
 $('#cat-vip').checked=vip;$('#cat-saving').hidden=!q.saving;$('#cat-saving').textContent='Комплект к защите: учтена экономия 1 500 ₽ относительно отдельных услуг.';
 $('#cat-sheet-context').hidden=!contextLabel();$('#cat-sheet-context').textContent='В ориентире учтено: '+contextLabel()+'. Направление и дату можно изменить в заявке.';
}
function openCard(card){context=readContext();trigger=card;state=drafts.has(card.dataset.product)?M.normalize(drafts.get(card.dataset.product)):fresh(P.get(card.dataset.product));renderSheet();$('.cat-additions').open=false;dialog.showModal();document.body.classList.add('catalog-open');$('.cat-sheet-layout').scrollTop=0;$('.cat-sheet-content').scrollTop=0;$('.cat-close').focus()}
cards.forEach(card=>card.addEventListener('click',e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0)return;e.preventDefault();e.stopPropagation();openCard(card)}));
$('.cat-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.classList.remove('catalog-open');if(state)drafts.set(state.product,M.normalize(state));trigger?.focus({preventScroll:true})});
dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=Array.from(dialog.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),summary')).filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden');const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});
$$('[data-sheet-scope]').forEach(b=>b.onclick=()=>{state.scope=b.dataset.sheetScope;renderSheet()});
$$('[data-sheet-speed]').forEach(b=>b.onclick=()=>{state.speed=b.dataset.sheetSpeed;renderSheet()});
$$('[data-cat-addon]').forEach(c=>c.onchange=()=>{state.addons=c.checked?[...state.addons,c.dataset.catAddon]:state.addons.filter(id=>id!==c.dataset.catAddon);renderSheet()});
$('#cat-vip').onchange=e=>{state.package=e.target.checked?'vip':'standard';renderSheet()};
$('#cat-checkout').addEventListener('click',()=>{persist();dialog.close()});
$$('[data-cat-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.catFilter;renderCards()});
$$('[data-catalog-speed]').forEach(b=>b.onclick=()=>{speed=b.dataset.catalogSpeed;drafts.forEach((s,id)=>drafts.set(id,M.normalize({...s,speed})));renderCards()});
$('#cat-search').addEventListener('input',renderCards);$('#cat-clear').onclick=()=>{filter='all';$('#cat-search').value='';renderCards();$('#cat-search').focus()};
$('#cat-discipline').innerHTML=C.disciplines.map(d=>'<option value="'+d.id+'">'+esc(d.label)+'</option>').join('');$('#cat-discipline').value=context.discipline;$('#cat-deadline').value=context.deadline;const today=new Date();$('#cat-deadline').min=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
$('#cat-discipline').onchange=e=>{context.discipline=e.target.value;saveContext();renderCards();document.dispatchEvent(new Event('salon:order-updated'))};$('#cat-deadline').onchange=e=>{if(!e.target.validity.valid){e.target.reportValidity();return}context.deadline=e.target.value;saveContext();renderCards();document.dispatchEvent(new Event('salon:order-updated'))};
$('#cat-reset-context').onclick=()=>{context={discipline:'hum',deadline:''};$('#cat-discipline').value='hum';$('#cat-deadline').value='';saveContext();renderCards();document.dispatchEvent(new Event('salon:order-updated'))};
function resume(){const saved=M.read();$('#cat-resume').hidden=!M.saved();$('#cat-resume-open').replaceChildren();const label=document.createElement('span');label.className='cat-resume-label';label.textContent='ТВОЙ ВЫБОР';const title=document.createElement('strong');title.textContent=P.get(saved.product).name;const meta=document.createElement('span');meta.className='cat-resume-meta';meta.textContent=(saved.scope==='part'?'Отдельная часть':saved.scope==='editing'?'Доработка':'Работа с нуля')+' · '+(saved.speed==='express24'?'24 часа · ×2':saved.speed==='expressfast'?'Меньше суток':'Плановый срок');const action=document.createElement('span');action.className='cat-resume-action';action.textContent='Продолжить →';$('#cat-resume-open').append(label,title,meta,action)}
$('#cat-resume-open').onclick=()=>{const saved=M.read(),card=cards.find(c=>c.dataset.product===saved.product);drafts.set(saved.product,saved);openCard(card);trigger=$('#cat-resume-open')};
$('#cat-resume-clear').onclick=()=>{M.clear();drafts.clear();try{sessionStorage.removeItem(E.KEY)}catch(_){}resume();renderCards();$('#cat-search').focus()};
window.addEventListener('pageshow',e=>{context=readContext();$('#cat-discipline').value=context.discipline;$('#cat-deadline').value=context.deadline;if(e.persisted&&M.saved()){const saved=M.read();drafts.set(saved.product,saved)}resume();renderCards()});resume();renderCards();
// View state is separate from the saved order. Only enums, card ID and numbers.
const helpSlot=document.createElement('div');helpSlot.className='est-help-slot';$('.cat-questions').append(helpSlot);function placeHelper(){const launcher=$('.sa-launch');if(!launcher)return false;const focused=document.activeElement===launcher;helpSlot.append(launcher);if(focused)launcher.focus({preventScroll:true});return true}if(!placeHelper()){const observer=new MutationObserver(()=>{if(placeHelper())observer.disconnect()});observer.observe(document.body,{childList:true});window.addEventListener('pagehide',()=>observer.disconnect(),{once:true})}
const returnAPI=window.SalonReturn;let returnRestoring=false,returnTimer,returnIntent=false,returnAllowed=true,returnAnchor=null;
function returnState(){const shown=cards.filter(c=>!c.hidden);const card=dialog.open&&trigger?.matches('.cat-card')?trigger:shown.find(c=>{const r=c.getBoundingClientRect();return Math.min(innerHeight,r.bottom)-Math.max(150,r.top)>=Math.min(120,r.height)});if(!card&&returnAnchor&&shown.some(c=>c.dataset.product===returnAnchor.product))return {...returnAnchor,filter,speed,at:Date.now()};const view={v:1,filter,speed,product:card?.dataset.product||'',top:Math.max(-5000,Math.min(5000,card?.getBoundingClientRect().top||0)),y:Math.min(100000,scrollY),at:Date.now()};if(card)returnAnchor=view;return view}
function returnSave(){if(!returnAPI||returnRestoring||!returnAllowed)return;const view=returnState();try{sessionStorage.setItem(returnAPI.catalogueKey,JSON.stringify(view));const previous=history.state;history.replaceState({...previous,salonCatalogReturn:view},'')}catch(_){}}
function returnRead(){const intent=returnAPI?.catalogueIntent();if(!returnAPI||location.hash)return null;try{const entry=returnAPI.catalogueRead(JSON.stringify(history.state?.salonCatalogReturn));if(entry)return entry;if(!intent)return null;return returnAPI.catalogueRead(sessionStorage.getItem(returnAPI.catalogueKey))}catch(_){return null}}
function returnRestore(view){if(!view)return;returnRestoring=true;filter=view.filter;speed=view.speed;renderCards();Promise.resolve(document.fonts?.ready).then(()=>requestAnimationFrame(()=>{if(!location.hash&&!returnIntent){const card=cards.find(c=>c.dataset.product===view.product&&!c.hidden);window.scrollTo({top:Math.max(0,card?scrollY+card.getBoundingClientRect().top-view.top:view.y),behavior:'instant'})}returnRestoring=false}))}
const initialReturn=returnRead();if(initialReturn){filter=initialReturn.filter;speed=initialReturn.speed;renderCards();returnRestoring=true}
window.addEventListener('pageshow',e=>{if(!e.persisted)returnRestore(initialReturn);else returnRestoring=false});
window.addEventListener('pagehide',()=>{clearTimeout(returnTimer);returnSave()});
window.addEventListener('scroll',()=>{if(returnRestoring||dialog.open)return;clearTimeout(returnTimer);returnTimer=setTimeout(returnSave,180)},{passive:true});
for(const kind of ['wheel','touchmove','keydown'])window.addEventListener(kind,e=>{if(e.isTrusted){returnIntent=true;returnAllowed=true}},{passive:true});
root.addEventListener('click',e=>{if(e.target.closest('[data-cat-filter],[data-catalog-speed],#cat-clear')){returnAllowed=true;queueMicrotask(returnSave)}});
cards.forEach(card=>card.addEventListener('click',()=>{returnAllowed=true;returnSave()}));
window.addEventListener('popstate',()=>{returnIntent=false;returnRestore(returnRead())});
document.addEventListener('salon:return-cleared',()=>{returnAllowed=false;clearTimeout(returnTimer);try{sessionStorage.removeItem(returnAPI.catalogueKey);const next={...history.state};delete next.salonCatalogReturn;history.replaceState(next,'')}catch(_){}});

})();
