const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const baseline=process.env.SALON_BASELINE||'/tmp/salon-reading-20260924/release-final';
const app=fs.readFileSync(path.join(baseline,'assets/js/app.js'),'utf8');const start=app.indexOf('var SalonCalc = {'),end=app.indexOf('window.SalonCalc = SalonCalc;',start);const C=vm.runInNewContext(app.slice(start,end)+'SalonCalc');
const M=require(path.join(baseline,'assets/js/salon-commerce.js')),P=require(path.join(baseline,'assets/js/salon-products.js')),E=require('./estimate.js');const deps={C,M,P};
const q=(s,context={},options={})=>E.estimate(s,context,options,deps);
test('all published bases preserved, all scenarios numeric and monotonic',()=>{let n=0;for(const p of P.products)for(const scope of ['whole','part','editing'])for(const speed of ['standard','express24','expressfast'])for(const d of C.disciplines)for(const deadline of ['', '2026-09-28','2026-10-15','2026-12-01'])for(const pack of ['standard','vip']){const v=q({product:p.id,scope,speed,package:pack,addons:['defense','norm','tutor']},{discipline:d.id,deadline,now:Date.parse('2026-09-27T12:00:00')});assert(Number.isFinite(v.total)&&v.total>0);assert(v.high>=v.total);assert(v.work+v.extras===v.total);n++}assert.equal(n,6048);for(const p of P.products.filter(p=>p.price)){const v=q({product:p.id,scope:p.id==='chapter'?'part':'whole'});assert.equal(v.work,p.price,p.id)}});
test('plan, date and 24h rates match exact existing calculator',()=>{for(const p of P.products.filter(p=>p.price))for(const disc of C.disciplines)for(const deadline of ['','2026-10-03','2026-10-20']){const ctx={discipline:disc.id,deadline,now:Date.parse('2026-09-27T12:00:00')};for(const scope of ['whole','editing']){const v=q({product:p.id,scope},ctx);const expected=C.quote(p.type,disc.id,E.term(ctx,ctx.now),scope==='editing'?'turn':'vip');assert.equal(v.work,expected.low);assert.equal(v.workHigh,expected.high)}if(p.id!=='kandidat'){const v=q({product:p.id,speed:'express24'},ctx);assert.equal(v.work,C.quote(p.type,disc.id,'free','vip').low*2)}}});
test('bounded custom units, edit types and duplicates',()=>{assert.equal(q({product:'custom'}).total,2500);assert.equal(q({product:'editing'}).total,9000);assert.equal(q({product:'editing'},{},{edit:'practice'}).total,8000);assert.equal(q({product:'custom'},{},{piece:'other',quantity:3}).total,7500);const v=q({product:'custom',addons:['defense','norm']},{},{piece:'defense'});assert.equal(v.total,9500);assert.equal(v.lines.length,1);assert.equal(v.saving,1500);assert.equal(q({product:'custom',addons:['defense']},{},{piece:'norm'}).total,9500);assert.equal(q({product:'custom',addons:['norm']},{},{piece:'defense',quantity:2}).total,15500);assert.equal(q({product:'course',addons:['defense','norm']}).total,23500);assert.equal(q({product:'course',package:'vip'}).total,29500);assert.equal(q({product:'course',speed:'expressfast'}).total,28000);assert.equal(q({product:'course',speed:'expressfast'}).high,42000)});
test('benefits respect caps across low and high prices; new plan fees separate',()=>{for(const price of [0,100,999,1000,2500,14000,40000,60000,200000,1500000])for(const plan of Object.keys(E.plans))for(const points of [0,100,1000,1000000])for(const gift of [0,2000,50000]){const b=E.benefit(price,{plan,points,gift,newPlan:true,period:'sem'});assert(b.discount+b.spent<=Math.floor(price*.25));assert(b.spent<=Math.floor(price*.2));assert.equal(b.cash+b.giftUsed+b.discount+b.spent,price);assert(b.cash>=0);assert.equal(b.totalNow,b.cash+b.fee);assert.equal(b.cashback,Math.floor(b.cash*E.plans[plan].cashback/100))}assert.equal(E.benefit(14000,{plan:'plus',newPlan:true}).netSaving,-299);assert.equal(E.benefit(40000,{plan:'pro',newPlan:true}).netSaving,310);assert.equal(E.benefit(40000,{plan:'pro',points:8000}).spent,7000)});
test('deposit cash not savings; reserve subtracts cashback; whole stage only',()=>{const b=E.benefit(20000,{deposit:30000});assert.equal(b.fromDeposit,20000);assert.equal(b.depositLeft,10000);assert.equal(b.reserve,600);assert.equal(b.upfront,30000);assert.equal(b.netSaving,0);assert.equal(E.benefit(20000,{deposit:30000,plan:'pro'}).reserve,0);const high=E.benefit(65000,{deposit:60000});assert.equal(high.fromDeposit,0);assert.equal(high.upfront,125000);assert.equal(high.reserve,0)});
test('subscription comparison includes fees and never recommends loss',()=>{assert.equal(E.compare(14000,1,'sem').best.id,'none');assert.equal(E.compare(14000,3,'sem').best.id,'pro');assert.equal(E.compare(2500,1,'sem').best.id,'none');assert.equal(E.compare(40000,1,'sem').best.id,'pro');for(const x of E.compare(14000,3,'sem').items)assert.equal(x.total,42000-x.discount+x.fee)});

test('same chapter correction tariff from each route and honest addon deadline note',()=>{const n=q({product:'chapter',scope:'editing'}).work;assert.equal(n,9000);assert.equal(q({product:'custom',scope:'editing'},{},{piece:'chapter'}).work,n);assert.equal(q({product:'editing'},{},{edit:'chapter'}).work,n);for(const piece of ['defense','norm','tutor'])for(const deadline of ['2026-09-28','2026-10-15']){const v=q({product:'custom'},{deadline,now:Date.parse('2026-09-27T12:00:00')},{piece});assert(!/×1[,\.](15|45)/.test(v.note));assert.equal(v.work,M.addons.find(a=>a.id===piece).price)}for(const scope of ['diagnostic','support'])for(const product of ['custom','editing'])assert(q({product,scope}).total>0);assert.equal(q({product:'custom',scope:'diagnostic'},{},{piece:'chapter'}).work,3000)});

test('diagnostic copy describes only the diagnostic deliverable',()=>{for(const product of ['course','editing'])assert.match(q({product,scope:'diagnostic'}).description,/Письменный разбор требований/)});
