(function(){
'use strict';
const E=window.SalonEstimate,U=window.SalonEstimateUI,M=window.SalonCommerce,C=window.SalonCalc;
const product=document.getElementById('product'),scope=document.getElementById('scope');if(!E||!U||!product||!scope)return;
const host=document.createElement('section');host.className='est-order-controls';host.innerHTML='<h3>Твой ориентир</h3><div class="est-scope-fields" id="est-order-fields"><label for="est-order-unit">Основа расчёта<select id="est-order-unit"></select></label><label for="est-order-quantity" id="est-order-quantity-label">Количество<input id="est-order-quantity" type="number" min="1" max="10" step="1" value="1" inputmode="numeric"></label></div><p class="est-fine" id="est-order-assumption"></p><details class="est-order-benefits"><summary>Пример с бонусами и подпиской</summary><div id="est-order-benefit-controls"></div><div id="est-order-benefit-result"></div></details>';
const target=document.getElementById('intake-composition-slot')||document.querySelector('.order-composition-controls');if(!target)return;target.append(host);U.mount(document.getElementById('est-order-benefit-controls'),'est-order');
// Hypothetical budget controls are not fields of the order form. Invalid examples must never block an order.
host.querySelectorAll('input,select').forEach(el=>el.setAttribute('form','est-scenario-only'));
let current=null;
function render(){host.hidden=!M.products.includes(product.value)||!['whole','part','editing','diagnostic','support'].includes(scope.value);if(host.hidden)return;current={...M.normalize({...M.read(),product:product.value,scope:scope.value}),scope:scope.value};const mode=E.kind(current),o=E.read(current),select=document.getElementById('est-order-unit');document.getElementById('est-order-fields').hidden=mode==='whole';const opts=mode==='piece'?E.pieces.map(p=>({id:p.id,name:p.name})):E.editTypes.map(id=>({id,name:C.types.find(t=>t.id===id).label}));if(select.dataset.kind!==mode){select.replaceChildren(...opts.map(p=>new Option(p.name,p.id)));select.dataset.kind=mode}select.value=mode==='piece'?o.piece:o.edit;document.getElementById('est-order-quantity-label').hidden=mode!=='piece';if(document.activeElement!==document.getElementById('est-order-quantity'))document.getElementById('est-order-quantity').value=o.quantity;const q=E.estimate(current,{discipline:document.getElementById('discipline').value,deadline:document.getElementById('deadline').value},o);document.getElementById('est-order-assumption').textContent=q.note;document.getElementById('est-order-benefit-result').innerHTML=U.summary(q.total,q.high)}
function update(){scope.dispatchEvent(new Event('change',{bubbles:true}))}
document.getElementById('est-order-unit').onchange=e=>{const o=E.read(current);o[E.kind(current)==='piece'?'piece':'edit']=e.target.value;E.save(current,o);update()};document.getElementById('est-order-quantity').oninput=e=>{if(!e.target.validity.valid)return;E.save(current,{...E.read(current),quantity:e.target.value});update()};
document.addEventListener('salon:order-updated',render);document.addEventListener('salon:benefits-estimate',render);render();
})();
