import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';import{execFileSync}from'node:child_process';
const deps=process.env.SALON_NODE_DEPS||'/Users/saymurrbk.ru/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';const require=createRequire(deps+'/package.json');const{chromium}=require('playwright');const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
async function setup(width=1440,theme='light',reduced=false){const ctx=await browser.newContext({viewport:{width,height:844},colorScheme:theme,reducedMotion:reduced?'reduce':'no-preference',serviceWorkers:'block'}),page=await ctx.newPage(),errors=[],calls=[],orders=[];page.on('pageerror',e=>errors.push(String(e)));await ctx.addInitScript(theme=>{localStorage.setItem('salon_theme',theme);localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1','{"v":1}');sessionStorage.setItem('salon_analytics_qa_session_v1','1')},theme);await ctx.route('**/*',async route=>{const request=route.request(),u=new URL(request.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:request.method()});if(u.pathname==='/api/orders'&&request.method()==='POST'){orders.push(request.postDataJSON());return route.fulfill({json:{ok:true,id:712345,token:'SYNTHETIC_ORDER_TOKEN_123456'}})}return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));assert(p.startsWith(root+'/'));if(!fs.existsSync(p))return route.fulfill({status:404,body:'missing'});return route.fulfill({path:p,contentType:({'.html':'text/html','.css':'text/css','.js':'application/javascript','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.json':'application/json'})[path.extname(p)]||'application/octet-stream'})});return {ctx,page,errors,calls,orders}}
async function go(p,url='/services.html'){await p.goto('https://akademsalon.ru'+url);await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(220)}
async function test(name,fn,width=1440,theme='light',reduced=false){const x=await setup(width,theme,reduced);try{await fn(x);assert.deepEqual(x.errors,[],'no page errors');results.push({name,width,theme,status:'PASS',requests:x.calls,orders:x.orders.length});console.log('PASS',name)}catch(e){results.push({name,width,theme,status:'FAIL',error:String(e),pageErrors:x.errors});await x.page.screenshot({path:path.join(out,name+'-FAIL.png')}).catch(()=>{});throw e}finally{await x.ctx.close()}}
async function geometry(page,sel='body'){const g=await page.locator(sel).evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,rect:e.getBoundingClientRect().toJSON()}));assert(g.scroll<=g.client+1,JSON.stringify(g));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'body no overflow')}
const digits=t=>Number(t.replace(/[^\d]/g,''));
try{
for(const theme of ['light','dark'])await test('review-clarity-and-accessibility-'+theme,async({page:p})=>{await go(p);assert(await p.getByRole('searchbox',{name:'Найти работу или услугу',exact:true}).isVisible());const contrast=await p.locator('#est-hero-perk').evaluate(el=>{const s=getComputedStyle(el),rgb=v=>v.match(/[\d.]+/g).slice(0,3).map(Number),lum=v=>rgb(v).map(c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4}).reduce((n,x,i)=>n+x*[.2126,.7152,.0722][i],0),a=lum(s.color),b=lum(s.backgroundColor);return {foreground:s.color,background:s.backgroundColor,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)}});assert(contrast.ratio>=4.5,JSON.stringify(contrast));await p.locator('[data-product="course"]').click();assert.equal(await p.locator('#cat-total').locator('..').getAttribute('aria-live'),'polite');await p.locator('.cat-additions>summary').click();await p.locator('#cat-vip').check();assert.match(await p.locator('#est-assumption').textContent(),/минимум 3 000/);assert.match(await p.locator('.cat-vip').textContent(),/число итераций и срок сопровождения фиксируем до оплаты/);await p.locator('[data-sheet-speed="expressfast"]').click();assert.match(await p.locator('#est-assumption').textContent(),/бюджет ×2–3/);assert.match(await p.locator('#est-assumption').textContent(),/Возможность подтвердим/);await p.locator('.est-sheet-benefits>details>summary').click();await p.locator('#est-sheet-deposit').evaluate(el=>el.closest('details').open=true);await p.locator('#est-sheet-deposit').selectOption('60000');const note=await p.locator('#est-benefit-result').textContent();assert.match(note,/Первоначальные расходы/);assert.match(note,/Деньги на депозите не являются скидкой/);assert.match(note,/Резерв не доступен сейчас/);results.push({name:'hero-perk-contrast',theme,...contrast,status:'PASS'});},390,theme,true);
}catch(e){console.error(e);process.exitCode=1}finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),root,browser:'Chrome',api:'all synthetic; zero real mutations',results},null,2));}
