// Fresh private contexts. Real production GET/HEAD only; never sends a request or analytics.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const require=createRequire((process.env.SALON_NODE_DEPS||'/Users/saymurrbk.ru/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules')+'/package.json');
const{chromium}=require('playwright'),out=path.resolve(process.argv[2]),manifest=JSON.parse(fs.readFileSync(process.argv[3]));fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
try{for(const width of [319,1440])for(const theme of ['light','dark']){
 const ctx=await browser.newContext({viewport:{width,height:900},colorScheme:theme,serviceWorkers:'block',reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[],mutations=[];p.on('pageerror',e=>errors.push(String(e)));
 await ctx.addInitScript(theme=>{localStorage.setItem('salon_theme',theme);localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1','{"v":1}');sessionStorage.setItem('salon_analytics_qa_session_v1','1')},theme);
 await ctx.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.hostname!=='akademsalon.ru')return route.abort();if(!['GET','HEAD'].includes(req.method())){mutations.push({path:url.pathname,method:req.method()});return route.abort()}return route.continue()});
 await p.goto('https://akademsalon.ru/services.html',{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready);await p.locator('[data-product="course"]').click();await p.locator('#cat-deadline-calendar').click();
 const day=p.locator('[data-date]:not([disabled])').last(),date=await day.getAttribute('data-date');await day.click();
 const total=await p.locator('#cat-total').textContent();await p.locator('#cat-checkout').click();await p.waitForURL('**/configurator.html?composition=1');assert.equal(await p.locator('#deadline').inputValue(),date);assert.equal(await p.locator('#summary-price').textContent(),total);
 assert(await p.locator('body.intake-studio').count());assert.equal(await p.locator('[data-contact-mode=telegram]').getAttribute('aria-pressed'),'true');assert(await p.locator('#name').isVisible());assert.equal(await p.locator('.intake-personal').getAttribute('open'),null);
 await p.locator('#intake-task-details>summary').click();assert.equal(await p.locator('.ic-brief-tools').getAttribute('open'),null);assert((await p.locator('.ic-brief-tools').boundingBox()).height<=52);
 await p.locator('#intake-task-details').screenshot({path:path.join(out,'live-brief-'+width+'-'+theme+'.png')});
 await p.locator('.ic-brief-tools>summary').click();await p.getByRole('button',{name:'Добавить пункт: Источники',exact:true}).click();assert.equal(await p.locator('#details').inputValue(),'Требования к источникам: ');await p.locator('.ic-brief-undo').click();assert.equal(await p.locator('#details').inputValue(),'');await p.locator('.ic-brief-tools>summary').click();
 await p.locator('#contact').fill('qa-intake@example.invalid');await p.locator('[data-contact-mode=phone]').click();assert.match(await p.locator('#ic-contact-format').textContent(),/Сейчас введён Email.*по телефону замени контакт/);assert.equal(await p.locator('#contact').inputValue(),'qa-intake@example.invalid');await p.locator('#contact').fill('+7 (900) 000-00-00');assert.equal(await p.locator('[data-contact-mode=phone]').getAttribute('aria-pressed'),'true');
 await p.locator('.intake-contact').screenshot({path:path.join(out,'live-contact-'+width+'-'+theme+'.png')});
 await p.locator('.intake-personal>summary').click();await p.locator('#promo').fill('QA-CODE');assert.match(await p.locator('.intake-personal>summary').textContent(),/1 код добавлен/);assert.equal(await p.locator('#summary-price').textContent(),total);assert.equal(await p.locator('#consent').isChecked(),false);assert.equal(await p.locator('#participation').isChecked(),false);
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 const assets=await p.locator('script[src*="intake-studio"],link[href*="intake-studio"],script[src*="form-polish-20260924"]').evaluateAll(a=>a.map(e=>e.src||e.href));assert.equal(assets.length,3);for(const a of assets){const u=new URL(a);assert.equal(u.searchParams.get('r'),manifest.files[u.pathname.slice(1)].slice(0,16))}
 assert.deepEqual(errors,[]);assert.deepEqual(mutations,[]);results.push({width,theme,status:'PASS',date,total,assets,errors,mutations,checkboxes:'unchecked',codes:'unconfirmed; price unchanged'});await ctx.close();
}}catch(e){console.error(e);results.push({status:'FAIL',error:String(e)});process.exitCode=1}finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({at:new Date().toISOString(),source_commit:manifest.source_commit,route:'services → configurator',browser:'Chrome',network:'live read-only; all non-GET/HEAD blocked',results},null,2))}
