// Isolated browser regression: routes ALL requests, never contacts production.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire((process.env.SALON_NODE_DEPS||'/Users/saymurrbk.ru/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules')+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),output=path.resolve(process.argv[3]);fs.mkdirSync(output,{recursive:true});
const serverContract=JSON.parse(fs.readFileSync(process.argv[4]||'docs/brain/evidence/salon-comfort-20260924/server-contract.json'));
const browser=await chromium.launch({headless:true,channel:'chrome'});const results=[];
const sourceCommit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const privateTopic='SYNTHETIC_PRIVATE_TOPIC_SENTINEL',privateContact='synthetic@example.invalid';
async function setup(opts={}){
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',timezoneId:'Europe/Moscow',reducedMotion:opts.reduced?'reduce':'no-preference'});
 const calls=[],events=[],orders=[],uploads=[],errors=[];let response=opts.response||'ok';
 await context.addInitScript(({opts})=>{
  const now=Date.now();localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:opts.consent!==false,at:new Date(now-60000).toISOString(),expiresAt:new Date(now+86400000).toISOString()}));
  localStorage.setItem('salon_theme',opts.theme||'light');
  if(opts.owner)localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));
  if(opts.qa)sessionStorage.setItem('salon_analytics_qa_session_v1','1');
  if(opts.saved)sessionStorage.setItem('salon_direct_selection_v1',JSON.stringify({product:'master',scope:'editing',discipline:'law',deadline:'2030-01-01'}));
 },{opts});
 await context.route('**/*',async route=>{
  const r=route.request(),u=new URL(r.url());
  if(u.hostname!=='akademsalon.ru')return route.abort();
  if(u.pathname.startsWith('/api/')){
   calls.push({path:u.pathname,body:r.postData(),headers:r.headers()});
   if(u.pathname==='/api/analytics/grant')return route.fulfill({json:{ok:true,grant:'synthetic-test-grant-123456',expires_at:Math.floor((opts.now?Date.parse(opts.now):Date.now())/1000)+3600}});
   if(u.pathname==='/api/analytics/events'){let b=r.postDataJSON();events.push(...b.events);return route.fulfill({json:{ok:true,processed:b.events.map(e=>e.event_id)}})}
   if(u.pathname==='/api/orders'){
    orders.push(r.postDataJSON());await new Promise(r=>setTimeout(r,120));
    if(response==='network')return route.abort('connectionfailed');
    if(response==='malformed')return route.fulfill({json:{ok:true}});
    if(typeof response==='number')return route.fulfill({status:response,json:{ok:false,error:response===400?'bad_input':response===409?'conflict':'unavailable'}});
    return route.fulfill({json:{ok:true,id:712345,token:'SYNTHETIC_ORDER_TOKEN_123456'}});
   }
   if(/\/orders\/\d+\/upload$/.test(u.pathname)){uploads.push(r.postDataBuffer().toString());return route.fulfill({status:uploads.length===1?503:200,json:{ok:uploads.length!==1}})}
   return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}});
  }
  const f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));
  if(!f.startsWith(root+'/')||!fs.existsSync(f))return route.abort();
  return route.fulfill({path:f,contentType:({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});
 });
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 async function flush(){for(let i=0;i<3;i++){await page.waitForTimeout(300);await page.evaluate(()=>window.dispatchEvent(new Event('online')))}await page.waitForTimeout(200)}
 function names(){return events.map(e=>e.event)}
 async function valid(){await page.locator('#topic').fill(privateTopic);await page.locator('#contact').fill(privateContact);await page.locator('#consent').check();if(await page.locator('#participation').isVisible())await page.locator('#participation').check()}
 async function privacy(){
  await flush();assert.deepEqual(errors,[]);
  for(const c of calls.filter(c=>c.path.startsWith('/api/analytics/'))){assert(!/SYNTHETIC_PRIVATE|synthetic@example|SYNTHETIC_ORDER_TOKEN|private-file/.test(c.body||''));assert(!c.headers.cookie)}
  for(const e of events){assert(serverContract.events[e.event],e.event);if(e.cta_id)assert(serverContract.cta_values.includes(e.cta_id),e.cta_id);assert.equal(e.page,'/configurator.html');}
 }
 return {context,page,calls,events,orders,uploads,errors,flush,names,valid,privacy,setResponse(v){response=v}};
}
async function test(name,fn){if(process.env.SALON_TEST_FILTER&&!new RegExp(process.env.SALON_TEST_FILTER).test(name))return;try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.error('FAIL '+name+' '+e.message);process.exitCode=1}}
const plan='https://akademsalon.ru/configurator.html?service=pl&work=course';
async function choose(page,id,label){const wrap=page.locator('.salon-select').filter({has:page.locator('#'+id)});await wrap.locator('.salon-select-trigger').evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}));await page.waitForTimeout(60);await wrap.locator('.salon-select-trigger').click();await wrap.getByRole('option',{name:label,exact:true}).click()}const route='https://akademsalon.ru/configurator.html';
async function open(x,url=route){await x.page.goto(url);await x.page.evaluate(()=>document.fonts.ready);await x.page.waitForTimeout(120)}
async function brief(p,expandTools=true){await p.locator('#intake-task-details > summary').click();if(expandTools)await p.locator('.ic-brief-tools>summary').click()}
const chip=(p,label)=>p.getByRole('button',{name:'Добавить пункт: '+label,exact:true});
try{
for(const width of [319,360,390,768,1024,1440])for(const theme of ['light','dark'])await test('form-layout-'+width+'-'+theme,async()=>{const x=await setup({width,theme,consent:false,reduced:true});try{const p=x.page;await open(x);assert.equal(await p.locator('[data-contact-mode][aria-pressed=true]').count(),1);assert.equal(await p.locator('[data-contact-mode=telegram]').getAttribute('aria-pressed'),'true');await brief(p,false);assert.equal(await p.locator('.ic-brief-tools').getAttribute('open'),null);assert((await p.locator('.ic-brief-tools').boundingBox()).height<=52);await p.locator('.intake-personal > summary').click();await p.locator('#details').fill('Уже есть тема и методичка. Важно согласовать план до начала работы.');await p.locator('#contact').fill('synthetic@example.invalid');await p.locator('#name').fill('Тест');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no body overflow');for(const b of await p.locator('[data-contact-mode],.ic-brief-chip,.intake-consents .check-row:not([hidden]),#send-order').all()){if(!await b.isVisible())continue;const r=await b.boundingBox();assert(r.width>=44&&r.height>=44,'target >=44px');assert(await b.evaluate(e=>e.scrollWidth<=e.clientWidth+1),'no clipped control '+await b.textContent())}if(width<600){assert.equal(await p.locator('.polish-contact-modes').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),2);assert.equal(await p.locator('#contact').evaluate(e=>getComputedStyle(e).fontSize),'16px')}assert.equal(await p.locator('#name').evaluate(e=>!!e.closest('.intake-personal')),false);assert.equal(await p.locator('#consent').isChecked(),false);await p.locator('#intake-task-details').screenshot({path:path.join(output,'brief-'+width+'-'+theme+'.png')});await p.locator('.intake-contact').screenshot({path:path.join(output,'contact-'+width+'-'+theme+'.png')});await x.privacy()}finally{await x.context.close()}});
await test('brief-assistance-preserves-text-focuses-existing-and-undoes-only-insertion',async()=>{const x=await setup({width:390,consent:false});try{const p=x.page;await open(x);await brief(p);const prose='SYNTHETIC_PRIVATE исходное задание';await p.locator('#details').fill(prose);await chip(p,'Источники').click();const inserted=await p.locator('#details').inputValue();assert.equal(inserted,prose+'\n\nТребования к источникам: ');assert(await p.locator('#details').evaluate(e=>e===document.activeElement&&e.selectionStart===e.value.length));await chip(p,'Источники').click();assert.equal(await p.locator('#details').inputValue(),inserted);await p.locator('.ic-brief-undo').click();assert.equal(await p.locator('#details').inputValue(),prose);await chip(p,'Что уже есть').click();await p.locator('#details').pressSequentially('Мои данные');assert(!await p.locator('.ic-brief-undo').isVisible());assert((await p.locator('#details').inputValue()).includes(prose));await x.privacy()}finally{await x.context.close()}});
await test('template-is-not-a-topic-and-maxlength-never-truncates-user-text',async()=>{const x=await setup({consent:false});try{const p=x.page;await open(x);await brief(p);await chip(p,'Структура').click();assert.equal(await p.locator('#topic').inputValue(),'');assert(!await p.locator('#intake-use-topic').isVisible());await p.locator('#details').pressSequentially('Введение и две главы');assert(!await p.locator('#intake-use-topic').isVisible());await p.locator('#topic').fill('x');await p.locator('#topic').fill('');assert(!await p.locator('#intake-use-topic').isVisible());await p.locator('#details').fill('x'.repeat(11999));await chip(p,'Источники').click();assert.equal((await p.locator('#details').inputValue()).length,11999);assert.match(await p.locator('#ic-brief-message').textContent(),/не хватает места/);await p.locator('#details').fill('Настоящая тема\nПолное задание');assert(await p.locator('#intake-use-topic').isVisible());await p.locator('#intake-use-topic').click();assert.equal(await p.locator('#topic').inputValue(),'Настоящая тема');await x.privacy()}finally{await x.context.close()}});
await test('contact-detection-keeps-raw-values-and-optional-codes-do-not-change-price',async()=>{const x=await setup({width:390,consent:false});try{const p=x.page;await open(x);const price=await p.locator('#summary-price').textContent();for(const [mode,value]of [['telegram','@synthetic_user'],['email','synthetic@example.invalid'],['phone','+7 (900) 000-00-00'],['vk','https://vk.com/id12345678901']]){await p.locator('#contact').fill(value);assert.equal(await p.locator('[data-contact-mode='+mode+']').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#contact').inputValue(),value);assert.equal(await p.locator('#contact').getAttribute('type'),null);assert.match(await p.locator('#ic-contact-format').textContent(),/Формат:/)}await p.locator('[data-contact-mode=email]').click();assert.equal(await p.locator('#contact').inputValue(),'https://vk.com/id12345678901');await p.locator('.intake-personal > summary').click();await p.locator('#promo').fill('SYNTHETIC_PRIVATE_PROMO');await p.locator('#gift').fill('SYNTHETIC_PRIVATE_GIFT');assert.match(await p.locator('.intake-personal > summary small').textContent(),/2 кода/);assert.equal(await p.locator('#summary-price').textContent(),price);await x.privacy()}finally{await x.context.close()}});
await test('exact-consent-links-unchecked-state-dynamic-visibility-and-payload',async()=>{const x=await setup({consent:false});try{const p=x.page;await open(x);const expected=JSON.parse(fs.readFileSync(new URL('./baseline-contract.json',import.meta.url)));assert.equal(await p.evaluate(()=>SalonDirectContract.consent_doc),expected.consent_doc);const norm=s=>s.replace(/\s+/g,' ').replace(/\s+([,.])/g,'$1').trim();for(const c of expected.consents){const row=p.locator('label.check-row').filter({has:p.locator('#'+c.id)});assert.equal(norm(await row.locator('.ic-consent-text').textContent()),norm(c.text));assert.deepEqual(await row.locator('a').evaluateAll(a=>a.map(e=>e.getAttribute('href'))),c.links);assert.equal(await p.locator('#'+c.id).isChecked(),false)}await p.locator('#intake-settings > summary').click();await choose(p,'scope','Доработку моего текста');assert(!await p.locator('#participation-row').isVisible());await p.locator('#topic').fill(privateTopic);await p.locator('#contact').fill(privateContact);await p.locator('#name').fill('SYNTHETIC_PRIVATE_NAME');await brief(p);await p.locator('#details').fill('SYNTHETIC_PRIVATE requirements text that needs to survive unchanged.');await p.locator('.intake-personal > summary').click();await p.locator('#promo').fill('TESTCODE');await p.locator('#gift').fill('TESTGIFT');await p.locator('#consent').check();await p.locator('#send-order').click();await p.locator('#order-success:visible').waitFor();assert.equal(x.orders.length,1);const o=x.orders[0];assert.equal(o.name,'SYNTHETIC_PRIVATE_NAME');assert.equal(o.contact,privateContact);assert.equal(o.promo,'TESTCODE');assert.equal(o.gift,'TESTGIFT');assert(o.details.includes('SYNTHETIC_PRIVATE requirements text that needs to survive unchanged.'));assert.equal(o.consent,true);fs.writeFileSync(path.join(output,'synthetic-payload.json'),JSON.stringify(o,null,2));await x.privacy()}finally{await x.context.close()}});
await test('frozen-retry-disables-helpers-and-preserves-identity-and-rejection-unlocks',async()=>{for(const response of [503,400]){const x=await setup({response,consent:false});try{const p=x.page;await open(x);await brief(p);await p.locator('#details').fill('SYNTHETIC_PRIVATE original requirement');await chip(p,'Источники').click();await x.valid();await p.locator('#send-order').click();await p.locator('#form-message:visible').waitFor();const before=await p.locator('#details').inputValue();if(response===503){assert(await chip(p,'Структура').isDisabled());assert(await p.locator('.ic-brief-undo').isDisabled());await chip(p,'Структура').evaluate(e=>{e.disabled=false;e.click()});assert.equal(await p.locator('#details').inputValue(),before)}else{assert(!await chip(p,'Структура').isDisabled());await chip(p,'Структура').click();assert.notEqual(await p.locator('#details').inputValue(),before)}x.setResponse('ok');await p.locator('#send-order').click();await p.locator('#order-success:visible').waitFor();if(response===503){assert.equal(x.orders[0].client_request_id,x.orders[1].client_request_id);assert.equal(x.orders[0].details,x.orders[1].details)}await x.privacy()}finally{await x.context.close()}}});
await test('contact-switch-explains-existing-value-and-selected-check-does-not-overlap',async()=>{const x=await setup({width:319,consent:false});try{const p=x.page;await open(x);await p.locator('#contact').fill('synthetic@example.invalid');await p.locator('[data-contact-mode=phone]').click();assert.equal(await p.locator('#contact').inputValue(),'synthetic@example.invalid');assert.match(await p.locator('#ic-contact-format').textContent(),/Сейчас введён Email.*по телефону замени контакт/);await p.locator('#contact').press('Tab');assert.equal(await p.locator('[data-contact-mode=email]').getAttribute('aria-pressed'),'true');assert.match(await p.locator('#ic-contact-format').textContent(),/^Формат: Email/);for(const mode of ['telegram','phone']){await p.locator('[data-contact-mode='+mode+']').click();const label=await p.locator('[data-contact-mode='+mode+'] .ic-channel-name').boundingBox(),check=await p.locator('[data-contact-mode='+mode+'] .ic-channel-check').boundingBox();assert(check.y+check.height<=label.y||check.x>=label.x+label.width,'selected marker does not overlap channel name')}await p.locator('#contact').fill('+7 (900) 000-00-00');assert.match(await p.locator('#ic-contact-format').textContent(),/^Формат: Телефон/);await brief(p,false);await p.locator('.ic-brief-tools>summary').focus();await p.keyboard.press('Enter');assert(await chip(p,'Источники').isVisible());await p.keyboard.press('Tab');assert(await chip(p,'Структура').evaluate(e=>e===document.activeElement));await x.privacy()}finally{await x.context.close()}});
await test('short-screen-keyboard-and-native-fallback',async()=>{const x=await setup({width:319,consent:false});try{const p=x.page;await p.setViewportSize({width:319,height:484});await open(x);await p.locator('[data-contact-mode=phone]').focus();await p.keyboard.press('Enter');assert(await p.locator('#contact').evaluate(e=>e===document.activeElement));await p.locator('#contact').press('Tab');assert(await p.locator('#name').evaluate(e=>e===document.activeElement));await p.locator('#consent').focus();await p.keyboard.press('Space');assert(await p.locator('#consent').isChecked());await x.privacy();await x.context.route('**/assets/js/intake-studio.js*',r=>r.abort());await p.reload();assert.equal(await p.locator('.ic-editor').count(),0);await p.locator('.intake-personal > summary').click();assert(await p.locator('#name').isVisible());assert(await p.locator('#contact').isVisible())}finally{await x.context.close()}});
}finally{await browser.close();fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({sourceCommit,root,browser:'Chrome',routes:[route],data:'synthetic only; every request intercepted',results},null,2));}
