"""Reviewed commercial metadata and service entry pages; no financial mutations."""
from pathlib import Path
import subprocess,re,json,html
ROOT=Path(__file__).resolve().parents[5]
BASE='834e3ec20f8d'
def old(n):return subprocess.check_output(['git','show',BASE+':'+n],cwd=ROOT,text=True)
def e(s):return html.escape(str(s),quote=True)
DATA=[
 dict(slug='kursovaya-rabota',id='course',name='Курсовая работа',order='Заказать курсовую',title='Курсовая работа на заказ — от 14 000 ₽ | Академический Салон',price=14000,days='14–30 дней',intro='От темы и плана до глав, выводов и оформления. Или только тот фрагмент, с которым нужна помощь.',outline=['План и логика исследования','Введение и главы по заданию','Выводы, источники, оформление'],materials=['Тема и дисциплина','Методичка и нужный объём','Срок и замечания руководителя'],limit='Практическую часть строим на согласованных данных. Если нужны опрос, расчёты или исследование, сначала уточним материалы и метод.',guides=[('guide-skolko-stoit-kursovaya.html','Из чего складывается цена'),('guide-vvedenie-kursovoy.html','Как устроено введение')],related=[('kursovaya-po-psihologii.html','Психология'),('kursovaya-po-ekonomike.html','Экономика'),('kursovaya-po-yurisprudencii.html','Право'),('kursovaya-po-pedagogike.html','Педагогика'),('kursovaya-po-menedzhmentu.html','Менеджмент'),('kursovaya-po-informatike.html','Информатика')]),
 dict(slug='diplomnaya-rabota',id='diplom',name='Дипломная работа / ВКР',order='Заказать ВКР',title='Дипломная работа и ВКР на заказ — от 40 000 ₽',price=40000,days='30–60 дней',intro='Соберём работу вокруг твоей темы и требований кафедры. Можно заказать весь проект, отдельную главу или доработку.',outline=['Тема, план и метод исследования','Теоретическая и практическая главы','Введение, заключение и источники'],materials=['Тема и утверждённый план, если есть','Методичка и требования кафедры','Исходные данные и обратная связь'],limit='Данные исследования и содержательные решения согласуем с тобой. Презентация и речь к защите добавляются отдельно; их состав виден до оплаты.',guides=[('guide-skolko-stoit-diplomnaya.html','Как оценить бюджет ВКР'),('guide-zashchita-diploma.html','Что подготовить к защите')],related=[('diplomnaya-po-psihologii.html','Психология'),('diplomnaya-po-ekonomike.html','Экономика'),('diplomnaya-po-yurisprudencii.html','Право')]),
 dict(slug='otchet-po-praktike',id='practice',name='Отчёт по практике',order='Заказать отчёт',title='Отчёт по практике на заказ — от 14 000 ₽ | Академический Салон',price=14000,days='7–14 дней',intro='Превратим материалы твоей практики в связный отчёт по программе вуза. Готовый черновик тоже можно доработать.',outline=['Описание базы и задач практики','Анализ выполненной работы','Выводы и согласованные приложения'],materials=['Программа практики и методичка','Материалы о базе и выполненных задачах','Даты, объём и список приложений'],limit='Используем реальные материалы практики. Не придумываем прохождение, подписи или печати. Дневник и приложения включаем только после согласования состава.',guides=[('guide-otchet-po-praktike.html','Структура отчёта'),('guide-dnevnik-praktiki.html','Как заполнить дневник')],related=[('dorabotka-otcheta-po-praktike.html','Доработка готового отчёта'),('normokontrol-vkr.html','Оформление по требованиям')]),
 dict(slug='referat',id='referat',name='Реферат',order='Заказать реферат',title='Реферат на заказ — от 2 500 ₽, сроки и состав',price=2500,days='3–7 дней',intro='Обзор темы с понятной структурой, выводами и источниками. Согласуем объём и требования к литературе.',outline=['План и вводная часть','Обзор темы по источникам','Заключение и список литературы'],materials=['Тема и учебная дисциплина','Объём и требования к оформлению','Список обязательных источников, если есть'],limit='Если преподаватель задал конкретные книги, статьи или период публикаций, передай этот список вместе с темой. Источники подбираются под задание.',guides=[('guide-spisok-literatury.html','Как оформить источники'),('guide-titulnyj-list.html','Что проверить на титульном')],related=[('services.html#works','Эссе и самостоятельные'),('avtorskiy-zakaz.html','Нестандартный текст')]),
 dict(slug='magisterskaya-dissertaciya',id='master',name='Магистерская диссертация',order='Обсудить магистерскую',title='Магистерская диссертация — помощь от 60 000 ₽',price=60000,days='45–90 дней',intro='Помощь с исследовательским проектом: от методологии до анализа результатов и текста глав. Вся работа или отдельный этап.',outline=['Исследовательский вопрос и методология','Главы и анализ согласованных данных','Результаты, выводы и оформление'],materials=['Тема и требования программы','План и комментарии руководителя','Данные, методики и материалы исследования'],limit='Объём эмпирики, методы и доступность данных влияют на смету и срок. Не обещаем результат защиты; твой вклад и границы помощи фиксируются в задании.',guides=[('guide-vkr-struktura.html','Введение и задачи исследования'),('guide-zashchita-diploma.html','Подготовка к защите')],related=[('plan.html','Уточнение темы и плана'),('normokontrol-vkr.html','Нормоконтроль')]),
 dict(slug='nauchnaya-statya',id='rinc',name='Научная статья',order='Заказать помощь со статьёй',title='Научная статья — подготовка текста от 9 000 ₽',price=9000,days='10–21 день',intro='Подготовка и редактура текста по требованиям выбранного издания. От структуры и аргументации до аннотации и источников.',outline=['Структура и основной текст','Аннотация и ключевые слова','Источники и оформление для журнала'],materials=['Тема, результаты и материалы исследования','Требования выбранного журнала','Черновик и замечания, если есть'],limit='Публикация, редакционные сборы и решение журнала не входят в подготовку текста. Не гарантируем принятие статьи и не придумываем результаты исследования.',guides=[('guide-rinc-statya.html','Подготовка и подача в журнал'),('guide-spisok-literatury.html','Проверка списка источников')],related=[('redaktura-posle-ii.html','Редактура готового текста'),('proverka-istochnikov-vkr.html','Сверка источников')]),
 dict(slug='kandidatskaya-dissertaciya',id='kandidat',name='Кандидатская диссертация',order='Обсудить исследование',title='Кандидатская диссертация — помощь по этапам исследования',price=200000,days='от 3 месяцев',intro='Индивидуальная работа над исследованием: методология, отдельные главы, анализ материалов и научная редактура.',outline=['Замысел и методологическая рамка','Работа над согласованными главами','Анализ, аргументация и научная редактура'],materials=['Специальность, тема и план','Результаты и материалы исследования','Требования совета и комментарии консультанта'],limit='Полная кандидатская не выполняется за сутки. Срочность отдельной задачи обсуждается по материалам. Авторство, научные результаты и решение диссертационного совета не продаются.',guides=[('plan.html','Сначала проработать план'),('proverka-istochnikov-vkr.html','Проверить источники')],related=[('nauchnaya-statya.html','Текст научной статьи'),('services.html#works','Отдельная глава')]),
]
meta={
 'index.html':('Заказать учебную работу: курсовую, ВКР, реферат | Академический Салон','Учебные работы целиком, отдельные главы и доработка. Курсовые от 14 000 ₽, рефераты от 2 500 ₽. Состав, срок и точная цена до оплаты. Есть экспресс.'),
 'services.html':('Студенческие работы на заказ — цены и сроки | Академический Салон','Сравни эссе, реферат, курсовую, отчёт по практике и ВКР. Выбери всю работу или часть, обычный срок или экспресс. Состав и стоимость до оплаты.'),
 'reviews.html':('Отзывы клиентов об учебных работах | Академический Салон','Посмотри отзывы клиентов Академического Салона: сообщения о работе, сроках и взаимодействии. Рядом — примеры документов и условия заказа.'),
 'samples.html':('Примеры курсовых, отчётов и учебных работ | Академический Салон','Открой реальные обезличенные документы в просмотрщике. Посмотри структуру, оформление и примеры разных учебных задач перед заказом.'),
 'about.html':('Об Академическом Салоне — как устроена работа над заказом','Мастерская учебных работ от создателя Кладовой ГИПСР. Посмотри, что согласуется до оплаты, как идёт работа и что ты получаешь в конце.'),
}
shell=old('about.html');header=re.search(r'<header\b.*?</header>',shell,re.S)[0];footer=re.search(r'<footer\b.*?</footer>',shell,re.S)[0]
for d in DATA:
 price=f"{d['price']:,}".replace(',',' ')
 desc=f"{d['name']}: от {price} ₽, планово {d['days']}. Вся работа, часть или доработка. Состав, требования и точная смета согласуются до оплаты."
 meta[d['slug']+'.html']=(d['title'],desc)
 h=old(d['slug']+'.html').split('</head>')[0]+'<link rel="stylesheet" href="assets/css/salon-home.css?v=20260909catalog1"></head>'
 # Metadata is normalized in the common pass below.
 speed='''<button type="button" data-entry-speed="express24" aria-pressed="false">24 часа <b>×2</b></button><button type="button" data-entry-speed="expressfast" aria-pressed="false">Быстрее</button>''' if d['id']!='kandidat' else ''
 main=f'''<main id="main" class="sen-main" data-service-entry data-entry-product="{d['id']}" data-entry-base="{d['price']}" data-entry-days="{e(d['days'])}">
<nav class="sen-breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/services.html">Работы и цены</a><span>/</span><span>{e(d['name'])}</span></nav>
<section class="sen-hero"><div class="sen-intro"><span class="eyebrow">ПО ТВОЕМУ ЗАДАНИЮ</span><h1>{e(d['name'])}<br><em>В твоём объёме.</em></h1><p>{e(d['intro'])}</p><div class="sen-included"><span>✓ По методичке</span><span>✓ Смета до оплаты</span><span>✓ Прямой заказ</span></div></div>
<div class="sen-brief"><div class="sen-brief-top"><span>ТВОЯ ЗАДАЧА</span><b aria-hidden="true">а.</b></div><h2>Нужно ровно <em>это.</em></h2><fieldset><legend>Какой объём?</legend><div class="sen-options"><button type="button" data-entry-scope="whole" aria-pressed="true">Вся работа</button><button type="button" data-entry-scope="part" aria-pressed="false">Только часть</button><button type="button" data-entry-scope="editing" aria-pressed="false">Есть текст</button></div></fieldset><fieldset><legend>Когда нужно?</legend><div class="sen-options"><button type="button" data-entry-speed="standard" aria-pressed="true">Планово</button>{speed}</div></fieldset>
<div class="sen-estimate" aria-live="polite" aria-atomic="true"><div><span>Ориентир</span><strong data-entry-price>от {price} ₽</strong></div><div><span>Срок</span><strong data-entry-term>{e(d['days'])}</strong></div><p data-entry-note>За согласованный состав всей работы. Точная цена и дата после задания, до оплаты.</p></div>
<a class="button sen-order" data-entry-order href="/configurator.html?product={d['id']}&amp;result=whole">{e(d['order'])} <span aria-hidden="true">↗</span></a><p class="sen-micro">Тема, требования и контакт. Файлы можно приложить в заявке.</p><noscript><p>Выбери формат в заявке: <a href="/configurator.html?product={d['id']}&amp;result=part">нужна часть</a> · <a href="/configurator.html?product={d['id']}&amp;result=editing">доработка</a>. Экспресс тоже доступен в форме.</p></noscript></div></section>
<section class="sen-delivery"><div><span class="eyebrow">НА ВЫХОДЕ</span><h2>У результата<br><em>есть состав.</em></h2><p data-entry-scope-copy>Базовый состав всей работы. Конкретный объём закрепим в задании.</p></div><ol class="sen-document">{''.join(f'<li><span>{i+1:02}</span><strong>{e(x)}</strong></li>' for i,x in enumerate(d['outline']))}<li class="sen-document-foot">Редактируемый документ и согласованные материалы.</li></ol></section>
<section class="sen-ready"><div><span class="eyebrow">БЫСТРЫЙ СТАРТ</span><h2>Что уже<br><em>есть у тебя?</em></h2><p>Отметь для себя. Это памятка, не обязательные шаги перед заказом.</p></div><div><div class="sen-checklist">{''.join(f'<label><input type="checkbox"><span>{e(x)}</span></label>' for x in d['materials'])}</div><p class="sen-progress" data-entry-progress aria-live="polite">Можно начать с того, что есть.</p><p class="sen-limit">{e(d['limit'])}</p></div></section>
<section class="sen-links" aria-label="Посмотреть перед заказом"><a href="/samples.html"><span>ДОКУМЕНТЫ</span><strong>Посмотреть примеры ↗</strong><p>Структура и оформление в настоящем просмотрщике.</p></a><a href="/reviews.html"><span>ОБРАТНАЯ СВЯЗЬ</span><strong>Почитать отзывы ↗</strong><p>Что клиенты рассказывают о взаимодействии.</p></a><a href="/guarantees.html"><span>ДО ОПЛАТЫ</span><strong>Понять условия ↗</strong><p>Состав заказа, границы правок и ответственность.</p></a></section>
<section class="sen-reading"><h2>Полезно <em>для этой задачи.</em></h2><div>{''.join(f'<a href="/{e(url)}">{e(label)} <span aria-hidden="true">↗</span></a>' for url,label in d['guides'])}</div><div class="sen-related">{''.join(f'<a href="/{e(url)}">{e(label)} ↗</a>' for url,label in d['related'])}</div></section>
<section class="sen-faq"><h2>До заказа <em>обычно спрашивают.</em></h2><div><details><summary>Нужна только часть. Как считается цена?</summary><p>По объёму и сложности выбранного фрагмента. Цена целой работы не делится механически на число глав. В заявке можно указать раздел, задачи и требования.</p></details><details><summary>Что означает экспресс за 24 часа?</summary><p>{'Для целой кандидатской этот формат недоступен. Срочную отдельную задачу оцениваем по материалам.' if d['id']=='kandidat' else 'Ускоренный формат стоит ×2 к плановой цене работы. Отсчёт начинается после согласования задания, получения материалов и оплаты. Срок меньше суток рассчитывается отдельно.'}</p></details><details><summary>Что входит в оформление и правки?</summary><p>Оформление по переданной методичке включено. Границы правок по исходному заданию фиксируются до начала. Новые требования нормоконтроля и дополнительные материалы согласуем отдельно.</p></details></div></section>
</main>'''
 graph={'@context':'https://schema.org','@graph':[{'@type':'Service','@id':f"https://akademsalon.ru/{d['slug']}.html#service",'name':d['name'],'description':desc,'url':f"https://akademsalon.ru/{d['slug']}.html",'provider':{'@id':'https://akademsalon.ru/#organization'},'offers':{'@type':'AggregateOffer','lowPrice':d['price'],'priceCurrency':'RUB','description':'Ориентир за всю работу. Состав и окончательная цена согласуются до оплаты.'}},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Главная','item':'https://akademsalon.ru/'},{'@type':'ListItem','position':2,'name':'Работы и цены','item':'https://akademsalon.ru/services.html'},{'@type':'ListItem','position':3,'name':d['name'],'item':f"https://akademsalon.ru/{d['slug']}.html"}]}]}
 result=h+f'<body class="salon-experience salon-direct concept-shell salon-entry"><a class="skip-link" href="#main">К содержанию</a>'+header+main+footer.replace('href="configurator.html"',f'href="/configurator.html?product={d["id"]}&amp;result=whole"')+'<script src="assets/js/app.js?v=20260806shell123" defer></script><script src="assets/js/salon-experience.js?v=20260909home3" defer></script><script type="application/ld+json">'+json.dumps(graph,ensure_ascii=False)+'</script></body></html>'
 if d['id']=='kandidat':result=result.replace('Экспресс тоже доступен в форме.','Срок отдельной задачи уточним по материалам.')
 (ROOT/(d['slug']+'.html')).write_text(result)
# Unique discipline intent, using its existing visible prices and scope.
for p in ROOT.glob('*-po-*.html'):
 if p.name not in [x['slug']+'.html' for x in DATA] and re.match(r'(kursovaya|diplomnaya)-po-',p.name):
  s=old(p.name);name=re.search(r'<h1[^>]*>(.*?)</h1>',s,re.S)[1];price=re.search(r'<strong>(от [^<]+₽)</strong>',s)
  title=f"{name} на заказ";description=f"{name}: {price[1] if price else 'смета по заданию'}. Вся работа, отдельный раздел или доработка. Методичка, материалы и точный срок согласуются до оплаты."
  meta[p.name]=(title,description)
for name,(title,desc) in meta.items():
 p=ROOT/name;s=p.read_text();s=re.sub(r'<title>.*?</title>',f'<title>{e(title)}</title>',s,count=1,flags=re.S);s=re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{e(desc)}">',s,count=1);p.write_text(s)
# Canonical alias: retain compatibility URL while consolidating the catalogue.
p=ROOT/'tariffs.html';s=p.read_text().replace('rel="canonical" href="https://akademsalon.ru/tariffs.html"','rel="canonical" href="https://akademsalon.ru/services.html"');p.write_text(s)
for name in ['configurator.html','consent.html','consent-request.html']:
 p=ROOT/name;s=p.read_text();s=re.sub(r'<meta\b(?=[^>]*\bname=["\']robots["\'])[^>]*>','',s,flags=re.I);s=s.replace('</head>','<meta name="robots" content="noindex,follow"></head>');p.write_text(s)
# Public, visible catalogue links: supplement (not intercept) the quick-order cards.
directory='<section class="sen-directory"><div><span class="eyebrow">РАЗОБРАТЬСЯ В ДЕТАЛЯХ</span><h2>Что входит <em>в твою работу.</em></h2><p>Состав, материалы и варианты заказа — на отдельной странице.</p></div><nav aria-label="Подробнее о видах работ">'+''.join(f'<a href="/{d["slug"]}.html">{e(d["name"])} <span aria-hidden="true">↗</span></a>' for d in DATA)+'</nav></section>'
for name in ['services.html','tariffs.html']:
 p=ROOT/name;s=p.read_text();s=re.sub(r'<section class="sen-directory">.*?</section>','',s,flags=re.S);s=s.replace('<section class="cat-assurance"',directory+'<section class="cat-assurance"');p.write_text(s)
# Remove only this generator's identity graph before the normalized metadata pass.
p=ROOT/'index.html';s=p.read_text();s=re.sub(r'<script type="application/ld\+json">(?:(?!</script>).)*https://akademsalon.ru/#website(?:(?!</script>).)*</script>','',s,flags=re.S);p.write_text(s)
# All indexable pages get stable sharing metadata; preserve page-specific imagery.
for p in ROOT.glob('*.html'):
 s=p.read_text();head=s.split('</head>')[0]
 if re.search(r'<meta[^>]*name=["\']robots["\'][^>]*content=["\'][^"\']*noindex',head,re.I):continue
 can=re.search(r'<link rel="canonical" href="([^"]+)"',head)
 title=re.search(r'<title>(.*?)</title>',head,re.S);desc=re.search(r'<meta name="description" content="([^"]*)"',head)
 if not(can and title and desc):continue
 image=re.search(r'<meta property="og:image" content="([^"]+)"',head)
 image=image[1] if image else 'https://akademsalon.ru/assets/img/og-cover-v4.png'
 for key in ['og:title','og:description','og:url','og:site_name','og:type','og:image','og:locale','twitter:card','twitter:title','twitter:description','twitter:image']:
  s=re.sub(r'<meta\b(?=[^>]*(?:property|name)=["\']'+re.escape(key)+r'["\'])[^>]*>','',s,flags=re.I)
 values={'og:title':html.unescape(title[1]),'og:description':html.unescape(desc[1]),'og:url':can[1],'og:site_name':'Академический Салон','og:type':'article' if p.name.startswith('guide-') else 'website','og:locale':'ru_RU','og:image':html.unescape(image),'twitter:card':'summary_large_image','twitter:title':html.unescape(title[1]),'twitter:description':html.unescape(desc[1]),'twitter:image':html.unescape(image)}
 tags=''.join(f'<meta {"name" if k.startswith("twitter:") else "property"}="{k}" content="{e(v)}">' for k,v in values.items())
 s=s.replace('</head>',tags+'</head>');p.write_text(s)
p=ROOT/'index.html';s=p.read_text();g={'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':'https://akademsalon.ru/#website','url':'https://akademsalon.ru/','name':'Академический Салон','alternateName':'Академсалон','inLanguage':'ru-RU','publisher':{'@id':'https://akademsalon.ru/#organization'}},{'@type':'Organization','@id':'https://akademsalon.ru/#organization','name':'Академический Салон','url':'https://akademsalon.ru/','logo':{'@type':'ImageObject','url':'https://akademsalon.ru/assets/img/icon-512.png'},'sameAs':['https://t.me/akademsalon']} ]};s=s.replace('</head>','<script type="application/ld+json">'+json.dumps(g,ensure_ascii=False)+'</script></head>');p.write_text(s)
(ROOT/'docs/brain/evidence/salon-product/seo-20260909/entry-data.json').write_text(json.dumps(DATA,ensure_ascii=False,indent=2))
