(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).toLocaleLowerCase('ru').replace(/ё/g,'е');
const words=s=>norm(String(s).slice(0,3000)).match(/[\p{L}\p{N}]+/gu)||[];
const groups=[['диплом','дипломная','дипломной','диплома','вкр'],['курсовая','курсовой','курсовую','курсовые','курсовым'],['научрук','научрука','руководитель','руководителя'],['источники','источников','литература','литературы','библиография'],['правки','доработка','доработку','редактура','редактуры'],['цена','цены','стоимость','стоит'],['практика','практике','практики','практику']];
function distance(a,b){if(Math.abs(a.length-b.length)>2)return 3;let prev=Array.from({length:b.length+1},(_,i)=>i),older;for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++){next[j]=Math.min(next[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));if(i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])next[j]=Math.min(next[j],older[j-2]+1);}older=prev;prev=next;}return prev[b.length];}
function tokenScore(q,w){if(w===q)return 0;if(q.length>=3&&w.startsWith(q))return 1;const group=groups.find(g=>g.includes(q));if(group?.includes(w))return 2;if(q.length>=4&&w.length>=4&&distance(q,w)<=(q.length>=8?2:1))return 3;if(q.length>=4&&groups.some(g=>g.includes(w)&&g.some(alias=>distance(q,alias)<=1)))return 4;return Infinity;}
function match(text,query){const qs=words(String(query).slice(0,160)).slice(0,12),ws=words(text);if(!qs.length)return {score:0,matched:0,total:0};const scores=qs.map(q=>Math.min(...ws.map(w=>tokenScore(q,w))));return {score:scores.reduce((a,b)=>a+b,0),matched:scores.filter(Number.isFinite).length,total:qs.length};}
function highlight(text,query){const qs=words(query).slice(0,12);return String(text).split(/([\p{L}\p{N}]+)/gu).map(t=>qs.some(q=>Number.isFinite(tokenScore(q,norm(t))))?'<mark>'+esc(t)+'</mark>':esc(t)).join('');}
function art(kind){const common='<path d="M37 17h49l18 18v64H37z" fill="var(--sx-paper)"/><path d="M37 17h49l18 18v64H37zM86 17v19h18"/>';const detail=kind==='saved'?'<path d="M64 17v40l11-8 11 8V17" fill="var(--sx-tint)"/><path d="M49 73h42M49 82h27M27 30v79h65"/>':kind==='lost'?'<path d="m38 66 17-8 18 13 17-8 14 6M52 40h18M52 48h27"/><path d="m112 75 9 9m0-9-9 9M21 65h7M24 62v7"/>':'<path d="M49 40h30M49 50h22M49 60h13"/><circle cx="89" cy="80" r="19" fill="var(--sx-tint)"/><path d="m103 94 18 18M81 80h16"/>';return '<svg class="sx-art" viewBox="0 0 144 124" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'+common+detail+'<path d="M26 116h90" opacity=".3"/></svg>';}
let toastTimer;
function notice(text){const host=$$('dialog[open]').at(-1)||document.body;let el=host.querySelector('.sx-notice');if(!el){el=document.createElement('p');el.className='sx-notice'+(host===document.body?'':' sx-modal-notice');el.setAttribute('role','status');host.append(el);}el.textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.textContent='',4200);}
function button(text,cls){const b=document.createElement('button');b.type='button';b.className=cls||'sx-button';b.textContent=text;return b;}
function sheet(title,content,trigger,wide=false){const d=document.createElement('dialog');d.className='sx-dialog'+(wide?' sx-wide':'');d.setAttribute('aria-label',title);const head=document.createElement('div');head.className='sx-dialog-head';const h=document.createElement('h2');h.textContent=title;const close=button('Закрыть ×');close.setAttribute('aria-label','Закрыть: '+title);head.append(h,close);d.append(head,content);document.body.append(d);const pos={x:scrollX,y:scrollY};let after,done=false;function finish(){if(done)return;done=true;d.remove();if(!$('.sx-dialog[open]'))document.documentElement.classList.remove('sx-modal-open');scrollTo({left:pos.x,top:pos.y,behavior:'instant'});if(trigger?.isConnected)trigger.focus({preventScroll:true});after?.();}function dismiss(fn){after=fn;if(d.open)d.close();finish();}close.onclick=()=>dismiss();d.addEventListener('cancel',e=>{e.preventDefault();e.stopPropagation();dismiss();});d.addEventListener('close',finish,{once:true});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dismiss();}});d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=Array.from(d.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')).filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}});d.showModal();document.documentElement.classList.add('sx-modal-open');close.focus({preventScroll:true});return {dialog:d,close:dismiss};}
function fallback(text,trigger,isURL){const content=document.createElement('div');content.className='sx-copy-fallback';const label=document.createElement('label');label.textContent=isURL?'Скопируй ссылку из поля':'Выделенный пример можно скопировать вручную';const input=document.createElement('textarea');input.readOnly=true;input.value=text;input.setAttribute('aria-label',isURL?'Ссылка для копирования':'Пример для копирования');label.append(input);content.append(label);sheet(isURL?'Ссылка готова':'Пример готов',content,trigger);input.focus({preventScroll:true});input.select();}
async function copy(text,trigger,isURL=false){try{await navigator.clipboard.writeText(text);notice(isURL?'Ссылка скопирована':'Пример скопирован');}catch(_){if(trigger?.isConnected&&trigger.getClientRects().length)fallback(text,trigger,isURL);}}
async function share(url,title,trigger){if(trigger.dataset.sxBusy)return;trigger.dataset.sxBusy='1';try{if(typeof navigator.share==='function'){try{await navigator.share({url,title});return;}catch(e){if(e.name==='AbortError')return;}}await copy(url,trigger,true);}finally{delete trigger.dataset.sxBusy;}}
window.SalonReading={match,highlight,art,share};

function init(){
 if(performance.getEntriesByType('navigation')[0]?.type!=='back_forward')document.documentElement.classList.add('sx-arrive');
 const reader=$('[data-guide-reader]'),article=reader?.querySelector('article.doc');
 if(article){
  const headings=Array.from(article.querySelectorAll('h2')),title=article.querySelector('h1').textContent;
  const route=reader.dataset.guideId;
  // Route is a build-time public guide ID, never the current query or arbitrary URL.
  const url=id=>'https://akademsalon.ru/'+route+(id?'#'+encodeURIComponent(id):'');
  const oldCopy=$('[data-reader-copy]');oldCopy.textContent='Поделиться ↗';oldCopy.onclick=()=>share(url(headings.some(h=>h.id===location.hash.slice(1))?location.hash.slice(1):''),title,oldCopy);
  const sections=button('Разделы ↑','sx-button sx-contents');sections.setAttribute('aria-haspopup','dialog');reader.append(sections);
  function contents(trigger){const nav=document.createElement('nav');nav.className='sx-contents-list';nav.setAttribute('aria-label','Содержание статьи');const modal=sheet('В этом разборе',nav,trigger);headings.forEach(h=>{const a=document.createElement('a');a.href='#'+h.id;a.textContent=h.textContent;const active=$('[data-reader-toc] [aria-current="location"]');if(active?.hash==='#'+h.id)a.setAttribute('aria-current','location');a.onclick=e=>{e.preventDefault();modal.close(()=>{history.pushState(null,'',location.pathname+location.search+'#'+h.id);h.tabIndex=-1;h.focus({preventScroll:true});h.scrollIntoView({block:'start',behavior:'instant'});});};nav.append(a);});}
  sections.onclick=()=>contents(sections);
  const bar=document.createElement('div');bar.className='sx-focus-bar';bar.hidden=true;const caption=document.createElement('span');caption.textContent='Только чтение';const barSections=button('Разделы'),exit=button('Вернуть обычный вид ×');bar.append(caption,barSections,exit);document.body.append(bar);barSections.onclick=()=>contents(barSections);
  const enter=button('Только читать','sx-button sx-focus-enter');enter.setAttribute('aria-pressed','false');$('.lr-reader-actions').append(enter);
  function toggle(on){const candidates=Array.from(article.querySelectorAll('h1,h2,h3,p,li,table'));const anchor=candidates.find(el=>el.getBoundingClientRect().bottom>110)||article;const before=anchor.getBoundingClientRect();const fraction=before.top<110?Math.min(1,(110-before.top)/before.height):0;const at=before.top<110?110:before.top;document.documentElement.classList.toggle('sx-focus',on);bar.hidden=!on;enter.setAttribute('aria-pressed',String(on));const after=anchor.getBoundingClientRect();scrollBy({top:after.top+after.height*fraction-at,behavior:'instant'});(on?exit:enter).focus({preventScroll:true});}
  enter.onclick=()=>toggle(true);exit.onclick=()=>toggle(false);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.documentElement.classList.contains('sx-focus')&&!$('dialog[open]')&&!e.defaultPrevented){e.preventDefault();toggle(false);}});
  headings.forEach(h=>{const wrap=document.createElement('div');wrap.className='sx-section-share';const b=button('Ссылка на раздел ↗');b.setAttribute('aria-label','Поделиться разделом: '+h.textContent);b.onclick=()=>share(url(h.id),h.textContent,b);wrap.append(b);h.after(wrap);});
  article.querySelectorAll('[data-sx-copy]').forEach(block=>{const b=button('Скопировать пример','sx-button sx-example-copy');b.setAttribute('aria-label','Скопировать пример: '+block.dataset.sxCopy);b.onclick=()=>copy(block.innerText,b);block.after(b);block.classList.add('sx-example');});
  article.querySelectorAll('.lr-table-scroll').forEach((wrap,i)=>{const open=button('Таблица на весь экран ↗','sx-button sx-table-open');open.setAttribute('aria-haspopup','dialog');wrap.after(open);open.onclick=()=>{const area=document.createElement('div');area.className='sx-table-area';area.tabIndex=0;area.setAttribute('role','region');area.setAttribute('aria-label','Таблица, можно прокрутить');const clone=wrap.querySelector('table').cloneNode(true);clone.removeAttribute('id');clone.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));clone.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=true);clone.querySelectorAll('a').forEach(e=>e.removeAttribute('href'));const hint=document.createElement('p');hint.className='sx-table-hint';hint.textContent='Если таблица шире экрана, прокручивай её в сторону →';area.append(hint,clone);sheet(clone.querySelector('caption')?.textContent||'Таблица '+(i+1),area,open,true);};});
  const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.target===article)sections.hidden=!e.isIntersecting;},{threshold:0});observer.observe(article);
  function directSection(){const h=headings.find(h=>'#'+h.id===location.hash);if(h){h.tabIndex=-1;h.focus({preventScroll:true});h.scrollIntoView({block:'start',behavior:'instant'});}}
  directSection();window.addEventListener('hashchange',directSection);
 }
 const empty=$('[data-library-empty]');if(empty){const drawing=document.createElement('div');drawing.className='sx-empty-art';empty.prepend(drawing);const update=()=>{const saved=$('[data-library-saved]')?.getAttribute('aria-pressed')==='true';drawing.innerHTML=art(saved?'saved':'search');};update();new MutationObserver(update).observe(empty,{attributes:true,attributeFilter:['hidden']});const saved=$('[data-library-saved]');if(saved)new MutationObserver(update).observe(saved,{attributes:true,attributeFilter:['aria-pressed']});}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
