// Real browser, exact candidate, synthetic API only. No production mutations.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const guide='/guide-kursovaya-za-nedelyu.html';
async function setup(opts={}){const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(()=>{const t=Date.now();try{localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')}catch(_){}});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready)};
async function physical(page,selector){const b=await page.locator(selector).boundingBox();assert(b&&b.y>=0&&b.y+b.height<=page.viewportSize().height,'visible control '+selector);await page.mouse.click(b.x+b.width/2,b.y+b.height/2)}
async function settings(page){await physical(page,'.sh-menu>summary');await page.locator('.se-settings>summary').click();}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n)}
const bib='/guide-spisok-literatury.html';
async function stubShare(page,mode='copy'){await page.evaluate(mode=>{window.__shares=[];window.__copies=[];Object.defineProperty(navigator,'share',{configurable:true,value:mode==='native'?async d=>window.__shares.push(d):mode==='abort'?async()=>{throw new DOMException('cancel','AbortError')}:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(mode==='denied')throw new Error('blocked');window.__copies.push(text)}}});},mode);}
try {
 await test('safety-dialog-tab-loop-and-native-navigation',async({page})=>{
 await goto(page,bib);await page.locator('.sx-table-open').click();const close=page.locator('.sx-dialog-head button'),area=page.locator('.sx-table-area');await close.focus();await page.keyboard.press('Shift+Tab');assert(await area.evaluate(e=>e===document.activeElement));await page.keyboard.press('Tab');assert(await close.evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');await stubShare(page,'denied');await page.locator('.sx-example-copy').first().click();await page.keyboard.press('Tab');assert(await page.locator('.sx-dialog-head button').evaluate(e=>e===document.activeElement));await page.keyboard.press('Shift+Tab');assert(await page.locator('.sx-dialog textarea').evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');
 await goto(page,'/');const normal=await page.locator('main').evaluate(e=>getComputedStyle(e).animationName);assert.equal(normal,'sx-page-arrive');await physical(page,'.sh-menu>summary');assert(await page.locator('.sh-dialog').evaluate(e=>e.open));await page.keyboard.press('Escape');await page.evaluate(()=>document.documentElement.dataset.calm='1');assert.equal(await page.locator('main').evaluate(e=>getComputedStyle(e).animationName),'none');await page.evaluate(()=>{delete document.documentElement.dataset.calm;document.documentElement.dataset.motion='off'});assert.equal(await page.locator('main').evaluate(e=>getComputedStyle(e).animationName),'none');
 await goto(page,bib);await page.goBack();await page.waitForLoadState('load');assert(await page.locator('html').evaluate(e=>!e.classList.contains('sx-arrive')));await physical(page,'.sh-menu>summary');assert(await page.locator('.sh-dialog').evaluate(e=>e.open));
 },{width:390});
 await test('safety-motion-reduce-and-no-snapshot-css',async({page})=>{await goto(page,'/');assert.equal(await page.locator('main').evaluate(e=>getComputedStyle(e).animationName),'none');const css=fs.readFileSync(path.join(root,'assets/css/salon-reading.css'),'utf8');assert(!css.includes('@view-transition'));assert(!css.includes('::view-transition'));},{width:390,reduced:true});
} finally {await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source,root,results},null,2));console.log(JSON.stringify(results));}
