// Real browser, exact candidate, synthetic API only. No production mutations.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const guide='/guide-kursovaya-za-nedelyu.html';
async function setup(opts={}){const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(()=>{const t=Date.now();try{localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')}catch(_){}});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready)};
async function physical(page,selector){const b=await page.locator(selector).boundingBox();assert(b&&b.y>=0&&b.y+b.height<=page.viewportSize().height,'visible control '+selector);await page.mouse.click(b.x+b.width/2,b.y+b.height/2)}
async function settings(page){await physical(page,'.sh-menu>summary');await page.locator('.se-settings>summary').click();}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n)}
const bib='/guide-spisok-literatury.html';
async function stubShare(page,mode='copy'){await page.evaluate(mode=>{window.__shares=[];window.__copies=[];Object.defineProperty(navigator,'share',{configurable:true,value:mode==='native'?async d=>window.__shares.push(d):mode==='abort'?async()=>{throw new DOMException('cancel','AbortError')}:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(mode==='denied')throw new Error('blocked');window.__copies.push(text)}}});},mode);}
try {
 await test('safety-pdf-back-forward-valid-and-base',async({page})=>{
 await goto(page,'/samples.html');await page.evaluate(()=>location.hash='#pdf=comparison&page=3');await readyPDF(page,3);await page.goBack();await page.waitForFunction(()=>location.hash==='');await page.waitForFunction(()=>!document.querySelector('#pdf-reader').open);assert(await page.locator('#pdf-share').isDisabled());await page.goForward();await readyPDF(page,3);await stubShare(page);await page.locator('#pdf-share').click();assert.equal((await page.evaluate(()=>__copies))[0],'https://akademsalon.ru/samples.html#pdf=comparison&page=3');
 await page.evaluate(()=>location.hash='#pdf=referat&page=2');await readyPDF(page,2);await page.goBack();await readyPDF(page,3);await page.goForward();await readyPDF(page,2);await stubShare(page);await page.locator('#pdf-share').click();assert.equal((await page.evaluate(()=>__copies))[0],'https://akademsalon.ru/samples.html#pdf=referat&page=2');await page.evaluate(()=>location.hash='#some-normal-section');await page.waitForFunction(()=>!document.querySelector('#pdf-reader').open);assert.equal(await page.evaluate(()=>location.hash),'#some-normal-section');
 });
 await test('safety-pdf-normal-card-open-survives-unrelated-hash',async({page})=>{
 await goto(page,'/samples.html');await page.locator('.document-open').click();await readyPDF(page,1);await page.evaluate(()=>location.hash='#some-normal-section');assert(await page.locator('#pdf-reader').evaluate(e=>e.open));await page.locator('#pdf-close').click();await page.waitForFunction(()=>!document.querySelector('#pdf-reader').open);assert.equal(await page.evaluate(()=>location.hash),'#some-normal-section');
 });
} finally {await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source,root,results},null,2));console.log(JSON.stringify(results));}
