// Real browser, exact candidate, synthetic API only. No production mutations.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const guide='/guide-kursovaya-za-nedelyu.html';
async function setup(opts={}){const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(()=>{const t=Date.now();try{localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')}catch(_){}});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready)};
async function physical(page,selector){const b=await page.locator(selector).boundingBox();assert(b&&b.y>=0&&b.y+b.height<=page.viewportSize().height,'visible control '+selector);await page.mouse.click(b.x+b.width/2,b.y+b.height/2)}
async function settings(page){await physical(page,'.sh-menu>summary');await page.locator('.se-settings>summary').click();}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n)}
const bib='/guide-spisok-literatury.html';
async function stubShare(page,mode='copy'){await page.evaluate(mode=>{window.__shares=[];window.__copies=[];Object.defineProperty(navigator,'share',{configurable:true,value:mode==='native'?async d=>window.__shares.push(d):mode==='abort'?async()=>{throw new DOMException('cancel','AbortError')}:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(mode==='denied')throw new Error('blocked');window.__copies.push(text)}}});},mode);}
try {
 await test('safety-search-corpus-and-storage',async({page})=>{
  await goto(page,'/');await physical(page,'.sh-quick-search');
  const cases={'курсовя':'kursovaya','научрук':'rukovod','диплом психологии':'diplomnaya-po-psihologii','ё':'','<svg/onload=alert(1)>':''};
  const samples=[];for(const [q,want] of Object.entries(cases)){await page.locator('#experience-search-input').fill(q);const a=await page.locator('.experience-search nav a').evaluateAll(es=>es.map(e=>({href:e.getAttribute('href'),text:e.textContent})));if(want)assert(a.some(x=>x.href.includes(want)||x.text.includes(want)),q);assert.equal(a.length,new Set(a.map(x=>x.href)).size);samples.push({q,a});}
  await page.locator('#experience-search-input').fill('private-SYNTHETIC-LOOKUP-4829');
  const storage=await page.evaluate(()=>[...Object.entries(localStorage),...Object.entries(sessionStorage)]);assert(!JSON.stringify(storage).includes('private-SYNTHETIC-LOOKUP-4829'));
  const perf=await page.evaluate(()=>{const rows=['курсовя '.repeat(1000),'я'.repeat(10000),'<img onerror=alert(1)>','научрук диплом литературы'];const start=performance.now();for(let n=0;n<100;n++)for(const q of rows)SalonReading.match('Курсовая работа по психологии и введение к ВКР',q);return performance.now()-start});assert(perf<3000);fs.writeFileSync(path.join(out,'search-details.json'),JSON.stringify({samples,storageKeys:storage.map(x=>x[0]),perf},null,2));
 });
 await test('safety-pdf-bookmark-direct-fallback',async({page})=>{
  await goto(page,'/samples.html');await page.evaluate(()=>SalonReturn.pdfSave('comparison',8,'manual',2.3));await goto(page,'/samples.html?private=SYNTHETIC#pdf=comparison&page=3');await readyPDF(page,3);assert.equal(await page.locator('#pdf-fit').textContent(),'По ширине');
  await stubShare(page,'denied');await page.locator('#pdf-share').click();assert.equal(await page.locator('.sx-dialog textarea').inputValue(),'https://akademsalon.ru/samples.html#pdf=comparison&page=3');await page.keyboard.press('Escape');assert(await page.locator('#pdf-share').evaluate(e=>e===document.activeElement));assert(await page.locator('#pdf-reader').evaluate(e=>e.open));
  await stubShare(page,'abort');await page.locator('#pdf-share').click();assert.equal(await page.locator('.sx-dialog').count(),0);assert.deepEqual(await page.evaluate(()=>__copies),[]);
  await page.locator('#pdf-close').click();await page.waitForFunction(()=>location.hash==='');await page.locator('.document-open').click();await readyPDF(page,3);
 });
 await test('safety-pdf-rapid-paint-shares-latest',async({page})=>{
  await goto(page,'/samples.html#pdf=comparison&page=1');await readyPDF(page,1);await stubShare(page);
  await page.evaluate(async()=>{const lib=await import('/assets/vendor/pdfjs/pdf.min.mjs');const orig=lib.TextLayer.prototype.render;window.__releasePaint=null;window.__enteredPaint=0;lib.TextLayer.prototype.render=async function(...args){const value=await orig.apply(this,args);window.__enteredPaint++;await new Promise(r=>{window.__releasePaint=r});return value;};});
  await page.locator('#pdf-next').click();await page.waitForFunction(()=>__enteredPaint===1);assert(await page.locator('#pdf-share').isDisabled());
  await page.evaluate(()=>{window.__oldRelease=__releasePaint;document.querySelector('#pdf-next').click()});await page.waitForFunction(()=>__enteredPaint===2);await page.evaluate(()=>__oldRelease());assert(await page.locator('#pdf-share').isDisabled());await page.evaluate(()=>__releasePaint());await readyPDF(page,3);
  await page.locator('#pdf-share').click();assert.equal((await page.evaluate(()=>__copies))[0],'https://akademsalon.ru/samples.html#pdf=comparison&page=3');
 });
 await test('safety-pdf-close-during-load-and-switch-document',async({page})=>{
  await goto(page,'/samples.html');let release;const gate=new Promise(r=>release=r);await page.route('**/comparison.pdf*',async r=>{await gate;await r.fallback()});await page.evaluate(()=>location.hash='#pdf=comparison&page=3');await page.waitForSelector('#pdf-loading',{state:'visible'});assert(await page.locator('#pdf-share').isDisabled());await page.locator('#pdf-close').click();await page.evaluate(()=>location.hash='#pdf=referat&page=2');release();await readyPDF(page,2);await stubShare(page);await page.locator('#pdf-share').click();assert.equal((await page.evaluate(()=>__copies))[0],'https://akademsalon.ru/samples.html#pdf=referat&page=2');assert(!(await page.locator('#pdf-title').textContent()).includes('Сравнительный'));
 });
 await test('safety-pdf-invalid-hash-storage',async({page})=>{
  const bad=['#pdf=__proto__&page=1','#pdf=comparison&page=-1','#pdf=comparison&page=01','#pdf=comparison&page=1e1','#pdf=comparison&page=Infinity','#pdf=comparison&page=10000','#pdf=comparison&page=1&private=SYNTHETIC','#pdf=%63omparison&page=1','#pdf=../../x&page=1','#pdf=comparison&page=NaN'];for(const hash of bad){await goto(page,'/samples.html'+hash);assert(await page.locator('#pdf-reader').evaluate(e=>!e.open),hash);assert(await page.locator('#pdf-share').isDisabled());}const storage=await page.evaluate(()=>[...Object.entries(localStorage),...Object.entries(sessionStorage)]);assert(!JSON.stringify(storage).includes('SYNTHETIC'));
 });
 await test('safety-guide-copy-names-and-cancel',async({page})=>{
  await goto(page,bib+'?private=SYNTHETIC');const headings=await page.locator('article h2').allTextContents();assert(headings.every(x=>!x.includes('Ссылка на раздел')));await page.locator('.sx-focus-enter').click();await page.locator('.sx-focus-bar button').first().click();const labels=await page.locator('.sx-contents-list a').allTextContents();assert.deepEqual(labels,headings);await page.keyboard.press('Escape');await page.keyboard.press('Escape');await stubShare(page,'native');await page.locator('.sx-section-share button').nth(2).click();const share=(await page.evaluate(()=>__shares))[0];assert(!share.url.includes('?'));assert(!share.title.includes('Ссылка на раздел'));
 });
} finally {await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source,root,browser:'Chrome headless',network:'all routed locally; API synthetic',results},null,2));console.log(JSON.stringify(results));}
