// Real browser, exact candidate, synthetic API only. No production mutations.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
const guide='/guide-kursovaya-za-nedelyu.html';
async function setup(opts={}){const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(()=>{const t=Date.now();try{localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')}catch(_){}});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready)};
async function physical(page,selector){const b=await page.locator(selector).boundingBox();assert(b&&b.y>=0&&b.y+b.height<=page.viewportSize().height,'visible control '+selector);await page.mouse.click(b.x+b.width/2,b.y+b.height/2)}
async function settings(page){await physical(page,'.sh-menu>summary');await page.locator('.se-settings>summary').click();}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'});console.log('PASS',name)}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'-failure.png')}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n)}
const bib='/guide-spisok-literatury.html';
async function stubShare(page,mode='copy'){await page.evaluate(mode=>{window.__shares=[];window.__copies=[];Object.defineProperty(navigator,'share',{configurable:true,value:mode==='native'?async d=>window.__shares.push(d):mode==='abort'?async()=>{throw new DOMException('cancel','AbortError')}:undefined});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{if(mode==='denied')throw new Error('blocked');window.__copies.push(text)}}});},mode);}
try{
 await test('search-typos-aliases-ranking-safe',async({page})=>{await goto(page,'/');await physical(page,'.sh-quick-search');const input=page.locator('#experience-search-input');for(const q of ['курсовя','диплом','научрук','диплом психологии','источники','курсовая']){await input.fill(q);assert(await page.locator('.experience-search mark').count()>0,q);const links=await page.locator('.experience-search nav a').evaluateAll(es=>es.map(e=>e.getAttribute('href')));assert(links.length>0,q);assert.equal(links.length,new Set(links).size);if(q==='курсовая')assert.equal(links[0],'kursovaya-rabota.html');}await input.fill('<img src=x onerror=alert(1)>');assert.equal(await page.locator('.experience-search nav img').count(),0);assert(await page.locator('.sx-search-empty svg').isVisible());assert(await page.locator('.experience-search nav a').count()>=1);assert(await page.locator('.experience-search nav a').count()<=3);await input.fill('я'.repeat(10000));assert(await page.locator('.sx-search-empty').isVisible());await page.keyboard.press('Escape');assert(await page.locator('.sh-quick-search').evaluate(e=>e===document.activeElement));},{width:390});
 await test('library-search-and-empty-art',async({page})=>{await goto(page,'/knowledge.html');const input=page.locator('[data-library-search]');await input.fill('курсовя');assert(await page.locator('[data-library-card]:visible').count()>0);assert(await page.locator('[data-library-card]:visible mark').count()>0);await input.fill('абракадабра');assert(await page.locator('[data-library-empty] .sx-art').isVisible());await page.locator('[data-library-reset]').click();await page.locator('[data-library-saved]').click();assert(await page.locator('[data-library-empty] .sx-art').isVisible());await page.screenshot({path:path.join(out,'saved-empty.png')});},{width:390});
 await test('focus-reading-position-and-dialog-escape',async({page})=>{await goto(page,bib);await page.locator('.sx-focus-enter').click();assert(await page.locator('html').evaluate(e=>e.classList.contains('sx-focus')));assert(await page.locator('header.site-header').isHidden());assert(await page.locator('.sx-focus-bar').isVisible());await page.locator('article.doc h2').nth(3).evaluate(h=>scrollTo({top:scrollY+h.getBoundingClientRect().top-130,behavior:'instant'}));const top=await page.locator('article.doc h2').nth(3).evaluate(h=>h.getBoundingClientRect().top);await page.locator('.sx-focus-bar button').first().click();assert(await page.locator('.sx-dialog').isVisible());await page.keyboard.press('Escape');assert(await page.locator('.sx-focus-bar').isVisible());await page.keyboard.press('Escape');assert(await page.locator('.sx-focus-bar').isHidden());await page.waitForTimeout(80);assert.equal(await page.locator('.sx-dialog').count(),0);assert(Math.abs(await page.locator('article.doc h2').nth(3).evaluate(h=>h.getBoundingClientRect().top)-top)<3);assert(await page.locator('.sx-focus-enter').evaluate(e=>e===document.activeElement));},{width:390});
 await test('mobile-contents-navigate-focus',async({page})=>{await goto(page,bib);await page.locator('article.doc h2').nth(2).scrollIntoViewIfNeeded();await page.locator('.sx-contents').click();const link=page.locator('.sx-contents-list a').nth(4),hash=await link.getAttribute('href');await link.click();await page.waitForFunction(hash=>location.hash===hash,hash);assert(await page.locator(hash).evaluate(e=>e===document.activeElement));assert(await page.locator(hash).evaluate(e=>e.getBoundingClientRect().top>=65));assert.equal(await page.locator('.sx-dialog').count(),0);},{width:360});
 await test('table-dialog-preserves-source-and-focus',async({page})=>{await goto(page,bib);const source=await page.locator('article table').first().textContent(),btn=page.locator('.sx-table-open').first();await btn.scrollIntoViewIfNeeded();await page.locator('.lr-table-scroll').first().evaluate(e=>e.scrollLeft=80);const pos=await page.evaluate(()=>scrollY);await btn.click();assert.equal(await page.locator('.sx-dialog table').textContent(),source);assert.equal(await page.locator('article table').count(),1);assert(await page.locator('.sx-table-area').evaluate(e=>e.scrollWidth>e.clientWidth));await page.keyboard.press('Escape');assert(await btn.evaluate(e=>e===document.activeElement));assert(Math.abs(await page.evaluate(()=>scrollY)-pos)<3);},{width:390});
 await test('curated-example-copy-and-manual-fallback',async({page})=>{await goto(page,bib);await stubShare(page);const text=await page.locator('[data-sx-copy]').first().innerText();await page.locator('.sx-example-copy').first().click();assert.deepEqual(await page.evaluate(()=>__copies),[text]);await stubShare(page,'denied');await page.locator('.sx-example-copy').first().click();assert.equal(await page.locator('.sx-dialog textarea').inputValue(),text);await page.keyboard.press('Escape');assert(await page.locator('.sx-example-copy').first().evaluate(e=>e===document.activeElement));for(const route of ['/guide-titulnyj-list.html','/guide-vkr-struktura.html','/guide-prilozheniya-po-gost.html']){await goto(page,route);assert(await page.locator('.sx-example-copy').count()>0);}});
 await test('section-share-canonical-native-abort-and-roundtrip',async({page})=>{await goto(page,bib+'?private=SYNTHETIC');const h=page.locator('article.doc h2').nth(2),id=await h.getAttribute('id'),b=page.locator('.sx-section-share button').nth(2);await stubShare(page,'native');await b.click();assert.equal((await page.evaluate(()=>__shares))[0].url,'https://akademsalon.ru'+bib+'#'+id);await stubShare(page,'abort');await b.click();assert.deepEqual(await page.evaluate(()=>__copies),[]);assert.equal(await page.locator('.sx-dialog').count(),0);await stubShare(page,'denied');await b.click();assert.equal(await page.locator('.sx-dialog textarea').inputValue(),'https://akademsalon.ru'+bib+'#'+id);await page.keyboard.press('Escape');await goto(page,bib+'#'+id);assert(await page.locator('#'+id).evaluate(e=>e===document.activeElement));await page.waitForFunction(id=>document.getElementById(id).getBoundingClientRect().top>=65,id);},{width:390});
 await test('pdf-direct-link-success-only-and-roundtrip',async({page})=>{await goto(page,'/samples.html?private=SYNTHETIC#pdf=comparison&page=3');await readyPDF(page,3);await stubShare(page);await page.locator('#pdf-share').click();assert.equal((await page.evaluate(()=>__copies))[0],'https://akademsalon.ru/samples.html#pdf=comparison&page=3');await page.locator('#pdf-close').click();await page.waitForFunction(()=>location.hash==='');await goto(page,'/samples.html#pdf=comparison&page=2');await readyPDF(page,2);await page.locator('#pdf-close').click();await page.locator('.document-open').click();await readyPDF(page,2);await page.locator('#pdf-close').click();for(const hash of ['#pdf=comparison&page=0','#pdf=comparison&page=11','#pdf=unknown&page=1','#pdf=comparison&page=1&page=2','#pdf=comparison&page=1.5']){await goto(page,'/samples.html'+hash);assert(await page.locator('#pdf-reader').evaluate(e=>!e.open));}},{width:390});
 await test('pdf-browser-back-and-forward',async({page})=>{await goto(page,'/samples.html');await page.evaluate(()=>location.hash='pdf=comparison&page=3');await readyPDF(page,3);await page.goBack();await page.waitForFunction(()=>!document.querySelector('#pdf-reader').open);assert.equal(new URL(page.url()).hash,'');await page.goForward();await readyPDF(page,3);await page.evaluate(()=>location.hash='pdf=risk&page=4');await readyPDF(page,4);await page.goBack();await readyPDF(page,3);assert.match(await page.locator('#pdf-title').textContent(),/Сравнительный/);},{width:390});
 await test('pdf-loading-error-retry-share-disabled',async({page})=>{await goto(page,'/samples.html');let release;const gate=new Promise(r=>release=r);await page.route('**/*.pdf*',async r=>{await gate;await r.fallback()});await page.locator('.document-open').click();await page.waitForSelector('#pdf-loading',{state:'visible'});assert(await page.locator('#pdf-share').isDisabled());release();await readyPDF(page,1);assert(await page.locator('#pdf-share').isEnabled());await page.locator('#pdf-next').click();assert(await page.locator('#pdf-share').isDisabled());await readyPDF(page,2);await page.locator('#pdf-close').click();await page.unroute('**/*.pdf*');await page.route('**/*.pdf*',r=>r.fulfill({status:503,body:'Unavailable'}));await page.locator('.document-open').click();await page.waitForFunction(()=>!document.querySelector('#pdf-error').hidden);assert(await page.locator('#pdf-share').isDisabled());await page.unroute('**/*.pdf*');await page.locator('#pdf-retry').click();await readyPDF(page,2);assert(await page.locator('#pdf-share').isEnabled());},{width:390});
 for(const width of [360,390,768,1024,1440])for(const theme of ['light','dark'])await test('visual-'+width+'-'+theme,async({page})=>{await goto(page,bib);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));for(const selector of ['.sx-focus-enter','.sx-example-copy','.sx-table-open']){const box=await page.locator(selector).first().boundingBox();assert(box.width>=44&&box.height>=44);}await page.locator('.sx-focus-enter').click();await page.screenshot({path:path.join(out,'focus-'+width+'-'+theme+'.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.keyboard.press('Escape');await page.locator('.sx-table-open').first().click();await page.screenshot({path:path.join(out,'table-'+width+'-'+theme+'.png')});assert(await page.locator('.sx-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.keyboard.press('Escape');await goto(page,'/samples.html#pdf=comparison&page=1');await readyPDF(page,1);assert(await page.locator('#pdf-reader').evaluate(e=>e.scrollWidth<=e.clientWidth+1));const b=await page.locator('#pdf-share').boundingBox();assert(b.x>=0&&b.x+b.width<=width);await page.waitForTimeout(220);await page.screenshot({path:path.join(out,'pdf-'+width+'-'+theme+'.png')});await page.locator('#pdf-close').click();await goto(page,'/404.html');assert(await page.locator('.sx-recovery-art .sx-art').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'404-'+width+'-'+theme+'.png')});},{width,theme});
 await test('motion-guard-and-private-exclusion',async({page})=>{await goto(page,'/');const css=fs.readFileSync(path.join(root,'assets/css/salon-reading.css'),'utf8');assert(css.includes('sx-page-arrive'));assert(!css.includes('@view-transition'));assert.equal(await page.locator('main').evaluate(e=>e.getAnimations().length),0);await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{document.documentElement.dataset.calm='1';document.documentElement.classList.add('sx-arrive');});assert.equal(await page.locator('main').evaluate(e=>e.getAnimations().length),0);await goto(page,'/dashboard.html');assert.equal(await page.locator('script[src*="salon-reading.js"]').count(),0);assert.equal(await page.locator('link[href*="salon-reading.css"]').count(),0);},{width:390,reduced:true});

}finally{await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source,root,browser:'Chrome headless',network:'all routed, no production requests',results},null,2));console.log(JSON.stringify(results));}
