"""Rebuild learning presentation from the source-bound pre-redesign articles."""
from pathlib import Path
import re, json, html, subprocess
ROOT = Path(__file__).resolve().parents[1]
BASE = '67b9b1e494e9e21d954a2b6eb1b357c91c151853'
def old(name): return subprocess.check_output(['git','show',BASE+':'+name],cwd=ROOT,text=True)
def plain(s): return ' '.join(re.sub('<[^>]+>',' ',html.unescape(s)).split())
shell=old('priyomnaya.html')
header=shell[shell.index('<body'):shell.index('<main')]
header=re.sub(r'<body[^>]*>','<body class="salon-direct salon-experience concept-shell salon-learning">',header)
footer=re.search(r'<footer\b.*?</footer>',shell,re.S).group()
styles=''.join('<link rel="stylesheet" href="'+x+'">' for x in ['assets/fonts/fonts.css','assets/css/salon-direct.css','assets/css/salon-experience.css','assets/css/salon-home.css','assets/css/salon-support.css','assets/css/salon-library.css?v=20260909learning1'])
scripts=''.join('<script src="'+x+'"></script>' for x in ['assets/js/configurator-nav-guard.js','assets/js/app.js','assets/js/analytics-attribution-v2.js','assets/js/analytics-v2.js','assets/js/salon-products.js','assets/js/salon-experience.js','assets/js/salon-shell.js','assets/js/salon-library.js?v=20260909learning1'])
def write(name,main,tool=False,extra=''):
 s=old(name);head=s[:s.index('</head>')]
 head=re.sub(r'<link\b[^>]*rel="stylesheet"[^>]*>','',head)
 if 'salon_theme' not in head:head+='<script>try{if(localStorage.getItem("salon_theme")==="dark"||(!localStorage.getItem("salon_theme")&&matchMedia("(prefers-color-scheme:dark)").matches))document.documentElement.dataset.theme="dark"}catch(e){}</script>'
 schemas=''.join(re.findall(r'<script type="application/ld\+json">.*?</script>',s,re.S))
 # Personal search terms from historic bookmarks are consumed before analytics loads.
 early='<script>if(["/knowledge","/knowledge.html"].includes(location.pathname)){const u=new URL(location.href);window.salonLibraryInitialQuery=(u.searchParams.get("q")||"").slice(0,160);u.searchParams.delete("q");history.replaceState(history.state,"",u.pathname+u.search+u.hash)}</script>'
 extras='<link rel="stylesheet" href="assets/css/salon-tools.css?v=20260909learning1">' if tool else ''
 js=scripts+('<script src="assets/js/salon-tools.js?v=20260909learning1"></script>' if tool else '')+extra
 (ROOT/name).write_text(head+styles+extras+early+'</head>'+header+main+schemas+footer+js+'</body></html>')
kb=old('knowledge.html');entries=[]
for card in re.findall(r'<article class="article-card".*?</article>',kb,re.S):
 def attr(k): return html.unescape(re.search(k+r'="([^"]*)"',card).group(1))
 entries.append({'path':re.search(r'href="(guide-[^"]+)"',card).group(1),'title':attr('data-title'),'summary':attr('data-summary'),'topic':attr('data-topic'),'time':re.search(r'<span>([0-9]+ минут)</span>',card).group(1)})
nav='<nav class="lr-subnav" aria-label="Полезное"><a href="knowledge.html">Библиотека</a><a href="tools.html">Инструменты</a><a href="samples.html">Примеры работ</a></nav>'
topics=[('all','Все материалы'),('start','Начало'),('methodology','Исследование'),('sources','Источники'),('formatting','Оформление'),('practice','Практика'),('defense','Защита'),('publication','Статья'),('price','Цены')]
cards=''.join('<article class="lr-card" data-library-card data-topic="'+e['topic']+'" data-path="'+e['path']+'"><a href="'+e['path']+'"><span class="lr-card-meta">'+dict(topics)[e['topic'].split()[0]]+' · '+e['time']+'</span><h2>'+html.escape(e['title'])+'</h2><p>'+html.escape(e['summary'])+'</p><span class="lr-read">Открыть разбор <span aria-hidden="true">↗</span></span></a><button class="lr-save" type="button" data-save="'+e['path']+'" aria-pressed="false" aria-label="Сохранить: '+html.escape(e['title'],quote=True)+'">♡</button></article>' for e in entries)
main='<main class="lr-main" id="main" data-library>'+nav+'''<header class="lr-hero"><div><p class="lr-kicker">ЧИТАЛЬНЫЙ ЗАЛ</p><h1>Есть вопрос.<br><em>Есть с чего начать.</em></h1><p>Короткий путь к нужному разбору. От первой темы до последнего слайда.</p></div><a class="lr-tool-invite" href="tools.html"><span aria-hidden="true">Аа ↗</span><strong>Попробуй на своём тексте</strong><span>Проверки, паспорт темы и список правок. Бесплатно.</span></a></header><section class="lr-catalog" aria-label="Найти материал"><div class="lr-search-row"><label class="lr-search"><span aria-hidden="true">⌕</span><input type="search" data-library-search maxlength="160" aria-label="Найти в библиотеке" placeholder="Введение, дневник, речь…" autocomplete="off"><button type="button" data-library-clear aria-label="Очистить поиск" hidden>×</button></label><button type="button" class="lr-shelf-toggle" data-library-saved aria-pressed="false">♡ <span>Сохранённое</span> <b data-shelf-count>0</b></button></div><div class="lr-filters" role="group" aria-label="Тема материала">'''+''.join('<button type="button" data-library-topic="'+id+'" aria-pressed="'+str(id=='all').lower()+'">'+title+'</button>' for id,title in topics)+'''</div><div class="lr-results-line"><p data-library-status role="status"></p><span data-library-shelf-note hidden>На этом устройстве</span></div><div class="lr-card-grid">'''+cards+'''</div><div class="lr-empty" data-library-empty hidden><h2>Пока ничего.</h2><p data-library-empty-note>Попробуй другое слово или тему.</p><button class="lr-button" type="button" data-library-reset>Показать все материалы</button></div><button type="button" class="lr-more" data-library-more hidden>Ещё материалы ↓</button></section><aside class="lr-help"><div><h2>Нужен разбор именно твоей работы?</h2><p>Инструкция помогает разобраться. Задание и методичка помогут нам оценить твою задачу.</p></div><a class="lr-button" href="configurator.html">Обсудить задачу ↗</a></aside><p class="lr-status" data-learning-status role="status"></p></main>'''
write('knowledge.html',main)
# Articles remain byte-identical inside their new reading surface.
for e in entries:
 s=old(e['path']);article=re.search(r'<article class="doc">.*?</article>',s,re.S).group()
 main='<main id="main" class="lr-main lr-reader" data-guide-reader data-guide-id="'+e['path']+'">'+nav+'<div class="lr-reader-top"><a href="knowledge.html">← Все материалы</a><span>'+e['time']+'</span></div><div class="lr-reader-actions"><button type="button" data-save="'+e['path']+'" aria-pressed="false">♡ Сохранить</button><button type="button" data-reader-copy>Ссылка ↗</button><button type="button" data-reader-size aria-pressed="false">Аа · Крупнее</button><button type="button" data-reader-print>Печать</button></div><div class="lr-reading-layout"><aside class="lr-reading-nav"><details open><summary>В этом разборе</summary><nav aria-label="Содержание статьи" data-reader-toc></nav></details><div class="lr-reading-progress" aria-hidden="true"><i></i></div><a class="lr-related-tool" href="tools.html">Проверить свой материал ↗</a></aside>'+article+'</div><p class="lr-status" role="status" data-learning-status></p></main>'
 write(e['path'],main)
# Compact directory. Inputs and results live on the corresponding working route.
tools=[('check.html','Аа','Текст','Найди длинные фразы, тяжёлые обороты и повторяющиеся слова.','Фрагмент до 8 000 знаков'),('audit-temy-vkr.html','?','Тема','Уточни границы, исследовательский вопрос и доступные данные.','Тема и направление'),('proverka-istochnikov-vkr.html','[1]','Источники','Проверь поля списка. При желании сверь DOI с Crossref.','До 100 записей'),('dosie-nauchruka.html','✓','Замечания','Преврати комментарии в список задач и отметь готовое.','Замечания до 800 знаков')]
main='<main id="main" class="lr-main lt-main" data-tools-directory>'+nav+'<header class="lr-hero"><div><p class="lr-kicker">ТВОЙ РАБОЧИЙ СТОЛ</p><h1>Меньше догадок.<br><em>Больше ясности.</em></h1><p>Четыре небольших инструмента. Начни со своего материала, без регистрации.</p></div></header><div class="lt-directory">'+''.join('<a href="'+p+'"><span class="lt-symbol" aria-hidden="true">'+mark+'</span><div><h2>'+title+'</h2><p>'+text+'</p><small>'+note+'</small></div><b aria-hidden="true">↗</b></a>' for p,mark,title,text,note in tools)+'</div><aside class="lr-help"><div><h2>Текст остаётся в этой вкладке.</h2><p>Проверки выполняются в браузере. Только при отдельной сверке DOI идентификаторы отправляются в Crossref. Результат можно скопировать. В инструменте «Замечания» есть отдельная кнопка переноса в заявку.</p></div><a href="privacy.html">Подробнее о данных ↗</a></aside></main>'
write('tools.html',main,True)
for name,title,desc in [('check.html','Разложим текст.<br><em>По полочкам.</em>','Посмотри, какие фразы стоит перечитать. Проверка стиля не определяет авторство и не оценивает факты.'),('audit-temy-vkr.html','Хорошая тема.<br><em>С чёткими границами.</em>','Собери рабочий паспорт: вопрос, данные и результат, который сможешь проверить.'),('proverka-istochnikov-vkr.html','Источники.<br><em>Каждый на своём месте.</em>','Проверь основные поля. Сверка DOI доступна отдельно и не подтверждает содержание работы.'),('dosie-nauchruka.html','Из замечаний.<br><em>В понятные задачи.</em>','Разбей комментарии на отдельные правки. Отметь готовое и передай исходные замечания для оценки.')]:
 intro='<main id="main" class="lr-main lt-main" data-learning-tool="'+name.removesuffix('.html')+'">'+nav+'<a class="lt-back" href="tools.html">← Все инструменты</a><header class="lt-hero"><p class="lr-kicker">БЕСПЛАТНО · БЕЗ РЕГИСТРАЦИИ</p><h1>'+title+'</h1><p>'+desc+'</p></header>'
 if name=='check.html':
  oldmain=re.search(r'<article class="tool-guidance".*?</article>',old(name),re.S).group()
  content='''<div class="lt-workspace"><section class="lt-input"><div class="lt-panel-head"><label for="lt-text">Твой фрагмент</label><span data-tool-count>0 / 8 000</span></div><textarea id="lt-text" data-tool-input maxlength="8000" rows="11" placeholder="Вставь один или несколько абзацев"></textarea><div class="lt-actions"><button type="button" class="lr-button" data-tool-run>Посмотреть замечания</button><button type="button" data-tool-example>Пример</button><button type="button" data-tool-clear>Очистить</button></div><p class="lt-note">Только эта вкладка. Текст не сохраняется и не отправляется.</p></section><section class="lt-result" data-tool-result aria-label="Замечания к тексту"><div class="lt-empty"><span aria-hidden="true">Аа</span><h2>Посмотри на конкретные места.</h2><p>Нажми на замечание, чтобы выделить нужную фразу в исходном тексте.</p></div></section></div><details class="lt-explainer"><summary>Как пользоваться проверкой и где её границы</summary>'''+oldmain+'''</details>'''
 elif name=='audit-temy-vkr.html':
  content='''<div class="lt-workspace"><section class="lt-input"><label for="lt-text">Тема работы</label><textarea id="lt-text" data-tool-input maxlength="1000" rows="4" placeholder="Например: связь учебной мотивации и тревожности у студентов первого курса"></textarea><label for="lt-discipline">Направление</label><select id="lt-discipline"><option>Психология</option><option>Экономика</option><option>Юриспруденция</option><option>Педагогика</option><option>Менеджмент</option><option>Информатика</option><option>Другое</option></select><label for="lt-data">Какие данные уже доступны? <span class="lt-optional">Необязательно</span></label><input id="lt-data" maxlength="300" placeholder="Например: результаты опроса, отчётность за 3 года"><div class="lt-actions"><button type="button" class="lr-button" data-tool-run>Собрать паспорт</button><button type="button" data-tool-example>Пример</button><button type="button" data-tool-clear>Очистить</button></div><p class="lt-note">Паспорт остаётся в этой вкладке. Это подсказка, а не согласование темы.</p></section><section class="lt-result" data-tool-result aria-label="Паспорт темы"><div class="lt-empty"><span aria-hidden="true">?</span><h2>Четыре опоры темы.</h2><p>Исследовательское действие, границы, доступные данные и вопрос для проверки.</p></div></section></div>'''
 elif name=='proverka-istochnikov-vkr.html':
  content='''<div class="lt-workspace"><section class="lt-input"><div class="lt-panel-head"><label for="lt-text">Список источников</label><span>До 100 строк</span></div><textarea id="lt-text" data-tool-input maxlength="20000" rows="11" placeholder="Одна запись на строку"></textarea><div class="lt-actions"><button type="button" class="lr-button" data-tool-run>Проверить поля</button><button type="button" data-tool-example>Пример</button><button type="button" data-tool-clear>Очистить</button></div><p class="lt-note">Локальная проверка не обращается к внешним сервисам.</p></section><section class="lt-result" data-tool-result aria-label="Проверка источников"><div class="lt-empty"><span aria-hidden="true">[1]</span><h2>Сначала поля. Потом сверка.</h2><p>Год, автор или организация, дата обращения. DOI можно проверить отдельным нажатием.</p></div></section></div><details class="lt-explainer"><summary>Что подтверждает запись Crossref?</summary><p>Найденная запись подтверждает наличие метаданных в реестре. Сравни название, автора и год со своим списком. Это не подтверждение корректности цитаты. Отсутствие записи или сбой сети не доказывают, что источник вымышлен.</p><p>Для сверки в Crossref отправляются только найденные DOI, до 8 за запуск, без полного текста и списка литературы.</p></details>'''
 else:
  content='''<div class="lt-workspace"><section class="lt-input"><div class="lt-panel-head"><label for="lt-text">Замечания руководителя</label><span data-tool-count>0 / 800</span></div><textarea id="lt-text" data-tool-input data-remarks-handoff-text maxlength="800" rows="9" aria-describedby="remarksHandoffNote" placeholder="Каждое замечание с новой строки или через точку с запятой"></textarea><p class="lt-note" id="remarksHandoffNote">Для передачи в заявку нужно от 40 до 800 знаков. Не добавляй контакты и личные данные.</p><div class="lt-actions"><button type="button" class="lr-button" data-tool-run>Разобрать на задачи</button><button type="button" data-tool-example>Пример</button><button type="button" data-tool-clear>Очистить</button></div><p data-p15-notice role="status" hidden></p></section><section class="lt-result" data-tool-result aria-label="Список правок"><div class="lt-empty"><span aria-hidden="true">✓</span><h2>Одна правка. Один пункт.</h2><p>Отмечай готовое в этой вкладке. Исходные замечания сохранятся в поле целиком.</p></div></section></div><aside class="lr-help"><div><h2>Передать на оценку?</h2><p>В заявку попадёт весь исходный текст замечаний. Ты сможешь проверить его перед отправкой.</p></div><button type="button" class="lr-button" data-remarks-handoff-submit>Перенести замечания в заявку ↗</button></aside>'''
 main=intro+content+'<p class="lr-status" data-learning-status role="status"></p></main>'
 write(name,main,True,'<script src="assets/js/remarks-handoff.js?v=20260825rescue1"></script>' if name=='dosie-nauchruka.html' else '')
print('Rebuilt',len(entries)+6,'learning pages; article bodies preserved')
