// Real Chrome, all HTTP routed to the exact candidate. No production traffic.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import crypto from 'node:crypto';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),KEY='salon_return_v1',CAT='salon_catalog_return_v1',guide='/guide-kursovaya-za-nedelyu.html';
async function openMenu(page){const box=await page.locator('.sh-menu>summary').boundingBox();assert(box&&box.y>=0&&box.y+box.height<=page.viewportSize().height,'menu visible');await page.mouse.click(box.x+box.width/2,box.y+box.height/2)}
async function setup(opts={}){
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(({opts})=>{const t=Date.now();localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_theme',opts.theme||'light');localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')},{opts});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method(),body:r.postData()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}if(opts.failPDF&&u.pathname.endsWith('.pdf'))return route.fulfill({status:503,body:'Unavailable'});const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};
}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready);};
const stored=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)||'null'),KEY);
async function headingRead(page,index=3){await page.mouse.wheel(0,350);await page.locator('article.doc h2').nth(index).evaluate(h=>window.scrollTo({top:scrollY+h.getBoundingClientRect().top-140,behavior:'instant'}));await page.waitForTimeout(650);}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'.png'),fullPage:false}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n);}
try{
 await test('catalogue-back-forward-back',async({page})=>{
  await goto(page,'/services.html');await page.locator('[data-cat-filter="science"]').click();const card=page.locator('.cat-card[data-product="kandidat"]');await card.scrollIntoViewIfNeeded();await card.click();await page.locator('.cat-close').click();await page.waitForTimeout(250);const y=await page.evaluate(()=>scrollY);
  await openMenu(page);await page.locator('.sh-groups a[href="samples.html"]').click();await page.waitForLoadState('load');
  for(let i=0;i<2;i++){await page.goBack({waitUntil:'load'});await page.waitForTimeout(350);assert.equal(await page.locator('[data-cat-filter="science"]').getAttribute('aria-pressed'),'true');assert(Math.abs((await page.evaluate(()=>scrollY))-y)<15);if(i===0){await page.goForward({waitUntil:'load'});assert.equal(new URL(page.url()).pathname,'/samples.html');await page.locator('.document-open').waitFor();}}
 },{width:390,theme:'dark'});
}finally{await browser.close();fs.writeFileSync(path.join(out,'history-results.json'),JSON.stringify({source,root,browser:'Chrome',network:'all requests routed; no API writes',results},null,2));console.log(JSON.stringify(results))}
