// Actual public bytes, GET-only. API calls are intercepted; no orders, payments or analytics.
import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json'),{chromium}=require('playwright');
const output=path.resolve(process.argv[2]),manifest=JSON.parse(fs.readFileSync(process.argv[3])),release=process.argv[4];fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
const guide='/guide-kursovaya-za-nedelyu.html';
async function openMenu(page){const box=await page.locator('.sh-menu>summary').boundingBox();assert(box&&box.y>=0&&box.y+box.height<=page.viewportSize().height,'menu visible');await page.mouse.click(box.x+box.width/2,box.y+box.height/2)}
async function goto(page,url){assert.equal((await page.goto('https://akademsalon.ru'+url,{waitUntil:'load'})).status(),200);await page.evaluate(()=>document.fonts.ready)}
async function pdfReady(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden,n)}
try{for(const width of [390,1440])for(const theme of ['light','dark']){
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width,height:900},colorScheme:theme,reducedMotion:'reduce'}),blocked=[],errors=[];
 await context.addInitScript(theme=>{const t=Date.now();localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_theme',theme);localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')},theme);
 await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(q.method()!=='GET'||u.origin!=='https://akademsalon.ru'){blocked.push({method:q.method(),path:u.pathname});return r.abort()}if(u.pathname.startsWith('/api/')){blocked.push({method:q.method(),path:u.pathname});return r.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}return r.continue()});
 try{
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await goto(page,guide);await page.mouse.wheel(0,350);await page.locator('article.doc h2').nth(3).evaluate(h=>scrollTo({top:scrollY+h.getBoundingClientRect().top-140,behavior:'instant'}));await page.waitForTimeout(650);await goto(page,'/about.html');await goto(page,guide);assert(await page.locator('.sr-reading-return').isVisible());assert(await page.evaluate(()=>scrollY)<30);await page.screenshot({path:path.join(output,`live-article-${width}-${theme}.png`)});await page.getByRole('button',{name:'Продолжить чтение →',exact:true}).click();assert(await page.locator('article.doc h2').nth(3).evaluate(h=>h===document.activeElement));
  await goto(page,'/samples.html');await page.locator('.document-open').click();await pdfReady(page,1);await page.locator('#pdf-page-number').fill('4');await page.locator('#pdf-page-number').press('Enter');await pdfReady(page,4);await page.locator('#pdf-close').click();await page.reload({waitUntil:'load'});assert.match(await page.locator('.document-open').textContent(),/стр. 4/);await page.locator('.document-open').press('Enter');await pdfReady(page,4);await page.locator('#pdf-close').click();await page.locator('.sr-pdf-start').press('Enter');await pdfReady(page,1);await page.locator('#pdf-close').click();
  await goto(page,'/services.html');await page.locator('[data-cat-filter="student"]').click();const card=page.locator('.cat-card[data-product="diplom"]');await card.scrollIntoViewIfNeeded();await card.click();await page.locator('.cat-close').click();const before=await card.evaluate(e=>e.getBoundingClientRect().top);await openMenu(page);await page.locator('.sh-groups a[href="samples.html"]').click();await page.waitForLoadState('load');await page.goBack({waitUntil:'load'});await page.waitForTimeout(300);assert.equal(await page.locator('[data-cat-filter="student"]').getAttribute('aria-pressed'),'true');assert(Math.abs(await card.evaluate(e=>e.getBoundingClientRect().top)-before)<15);
  await openMenu(page);await page.locator('.sr-recent summary').click();await page.waitForTimeout(350);assert(await page.locator('.sr-recent-links a').count()>=2);await page.screenshot({path:path.join(output,`live-menu-${width}-${theme}.png`)});await page.keyboard.press('Escape');assert(await page.locator('.sh-menu>summary').evaluate(e=>e===document.activeElement));
  await goto(page,'/configurator.html?type=course');assert.equal(await page.locator('[data-contact-mode]').count(),4);assert.equal(await page.locator('.sr-recent').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  const hashes={};for(const p of ['assets/js/salon-return.js','assets/css/salon-return.css','assets/js/salon-portfolio.js','assets/js/salon-catalogue.js']){const r=await context.request.get('https://akademsalon.ru/'+p+'?live_verify='+release);assert.equal(r.status(),200);hashes[p]=crypto.createHash('sha256').update(await r.body()).digest('hex');assert.equal(hashes[p],manifest.files[p])}
  assert.deepEqual(errors,[]);assert(!blocked.some(x=>x.method!=='GET'));results.push({width,theme,status:'PASS',checks:['article explicit resume','recent menu and focus','PDF resume and immediate keyboard restart','catalogue Back facet and position','existing form contact hints unchanged','exact live asset hashes'],hashes,errors,blocked,submitted:false});
 }finally{await context.close()}
}}finally{await browser.close();const report={release,source_commit:manifest.source_commit,browser:'Chrome',data:'new context; consent=false; owner+QA excluded; APIs mocked; only public GET allowed',results};fs.writeFileSync(path.join(output,'live-smoke.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report))}
