// Real Chrome, all HTTP routed to the exact candidate. No production traffic.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import crypto from 'node:crypto';
const require=createRequire(process.env.SALON_NODE_DEPS+'/package.json');const {chromium}=require('playwright');
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),KEY='salon_return_v1',CAT='salon_catalog_return_v1',guide='/guide-kursovaya-za-nedelyu.html';
async function openMenu(page){const box=await page.locator('.sh-menu>summary').boundingBox();assert(box&&box.y>=0&&box.y+box.height<=page.viewportSize().height,'menu visible');await page.mouse.click(box.x+box.width/2,box.y+box.height/2)}
async function setup(opts={}){
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:opts.width||1440,height:900},colorScheme:opts.theme||'light',reducedMotion:opts.reduced?'reduce':'no-preference'}),errors=[],calls=[];
 await context.addInitScript(({opts})=>{const t=Date.now();localStorage.setItem('salon_consent',JSON.stringify({v:3,analytics:false,at:new Date(t-60000).toISOString(),expiresAt:new Date(t+86400000).toISOString()}));localStorage.setItem('salon_theme',opts.theme||'light');localStorage.setItem('salon_analytics_owner_device_v1',JSON.stringify({v:1}));sessionStorage.setItem('salon_analytics_qa_session_v1','1')},{opts});
 await context.route('**/*',async route=>{const r=route.request(),u=new URL(r.url());if(u.hostname!=='akademsalon.ru')return route.abort();if(u.pathname.startsWith('/api/')){calls.push({path:u.pathname,method:r.method(),body:r.postData()});return route.fulfill({json:{ok:true,authenticated:false,pay_online:true}})}if(opts.failPDF&&u.pathname.endsWith('.pdf'))return route.fulfill({status:503,body:'Unavailable'});const p=path.join(root,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname));if(!p.startsWith(root+'/'))throw Error('unsafe route');if(!fs.existsSync(p)||!fs.statSync(p).isFile())return route.fulfill({status:404,body:'Not found'});const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.pdf':'application/pdf','.woff2':'font/woff2'};return route.fulfill({path:p,contentType:mime[path.extname(p)]||'application/octet-stream'});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return {context,page,errors,calls};
}
const goto=async(p,url)=>{await p.goto('https://akademsalon.ru'+url,{waitUntil:'load'});await p.evaluate(()=>document.fonts.ready);};
const stored=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)||'null'),KEY);
async function headingRead(page,index=3){await page.mouse.wheel(0,350);await page.locator('article.doc h2').nth(index).evaluate(h=>window.scrollTo({top:scrollY+h.getBoundingClientRect().top-140,behavior:'instant'}));await page.waitForTimeout(650);}
async function test(name,fn,opts={}){const env=await setup(opts);try{await fn(env);assert.deepEqual(env.errors,[],'no JS errors');assert(!env.calls.some(x=>x.method!=='GET'),'no API writes');results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',error:String(e),pageErrors:env.errors});await env.page.screenshot({path:path.join(out,name+'.png'),fullPage:false}).catch(()=>{});throw e}finally{await env.context.close()}}
async function readyPDF(page,n){await page.waitForFunction(n=>document.querySelector('#pdf-page-number').value===String(n)&&document.querySelector('#pdf-loading').hidden&&!document.querySelector('#pdf-error').getClientRects().length,n);}
try{
 await test('article-explicit-resume-and-anchor',async({page})=>{
  await goto(page,guide+'?private=SYNTHETIC_SENTINEL#');await headingRead(page);let x=await stored(page);assert.equal(x.articles[0].section,3);assert(!JSON.stringify(x).includes('SENTINEL'));const rec=x.articles[0];
  await goto(page,'/knowledge.html');await goto(page,guide);assert(await page.locator('.sr-reading-return').isVisible());assert(await page.evaluate(()=>scrollY)<30);await page.waitForTimeout(650);assert.equal((await stored(page)).articles[0].section,3);
  await page.getByRole('button',{name:'Продолжить чтение →',exact:true}).click();assert.equal(await page.locator('article.doc h2').nth(3).evaluate(h=>h===document.activeElement),true);assert(Math.abs(await page.locator('article.doc h2').nth(3).evaluate(h=>h.getBoundingClientRect().top)-140)<15);
  await goto(page,guide+'#article-section-1');assert.equal(await page.locator('.sr-reading-return').count(),0);await page.waitForFunction(()=>Math.abs(document.querySelector('#article-section-1').getBoundingClientRect().top)<180);assert.equal((await stored(page)).articles[0].section,3);
 });
 await test('recent-clear-cross-tab',async({context,page})=>{
  await goto(page,guide);await headingRead(page);const other=await context.newPage();await goto(other,'/reviews.html?token=SYNTHETIC_SENTINEL');await goto(other,'/about.html');await openMenu(other);await other.locator('.sr-recent summary').click();assert.equal(await other.locator('.sr-recent-links a').count(),2);assert(!(await stored(other)).recent.some(x=>JSON.stringify(x).includes('SENTINEL')));assert.equal(await other.locator('.sr-recent-links a').first().getAttribute('href'),'/reviews.html');
  await other.getByRole('button',{name:'Очистить историю страниц и место чтения статей и PDF'}).click();assert.equal(await other.locator('.sr-recent summary').evaluate(e=>e===document.activeElement),true);assert.deepEqual((await stored(other)).articles,[]);assert.deepEqual((await stored(other)).recent,[]);await page.goto('https://akademsalon.ru/privacy.html');assert.deepEqual((await stored(other)).articles,[]);assert.deepEqual((await stored(other)).recent,[]);await other.keyboard.press('Escape');assert.equal(await other.locator('.sh-menu>summary').evaluate(e=>e===document.activeElement),true);
 });
 await test('pdf-page-zoom-and-separate-documents',async({page})=>{
  await goto(page,'/samples.html');await page.locator('.document-open').click();await readyPDF(page,1);await page.locator('#pdf-page-number').fill('4');await page.locator('#pdf-page-number').press('Enter');await readyPDF(page,4);await page.locator('#pdf-zoom-in').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('salon_return_v1')).pdfs[0].mode==='manual');const mark=(await stored(page)).pdfs[0];assert.equal(mark.page,4);await page.locator('#pdf-close').click();assert.equal(await page.locator('.document-open').evaluate(e=>e===document.activeElement),true);assert.match(await page.locator('.document-open').textContent(),/стр. 4/);
  await page.reload({waitUntil:'load'});await page.locator('.document-open').click();await readyPDF(page,4);assert.equal((await stored(page)).pdfs[0].scale,mark.scale);await page.locator('#pdf-fit').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('salon_return_v1')).pdfs[0].mode==='fit');await page.locator('#pdf-close').click();await page.locator('.sr-pdf-start').click();await readyPDF(page,1);await page.locator('#pdf-close').click();await page.locator('[data-type="essay"]').click();assert.match(await page.locator('.document-open').textContent(),/Читать/);await page.locator('.document-open').click();await readyPDF(page,1);assert.equal((await stored(page)).pdfs.length,2);await page.locator('#pdf-close').click();
 });
 await test('pdf-keyboard-immediate-reopen',async({page})=>{
  await goto(page,'/samples.html');await page.locator('.document-open').click();await readyPDF(page,1);await page.locator('#pdf-page-number').fill('5');await page.locator('#pdf-page-number').press('Enter');await readyPDF(page,5);await page.locator('#pdf-close').click();await page.reload({waitUntil:'load'});await page.locator('.document-open').press('Enter');await readyPDF(page,5);await page.locator('#pdf-close').click();await page.locator('.sr-pdf-start').press('Enter');await readyPDF(page,1);await page.locator('#pdf-close').click();
 });
 await test('pdf-load-failure-does-not-overwrite',async({page})=>{
  await goto(page,'/samples.html');await page.locator('.document-open').click();await readyPDF(page,1);await page.locator('#pdf-page-number').fill('5');await page.locator('#pdf-page-number').press('Enter');await readyPDF(page,5);await page.locator('#pdf-close').click();const before=(await stored(page)).pdfs;
  await page.route('**/*.pdf*',r=>r.fulfill({status:503,body:'Unavailable'}));await page.locator('.sr-pdf-start').click();await page.waitForFunction(()=>!document.querySelector('#pdf-error').hidden);assert.deepEqual((await stored(page)).pdfs,before);await page.locator('#pdf-close').click();
 });
 await test('catalogue-back-return-and-direct-anchor',async({page})=>{
  await goto(page,'/services.html');await page.locator('[data-cat-filter="student"]').click();await page.locator('[data-catalog-speed="express24"]').click();const card=page.locator('.cat-card[data-product="diplom"]');await card.scrollIntoViewIfNeeded();await card.click();await page.locator('.cat-close').click();const top=await card.evaluate(e=>e.getBoundingClientRect().top);
  await page.locator('.sh-nav a[href="samples.html"]').count().then(async n=>{if(n)await page.locator('.sh-nav a[href="samples.html"]').click();else{await openMenu(page);await page.locator('.sh-groups a[href="samples.html"]').click()}});await page.waitForLoadState('load');await page.goBack({waitUntil:'load'});await page.waitForTimeout(300);assert.equal(await page.locator('[data-cat-filter="student"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-catalog-speed="express24"]').getAttribute('aria-pressed'),'true');assert(Math.abs(await card.evaluate(e=>e.getBoundingClientRect().top)-top)<15,'back position');
  await openMenu(page);await page.locator('.sh-groups a[href="samples.html"]').click();await page.waitForLoadState('load');await openMenu(page);await page.locator('.sh-groups a[href="services.html"]').click();await page.waitForLoadState('load');await page.waitForTimeout(300);assert.equal(await page.locator('[data-cat-filter="student"]').getAttribute('aria-pressed'),'true');assert(Math.abs(await card.evaluate(e=>e.getBoundingClientRect().top)-top)<15,'internal return position');
  await goto(page,'/samples.html');await goto(page,'/services.html#works');assert.equal(await page.locator('[data-cat-filter="all"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.cat-card:not([hidden])').count(),12);
 });
 await test('catalogue-mobile-menu-return',async({page})=>{
  await goto(page,'/services.html');await page.locator('[data-cat-filter="science"]').click();const card=page.locator('.cat-card[data-product="kandidat"]');await card.scrollIntoViewIfNeeded();await card.click();await page.locator('.cat-close').click();await page.waitForTimeout(250);const before=await card.evaluate(e=>e.getBoundingClientRect().top);await openMenu(page);await page.locator('.sh-groups a[href="samples.html"]').click();await page.waitForLoadState('load');await page.goBack({waitUntil:'load'});await page.waitForTimeout(400);assert.equal(await page.locator('[data-cat-filter="science"]').getAttribute('aria-pressed'),'true');assert(Math.abs(await card.evaluate(e=>e.getBoundingClientRect().top)-before)<15,'mobile menu preserves exact position');
 },{width:390,theme:'dark'});
 await test('invalid-storage-preview-and-denial',async({page})=>{
  await goto(page,'/');await page.evaluate(k=>localStorage.setItem(k,JSON.stringify({v:1,recent:[{path:'https://evil.invalid/?secret',at:Date.now()},{path:'reviews.html',at:Date.now()+999999999}],articles:[null],pdfs:[{id:'__proto__',page:999999,at:Date.now()}]})),KEY);await goto(page,'/about.html');assert.deepEqual((await stored(page)).recent.map(x=>x.path),['about.html']);assert.deepEqual((await stored(page)).pdfs,[]);const before=await stored(page);await goto(page,'/reviews.html?desktop-preview=1');assert.deepEqual(await stored(page),before);assert.equal(await page.locator('.sr-recent').count(),0);
  await page.addInitScript(()=>{for(const m of ['getItem','setItem','removeItem'])Object.defineProperty(Storage.prototype,m,{value(){throw new DOMException('blocked','SecurityError')}})});await goto(page,guide);assert.equal(await page.locator('.sr-reading-return').count(),0);await page.locator('[data-reader-size]').click();await goto(page,'/samples.html');await page.locator('.document-open').click();await readyPDF(page,1);await page.locator('#pdf-close').click();
 });
 for(const width of [360,390,768,1024,1440])for(const theme of ['light','dark'])await test('visual-'+width+'-'+theme,async({page})=>{
  await goto(page,guide);await headingRead(page);await goto(page,'/reviews.html');await goto(page,guide);await page.screenshot({path:path.join(out,'article-'+width+'-'+theme+'.png')});await openMenu(page);await page.locator('.sr-recent summary').click();await page.waitForTimeout(350);await page.screenshot({path:path.join(out,'menu-'+width+'-'+theme+'.png')});const m=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,targets:[...document.querySelectorAll('.sr-recent summary,.sr-recent a,.sr-recent button')].filter(e=>e.getClientRects().length).map(e=>({height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width})),dialogOverflow:document.querySelector('#salon-navigation').scrollWidth-document.querySelector('#salon-navigation').clientWidth}));assert(m.overflow<=1);assert(m.dialogOverflow<=1);assert(m.targets.every(x=>x.height>=44&&x.width>=44));await page.keyboard.press('Escape');const targets=await page.locator('.sr-reading-return button').evaluateAll(a=>a.map(e=>({height:e.getBoundingClientRect().height,width:e.getBoundingClientRect().width})));assert(targets.every(x=>x.height>=44&&x.width>=44));
 },{width,theme,reduced:width===390});
}finally{await browser.close();const hashes=Object.fromEntries(['assets/js/salon-return.js','assets/css/salon-return.css','assets/js/salon-portfolio.js','assets/js/salon-catalogue.js'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')]));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({source,root,browser:'Chrome headless',network:'all routed; no external network; no API writes',hashes,results},null,2));console.log(JSON.stringify(results));}
